### ISSUE TITLE
no web service

### ISSUE THREAD

**Issue by Thijxx** [linuxserver/docker-calibre-web#100]
## Expected Behavior
web ui available

## Current Behavior
nothing running on port 8083

## Steps to Reproduce
1. deploy calibre-web
2. browse to host:8083

## Environment
**OS:**     CentOS7 
**CPU architecture:** x86_64
**How docker service was installed:**      
```
docker create \
  --name=caliweb \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/Amsterdam \
  -e DOCKER_MODS=linuxserver/calibre-web:calibre \
  -p 8083:8083 \
  -v /opt/pakhuis/calibre/webconfig:/config \
  -v /opt/pakhuis/boeken:/books \
  --restart unless-stopped \
  linuxserver/calibre-web:latest

```

## Docker logs
```
[mod-init] Attempting to run Docker Modification Logic
[mod-init] Applying linuxserver/calibre-web:calibre files to container
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
cp: cannot stat '/app/calibre-web/gdrive.db': No such file or directory
[cont-init.d] 30-config: exited 0.
[cont-init.d] 60-calibre-config: executing... 
Creating symlinks...
	Symlinking /app/calibre/ebook-device to /usr/bin/ebook-device
	Symlinking /app/calibre/ebook-meta to /usr/bin/ebook-meta
	Symlinking /app/calibre/ebook-convert to /usr/bin/ebook-convert
	Symlinking /app/calibre/ebook-polish to /usr/bin/ebook-polish
	Symlinking /app/calibre/markdown-calibre to /usr/bin/markdown-calibre
	Symlinking /app/calibre/web2disk to /usr/bin/web2disk
	Symlinking /app/calibre/calibre-server to /usr/bin/calibre-server
	Symlinking /app/calibre/lrf2lrs to /usr/bin/lrf2lrs
	Symlinking /app/calibre/lrs2lrf to /usr/bin/lrs2lrf
	Symlinking /app/calibre/calibre-debug to /usr/bin/calibre-debug
	Symlinking /app/calibre/calibredb to /usr/bin/calibredb
	Symlinking /app/calibre/calibre-parallel to /usr/bin/calibre-parallel
	Symlinking /app/calibre/calibre-customize to /usr/bin/calibre-customize
	Symlinking /app/calibre/fetch-ebook-metadata to /usr/bin/fetch-ebook-metadata
	Symlinking /app/calibre/calibre-smtp to /usr/bin/calibre-smtp
	Symlinking /app/calibre/calibre to /usr/bin/calibre
	Symlinking /app/calibre/lrfviewer to /usr/bin/lrfviewer
	Symlinking /app/calibre/ebook-viewer to /usr/bin/ebook-viewer
	Symlinking /app/calibre/ebook-edit to /usr/bin/ebook-edit
Setting up command-line completion...
Installing zsh completion to: /usr/share/zsh/vendor-completions/_calibre
Failed to find directory to install bash completions, using default.
Installing bash completion to: /usr/share/bash-completion/completions/

____________________ WARNING ____________________
Setting up completion failed with error:
__________________________________________________


	Traceback (most recent call last):
	  File "site-packages/calibre/linux.py", line 832, in setup_completion
	  File "site-packages/calibre/linux.py", line 574, in write_completion
	  File "site-packages/calibre/gui2/__init__.py", line 16, in <module>
	ImportError: cannot import name 'QApplication' from 'PyQt5.Qt' (/app/calibre/lib/python3.8/site-packages/PyQt5/Qt.abi3.so)

Setting up desktop integration...

____________________ WARNING ____________________
Setting up desktop integration failed with error:
__________________________________________________


	Traceback (most recent call last):
	  File "site-packages/calibre/linux.py", line 900, in setup_desktop_integration
	  File "site-packages/calibre/linux.py", line 885, in install_icons
	  File "site-packages/calibre/linux.py", line 875, in install_single_icon
	  File "site-packages/calibre/linux.py", line 1219, in render_img
	ImportError: cannot import name 'QImage' from 'PyQt5.Qt' (/app/calibre/lib/python3.8/site-packages/PyQt5/Qt.abi3.so)

Creating un-installer: /usr/bin/calibre-uninstall


There were 2 warnings

* Setting up completion failed with error:

* Setting up desktop integration failed with error:


WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Get:1 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:4 http://archive.ubuntu.com/ubuntu bionic/multiverse Sources [216 kB]
Get:5 http://archive.ubuntu.com/ubuntu bionic/universe Sources [11.5 MB]
Get:6 http://archive.ubuntu.com/ubuntu bionic/restricted Sources [5,823 B]
Get:7 http://archive.ubuntu.com/ubuntu bionic/main Sources [1,063 kB]
Get:8 http://archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [186 kB]
Get:9 http://archive.ubuntu.com/ubuntu bionic/restricted amd64 Packages [13.5 kB]
Get:10 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
Get:11 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1,344 kB]
Get:12 http://archive.ubuntu.com/ubuntu bionic-updates/restricted Sources [18.3 kB]
Get:13 http://archive.ubuntu.com/ubuntu bionic-updates/universe Sources [542 kB]
Get:14 http://archive.ubuntu.com/ubuntu bionic-updates/main Sources [620 kB]
Get:15 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse Sources [11.6 kB]
Get:16 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [2,095 kB]
Get:17 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [2,110 kB]
Get:18 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [220 kB]
Get:19 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [44.6 kB]
Get:20 http://archive.ubuntu.com/ubuntu bionic-security/restricted Sources [13.0 kB]
Get:21 http://archive.ubuntu.com/ubuntu bionic-security/multiverse Sources [4,359 B]
Get:22 http://archive.ubuntu.com/ubuntu bionic-security/main Sources [295 kB]
Get:23 http://archive.ubuntu.com/ubuntu bionic-security/universe Sources [326 kB]
Get:24 http://archive.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [193 kB]
Get:25 http://archive.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [14.6 kB]
Get:26 http://archive.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [1,332 kB]
Get:27 http://archive.ubuntu.com/ubuntu bionic-security/main amd64 Packages [1,693 kB]
Fetched 35.6 MB in 4s (9,476 kB/s)
Reading package lists...
Building dependency tree...
Reading state information...
All packages are up to date.

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libdrm-amdgpu1 libdrm-common libdrm-intel1 libdrm-nouveau2 libdrm-radeon1
  libdrm2 libedit2 libelf1 libgl1 libgl1-mesa-dri libglapi-mesa libglvnd0
  libglx-mesa0 libglx0 libllvm10 libpciaccess0 libsensors4 libx11-xcb1
  libxcb-dri2-0 libxcb-dri3-0 libxcb-glx0 libxcb-present0 libxcb-sync1
  libxdamage1 libxfixes3 libxshmfence1 libxxf86vm1
Suggested packages:
  pciutils lm-sensors
The following NEW packages will be installed:
  libdrm-amdgpu1 libdrm-common libdrm-intel1 libdrm-nouveau2 libdrm-radeon1
  libdrm2 libedit2 libelf1 libgl1 libgl1-mesa-dri libgl1-mesa-glx
  libglapi-mesa libglvnd0 libglx-mesa0 libglx0 libllvm10 libpciaccess0
  libsensors4 libx11-xcb1 libxcb-dri2-0 libxcb-dri3-0 libxcb-glx0
  libxcb-present0 libxcb-sync1 libxdamage1 libxfixes3 libxshmfence1
  libxxf86vm1
0 upgraded, 28 newly installed, 0 to remove and 0 not upgraded.
Need to get 25.5 MB of archives.
After this operation, 327 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic/main amd64 libxxf86vm1 amd64 1:1.1.4-1 [10.6 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libelf1 amd64 0.170-0.4ubuntu0.1 [44.8 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libdrm-common all 2.4.101-2~18.04.1 [5,560 B]
Get:4 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libdrm2 amd64 2.4.101-2~18.04.1 [32.3 kB]
Get:5 http://archive.ubuntu.com/ubuntu bionic/main amd64 libedit2 amd64 3.1-20170329-1 [76.9 kB]
Get:6 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libdrm-amdgpu1 amd64 2.4.101-2~18.04.1 [18.2 kB]
Get:7 http://archive.ubuntu.com/ubuntu bionic/main amd64 libpciaccess0 amd64 0.14-1 [17.9 kB]
Get:8 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libdrm-intel1 amd64 2.4.101-2~18.04.1 [60.0 kB]
Get:9 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libdrm-nouveau2 amd64 2.4.101-2~18.04.1 [16.5 kB]
Get:10 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libdrm-radeon1 amd64 2.4.101-2~18.04.1 [21.7 kB]
Get:11 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libglapi-mesa amd64 20.0.8-0ubuntu1~18.04.1 [26.6 kB]
Get:12 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libllvm10 amd64 1:10.0.0-4ubuntu1~18.04.2 [15.4 MB]
Get:13 http://archive.ubuntu.com/ubuntu bionic/main amd64 libsensors4 amd64 1:3.4.0-4 [28.8 kB]
Get:14 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libgl1-mesa-dri amd64 20.0.8-0ubuntu1~18.04.1 [9,333 kB]
Get:15 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libglvnd0 amd64 1.0.0-2ubuntu2.3 [47.0 kB]
Get:16 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libx11-xcb1 amd64 2:1.6.4-3ubuntu0.3 [9,628 B]
Get:17 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libxcb-dri2-0 amd64 1.13-2~ubuntu18.04 [6,920 B]
Get:18 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libxcb-dri3-0 amd64 1.13-2~ubuntu18.04 [6,568 B]
Get:19 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libxcb-glx0 amd64 1.13-2~ubuntu18.04 [22.1 kB]
Get:20 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libxcb-present0 amd64 1.13-2~ubuntu18.04 [5,552 B]
Get:21 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libxcb-sync1 amd64 1.13-2~ubuntu18.04 [8,808 B]
Get:22 http://archive.ubuntu.com/ubuntu bionic/main amd64 libxdamage1 amd64 1:1.1.4-3 [6,934 B]
Get:23 http://archive.ubuntu.com/ubuntu bionic/main amd64 libxfixes3 amd64 1:5.0.3-1 [10.8 kB]
Get:24 http://archive.ubuntu.com/ubuntu bionic/main amd64 libxshmfence1 amd64 1.3-1 [5,028 B]
Get:25 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libglx-mesa0 amd64 20.0.8-0ubuntu1~18.04.1 [139 kB]
Get:26 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libglx0 amd64 1.0.0-2ubuntu2.3 [28.1 kB]
Get:27 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libgl1 amd64 1.0.0-2ubuntu2.3 [86.2 kB]
Get:28 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libgl1-mesa-glx amd64 20.0.8-0ubuntu1~18.04.1 [5,532 B]
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76, <> line 28.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7, <> line 28.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: 
Fetched 25.5 MB in 1s (32.0 MB/s)
Selecting previously unselected package libxxf86vm1:amd64.
(Reading database ... 11433 files and directories currently installed.)
Preparing to unpack .../00-libxxf86vm1_1%3a1.1.4-1_amd64.deb ...
Unpacking libxxf86vm1:amd64 (1:1.1.4-1) ...
Selecting previously unselected package libelf1:amd64.
Preparing to unpack .../01-libelf1_0.170-0.4ubuntu0.1_amd64.deb ...
Unpacking libelf1:amd64 (0.170-0.4ubuntu0.1) ...
Selecting previously unselected package libdrm-common.
Preparing to unpack .../02-libdrm-common_2.4.101-2~18.04.1_all.deb ...
Unpacking libdrm-common (2.4.101-2~18.04.1) ...
Selecting previously unselected package libdrm2:amd64.
Preparing to unpack .../03-libdrm2_2.4.101-2~18.04.1_amd64.deb ...
Unpacking libdrm2:amd64 (2.4.101-2~18.04.1) ...
Selecting previously unselected package libedit2:amd64.
Preparing to unpack .../04-libedit2_3.1-20170329-1_amd64.deb ...
Unpacking libedit2:amd64 (3.1-20170329-1) ...
Selecting previously unselected package libdrm-amdgpu1:amd64.
Preparing to unpack .../05-libdrm-amdgpu1_2.4.101-2~18.04.1_amd64.deb ...
Unpacking libdrm-amdgpu1:amd64 (2.4.101-2~18.04.1) ...
Selecting previously unselected package libpciaccess0:amd64.
Preparing to unpack .../06-libpciaccess0_0.14-1_amd64.deb ...
Unpacking libpciaccess0:amd64 (0.14-1) ...
Selecting previously unselected package libdrm-intel1:amd64.
Preparing to unpack .../07-libdrm-intel1_2.4.101-2~18.04.1_amd64.deb ...
Unpacking libdrm-intel1:amd64 (2.4.101-2~18.04.1) ...
Selecting previously unselected package libdrm-nouveau2:amd64.
Preparing to unpack .../08-libdrm-nouveau2_2.4.101-2~18.04.1_amd64.deb ...
Unpacking libdrm-nouveau2:amd64 (2.4.101-2~18.04.1) ...
Selecting previously unselected package libdrm-radeon1:amd64.
Preparing to unpack .../09-libdrm-radeon1_2.4.101-2~18.04.1_amd64.deb ...
Unpacking libdrm-radeon1:amd64 (2.4.101-2~18.04.1) ...
Selecting previously unselected package libglapi-mesa:amd64.
Preparing to unpack .../10-libglapi-mesa_20.0.8-0ubuntu1~18.04.1_amd64.deb ...
Unpacking libglapi-mesa:amd64 (20.0.8-0ubuntu1~18.04.1) ...
Selecting previously unselected package libllvm10:amd64.
Preparing to unpack .../11-libllvm10_1%3a10.0.0-4ubuntu1~18.04.2_amd64.deb ...
Unpacking libllvm10:amd64 (1:10.0.0-4ubuntu1~18.04.2) ...
Selecting previously unselected package libsensors4:amd64.
Preparing to unpack .../12-libsensors4_1%3a3.4.0-4_amd64.deb ...
Unpacking libsensors4:amd64 (1:3.4.0-4) ...
Selecting previously unselected package libgl1-mesa-dri:amd64.
Preparing to unpack .../13-libgl1-mesa-dri_20.0.8-0ubuntu1~18.04.1_amd64.deb ...
Unpacking libgl1-mesa-dri:amd64 (20.0.8-0ubuntu1~18.04.1) ...
Selecting previously unselected package libglvnd0:amd64.
Preparing to unpack .../14-libglvnd0_1.0.0-2ubuntu2.3_amd64.deb ...
Unpacking libglvnd0:amd64 (1.0.0-2ubuntu2.3) ...
Selecting previously unselected package libx11-xcb1:amd64.
Preparing to unpack .../15-libx11-xcb1_2%3a1.6.4-3ubuntu0.3_amd64.deb ...
Unpacking libx11-xcb1:amd64 (2:1.6.4-3ubuntu0.3) ...
Selecting previously unselected package libxcb-dri2-0:amd64.
Preparing to unpack .../16-libxcb-dri2-0_1.13-2~ubuntu18.04_amd64.deb ...
Unpacking libxcb-dri2-0:amd64 (1.13-2~ubuntu18.04) ...
Selecting previously unselected package libxcb-dri3-0:amd64.
Preparing to unpack .../17-libxcb-dri3-0_1.13-2~ubuntu18.04_amd64.deb ...
Unpacking libxcb-dri3-0:amd64 (1.13-2~ubuntu18.04) ...
Selecting previously unselected package libxcb-glx0:amd64.
Preparing to unpack .../18-libxcb-glx0_1.13-2~ubuntu18.04_amd64.deb ...
Unpacking libxcb-glx0:amd64 (1.13-2~ubuntu18.04) ...
Selecting previously unselected package libxcb-present0:amd64.
Preparing to unpack .../19-libxcb-present0_1.13-2~ubuntu18.04_amd64.deb ...
Unpacking libxcb-present0:amd64 (1.13-2~ubuntu18.04) ...
Selecting previously unselected package libxcb-sync1:amd64.
Preparing to unpack .../20-libxcb-sync1_1.13-2~ubuntu18.04_amd64.deb ...
Unpacking libxcb-sync1:amd64 (1.13-2~ubuntu18.04) ...
Selecting previously unselected package libxdamage1:amd64.
Preparing to unpack .../21-libxdamage1_1%3a1.1.4-3_amd64.deb ...
Unpacking libxdamage1:amd64 (1:1.1.4-3) ...
Selecting previously unselected package libxfixes3:amd64.
Preparing to unpack .../22-libxfixes3_1%3a5.0.3-1_amd64.deb ...
Unpacking libxfixes3:amd64 (1:5.0.3-1) ...
Selecting previously unselected package libxshmfence1:amd64.
Preparing to unpack .../23-libxshmfence1_1.3-1_amd64.deb ...
Unpacking libxshmfence1:amd64 (1.3-1) ...
Selecting previously unselected package libglx-mesa0:amd64.
Preparing to unpack .../24-libglx-mesa0_20.0.8-0ubuntu1~18.04.1_amd64.deb ...
Unpacking libglx-mesa0:amd64 (20.0.8-0ubuntu1~18.04.1) ...
Selecting previously unselected package libglx0:amd64.
Preparing to unpack .../25-libglx0_1.0.0-2ubuntu2.3_amd64.deb ...
Unpacking libglx0:amd64 (1.0.0-2ubuntu2.3) ...
Selecting previously unselected package libgl1:amd64.
Preparing to unpack .../26-libgl1_1.0.0-2ubuntu2.3_amd64.deb ...
Unpacking libgl1:amd64 (1.0.0-2ubuntu2.3) ...
Selecting previously unselected package libgl1-mesa-glx:amd64.
Preparing to unpack .../27-libgl1-mesa-glx_20.0.8-0ubuntu1~18.04.1_amd64.deb ...
Unpacking libgl1-mesa-glx:amd64 (20.0.8-0ubuntu1~18.04.1) ...
Setting up libedit2:amd64 (3.1-20170329-1) ...
Setting up libxcb-present0:amd64 (1.13-2~ubuntu18.04) ...
Setting up libglvnd0:amd64 (1.0.0-2ubuntu2.3) ...
Setting up libxcb-dri2-0:amd64 (1.13-2~ubuntu18.04) ...
Setting up libxcb-dri3-0:amd64 (1.13-2~ubuntu18.04) ...
Setting up libxcb-glx0:amd64 (1.13-2~ubuntu18.04) ...
Setting up libllvm10:amd64 (1:10.0.0-4ubuntu1~18.04.2) ...
Setting up libxdamage1:amd64 (1:1.1.4-3) ...
Setting up libxfixes3:amd64 (1:5.0.3-1) ...
Setting up libelf1:amd64 (0.170-0.4ubuntu0.1) ...
Setting up libxshmfence1:amd64 (1.3-1) ...
Setting up libglapi-mesa:amd64 (20.0.8-0ubuntu1~18.04.1) ...
Setting up libdrm-common (2.4.101-2~18.04.1) ...
Setting up libxcb-sync1:amd64 (1.13-2~ubuntu18.04) ...
Setting up libx11-xcb1:amd64 (2:1.6.4-3ubuntu0.3) ...
Setting up libpciaccess0:amd64 (0.14-1) ...
Setting up libsensors4:amd64 (1:3.4.0-4) ...
Setting up libxxf86vm1:amd64 (1:1.1.4-1) ...
Setting up libdrm2:amd64 (2.4.101-2~18.04.1) ...
Setting up libdrm-intel1:amd64 (2.4.101-2~18.04.1) ...
Setting up libdrm-radeon1:amd64 (2.4.101-2~18.04.1) ...
Setting up libdrm-nouveau2:amd64 (2.4.101-2~18.04.1) ...
Setting up libdrm-amdgpu1:amd64 (2.4.101-2~18.04.1) ...
Setting up libgl1-mesa-dri:amd64 (20.0.8-0ubuntu1~18.04.1) ...
Setting up libglx-mesa0:amd64 (20.0.8-0ubuntu1~18.04.1) ...
Setting up libglx0:amd64 (1.0.0-2ubuntu2.3) ...
Setting up libgl1:amd64 (1.0.0-2ubuntu2.3) ...
Setting up libgl1-mesa-glx:amd64 (20.0.8-0ubuntu1~18.04.1) ...
Processing triggers for libc-bin (2.27-3ubuntu1.2) ...
[cont-init.d] 60-calibre-config: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[mod-init] Attempting to run Docker Modification Logic
[mod-init] Applying linuxserver/calibre-web:calibre files to container
[mod-init] linuxserver/calibre-web:calibre at sha256:e210e0863fc592eaa4b16f6593048924cb7471fec00ab224889eb1f1782d6799 has been previously applied skipping
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 60-calibre-config: executing... 
[cont-init.d] 60-calibre-config: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

```

**Comment by CHBMB** [comment]
Can you try removing `  -e DOCKER_MODS=linuxserver/calibre-web:calibre \` and just to check after the `docker create` you are running it aren't you?

**Comment by Thijxx** [comment]
I'm entirely sure what you're saying but I removed the DOCKER_MODS line and re-created the container. The issue is still the same. It looks fine but no service on the port. it must be something on the Docker host that I have messed up and is not needed by my other containers, but I can't think of anything.

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1000
User gid:    1000
-------------------------------------
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

**Comment by Thijxx** [comment]
There is something wrong with the ports on my host, don't know what but randomizing the exposed port fixed it.

**Comment by tdiekel** [comment]
I had a similar issue which was also fixed by switching to another port.
