### ISSUE TITLE
Book convertion from AZW3 to PDF failed on linuxserver/calibre-web:0.6.9-ls83

### ISSUE THREAD

**Issue by adamcavendish** [linuxserver/docker-calibre-web#101]
Calling ebook-convert failed on linuxserver/calibre-web:0.6.9-ls83.

The related log is attached as:

```
[2020-10-09 10:29:53,259]  INFO {cps.editbooks:902} converting: book id: 230 from: AZW3 to: PDF
[2020-10-09 10:29:53,273]  INFO {cps.worker:209} 2
[2020-10-09 10:29:53,273]  INFO {cps.worker:210} 3
[2020-10-09 10:29:53,274]  INFO {cps.worker:303} Book id 230 - target format of .pdf does not exist. Moving forward with convert.
[2020-10-09 10:29:53,718] DEBUG {cps.worker:382} No write acces to /root/.config/calibre using a temporary dir instead
[2020-10-09 10:29:53,835] DEBUG {cps.worker:382} 1% Converting input to HTML...
[2020-10-09 10:29:53,927] DEBUG {cps.worker:382} 
[2020-10-09 10:29:53,928] DEBUG {cps.worker:395} Traceback (most recent call last):
[2020-10-09 10:29:53,928] DEBUG {cps.worker:395}   File "runpy.py", line 194, in _run_module_as_main
[2020-10-09 10:29:53,929] DEBUG {cps.worker:395}   File "runpy.py", line 87, in _run_code
[2020-10-09 10:29:53,929] DEBUG {cps.worker:395}   File "site.py", line 48, in <module>
[2020-10-09 10:29:53,929] DEBUG {cps.worker:395}   File "site.py", line 44, in main
[2020-10-09 10:29:53,929] DEBUG {cps.worker:395}   File "site-packages/calibre/ebooks/conversion/cli.py", line 401, in main
[2020-10-09 10:29:53,929] DEBUG {cps.worker:395}   File "site-packages/calibre/ebooks/conversion/plumber.py", line 1106, in run
[2020-10-09 10:29:53,930] DEBUG {cps.worker:395}   File "site-packages/calibre/ebooks/conversion/plugins/pdf_output.py", line 151, in specialize_options
[2020-10-09 10:29:53,930] DEBUG {cps.worker:395} ImportError: libXi.so.6: cannot open shared object file: No such file or directory
[2020-10-09 10:29:53,930]  INFO {cps.worker:347} ebook converter failed with error while converting book
[2020-10-09 10:29:53,930] ERROR {cps.worker:567} Calibre failed with error: ImportError: libXi.so.6: cannot open shared object file: No such file or directory
```

## Steps to Reproduce
1. Install a new docker-calibre-web with with docker version `linuxserver/calibre-web:0.6.9-ls83`
2. Follow the guideline to initialize everything
3. Use `/usr/bin/ebook-convert` in `Basic Configuration -> External binaries -> Path to Calibre E-Book Converter`
4. Try to convert an AWS format file to PDF format.
5. Find the failure in the logging

## Steps to Fix

I don't know whether ebook-convert do rely on X11 or not but after I installed the libs the errors are gone.

1. `apt install -y libxi-dev`

## Environment

OS: Ubuntu 18.04 HWE
Arch: x86_64

**Comment by davosian** [comment]
Installing libXi with `apt install -y libxi6` worked as well.

**Comment by CHBMB** [comment]
@davosian Just came to say that!

Shouldn't need the `dev` package.  Have pushed a fix for this and confirmed the issue and fix is working locally.

I think @adamcavendish means `AZW3` rather than `AWS` as well
