### ISSUE TITLE
Cifs volume conflict with sqlalchemy

### ISSUE THREAD

**Issue by JamesM92** [linuxserver/docker-calibre-web#138]
## Expected Behavior
When creating a docker volume using a cifs share folder for the config directory, the system should be able to look up the metadata.db and other information and operate like normal.

## Current Behavior
When setting the config folder to a cifs shared volume, it is able to to see the folder, and add and remove files and access like normal, but then it has issues with the sqlalchemy database.  This causes the entire application to crash.

This doesnt happen when setting it to a local volume, when set to a local volume it operates fine as expected.

## Steps to Reproduce
1.install with config volume mounted localy and everything works
2.re-install with config volume on a cifs volume and it starts having errors with database

## Environment
OS: Open Media Vault 5
CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**
Open Media Vault extras install.

## Command used to create docker container 
using stack in portainer to create the calibre-web service
```
---
version: "2.1"
services:
  calibre-web:
    image: ghcr.io/linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Denver
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    volumes:
      - config:/config
    ports:
      - 8083:8083
    restart: unless-stopped
    
volumes:
  config:
    driver: local
    driver_opts:
      type: cifs
      device: "//192.168.0.XXX/portainer/Calibre-Web/config"
      o: "username=portainer,password=XXXXXXXX,vers=3.0,uid=0,gid=0"


```

## Docker logs
 ```
 File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/visitors.py", line 145, in traverse_single,
    return meth(obj, **kw),
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/ddl.py", line 783, in visit_metadata,
    self.traverse_single(,
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/visitors.py", line 145, in traverse_single,
    return meth(obj, **kw),
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/ddl.py", line 827, in visit_table,
    self.connection.execute(,
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1011, in execute,
    return meth(self, multiparams, params),
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection,
    return connection._execute_ddl(self, multiparams, params),
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1068, in _execute_ddl,
    ret = self._execute_context(,
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context,
    self._handle_dbapi_exception(,
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception,
    util.raise_(,
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 182, in raise_,
    raise exception,
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context,
    self.dialect.do_execute(,
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 608, in do_execute,
    cursor.execute(statement, parameters),
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked,
[SQL: ,
CREATE TABLE flask_dance_oauth (,
	id INTEGER NOT NULL, ,
	provider VARCHAR(50) NOT NULL, ,
	created_at DATETIME NOT NULL, ,
	token TEXT NOT NULL, ,
	provider_user_id VARCHAR(256), ,
	user_id INTEGER, ,
	PRIMARY KEY (id), ,
	FOREIGN KEY(user_id) REFERENCES user (id),
),
,
],
(Background on this error at: http://sqlalche.me/e/13/e3q8),
Traceback (most recent call last):,
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context,
    self.dialect.do_execute(,
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 608, in do_execute,
    cursor.execute(statement, parameters),
sqlite3.OperationalError: database is locked,
,
The above exception was the direct cause of the following exception:,
,
Traceback (most recent call last):,
  File "/app/calibre-web/cps.py", line 34, in <module>,
    from cps import create_app,
  File "/app/calibre-web/cps/__init__.py", line 73, in <module>,
    ub.init_db(cli.settingspath),
  File "/app/calibre-web/cps/ub.py", line 677, in init_db,
    Base.metadata.create_all(engine),
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/schema.py", line 4664, in create_all,
    bind._run_visitor(,
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 2095, in _run_visitor,
    conn._run_visitor(visitorcallable, element, **kwargs),
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1656, in _run_visitor,
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element),
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/visitors.py", line 145, in traverse_single,
    return meth(obj, **kw),
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/ddl.py", line 783, in visit_metadata,
    self.traverse_single(,
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/visitors.py", line 145, in traverse_single,
    return meth(obj, **kw),
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/ddl.py", line 827, in visit_table,
    self.connection.execute(,
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1011, in execute,
    return meth(self, multiparams, params),
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection,
    return connection._execute_ddl(self, multiparams, params),
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1068, in _execute_ddl,
    ret = self._execute_context(,
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context,
    self._handle_dbapi_exception(,
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception,
    util.raise_(,
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 182, in raise_,
    raise exception,
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context,
    self.dialect.do_execute(,
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 608, in do_execute,
    cursor.execute(statement, parameters),
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked,
[SQL: ,
CREATE TABLE flask_dance_oauth (,
	id INTEGER NOT NULL, ,
	provider VARCHAR(50) NOT NULL, ,
	created_at DATETIME NOT NULL, ,
	token TEXT NOT NULL, ,
	provider_user_id VARCHAR(256), ,
	user_id INTEGER, ,
	PRIMARY KEY (id), ,
	FOREIGN KEY(user_id) REFERENCES user (id),
),
,
],
(Background on this error at: http://sqlalche.me/e/13/e3q8),
```

**Comment by Roxedus** [comment]
This isn't a image issue. This is due to how SQLite works, there's nothing we can do about this.

**Comment by JamesM92** [comment]
This is an expected issue?

I'm not understanding why the sqlite which is in the /usr/local/lib folder is being affected by where the /config folder is being mounted. 

Is there no way of mounting another volume locally to satisfy what sqlite is looking for? Or is it that the config volume is required to be on the local disk (and if so shouldn't that be mentioned on the read.me?)

**Comment by Roxedus** [comment]
The SQLite database is in /config
