### ISSUE TITLE
File uploads and then move fails with errors

### ISSUE THREAD

**Issue by ITestInProd** [linuxserver/docker-calibre-web#153]
## Expected Behavior
Upload succeeds and the eBook is imported successfully into the Calibre database.

## Current Behavior
Upload fails with partial file move into an "Unknown" directory completed. The eBook is left in a halfway imported state. Attempting to further modify the eBook properties fails.

## Steps to Reproduce

1. Calibre database as well as eBooks reside on NFS storage presented to the Docker host
2. Enable debug logging in calibre-web
3. Enable file upload
4. Allow calibre-web to restart automatically
5. Upload a file
6. Observe errors in web browser

## Environment
**OS:** CentOS 7.9.2009
**CPU architecture:** x86_64
**How docker service was installed:** Docker version 20.10.7 from upstream. Orchestration is via Rancher; have observed same failures independently of orchestration layer. SElinux is enforcing.

## Command used to create docker container (run/create/compose/screenshot)
Mount points:
/nfs/data/books:/books
/nfs/config/calibreweb:/config

Environment vars:
"PGID=30502"
"TZ=America/Chicago"
"DOCKER_MODS=linuxserver/calibre-web:calibre"
"PUID=21023"

## Docker logs
No relevant data in Docker logs. Debug log output from app:
```
[2021-07-20 13:49:04,282] DEBUG {cps.uploader:315} Temporary file: /tmp/calibre_web/ef5a8b75c7087bc7d0f66747e5788b65
[2021-07-20 13:49:09,389] ERROR {cps.helper:386} Rename title from: /tmp/calibre_web/ef5a8b75c7087bc7d0f66747e5788b65 to /books/Unknown/hakcing-police (363): [Errno 1] Operation not permitted: '/books/Unknown/hakcing-police (363)/hakcing-police.pdf'
[2021-07-20 13:49:09,390] DEBUG {cps.helper:387} [Errno 1] Operation not permitted: '/books/Unknown/hakcing-police (363)/hakcing-police.pdf'
Traceback (most recent call last):
  File "/usr/lib/python3.8/shutil.py", line 791, in move
    os.rename(src, real_dst)
OSError: [Errno 18] Invalid cross-device link: '/tmp/calibre_web/ef5a8b75c7087bc7d0f66747e5788b65' -> '/books/Unknown/hakcing-police (363)/hakcing-police.pdf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/calibre-web/cps/helper.py", line 367, in update_dir_structure_file
    shutil.move(os.path.normcase(path), os.path.normcase(os.path.join(new_path, db_filename)))
  File "/usr/lib/python3.8/shutil.py", line 811, in move
    copy_function(src, real_dst)
  File "/usr/lib/python3.8/shutil.py", line 436, in copy2
    copystat(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.8/shutil.py", line 381, in copystat
    lookup("chmod")(dst, mode, follow_symlinks=follow)
PermissionError: [Errno 1] Operation not permitted: '/books/Unknown/hakcing-police (363)/hakcing-police.pdf'
[2021-07-20 13:49:09,396] ERROR {cps.editbooks:976} Failed to move cover file /books/Unknown/hakcing-police/cover.jpg: [Errno 2] No such file or directory: '/books/Unknown/hakcing-police/cover.jpg'
[2021-07-20 13:49:09,595] DEBUG {cps.services.worker:72} Add Task for user: admin: <cps.tasks.upload.TaskUpload object at 0x7f2c0032f940>
```

Web browser errors:
```
Failed to Move Cover File /books/Unknown/hakcing-police/cover.jpg: [Errno 2] No such file or directory: '/books/Unknown/hakcing-police/cover.jpg'

Rename title from: '/tmp/calibre_web/ef5a8b75c7087bc7d0f66747e5788b65' to '/books/Unknown/hakcing-police (363)' failed with error: [Errno 1] Operation not permitted: '/books/Unknown/hakcing-police (363)/hakcing-police.pdf'
```

**Comment by CHBMB** [comment]
I can't reproduce this my end.

```
[2021-07-20 20:43:14,861] DEBUG {cps.updater:303} Stable version: {'version': '0.6.13 Beta'}
[2021-07-20 20:43:44,676] DEBUG {cps.uploader:315} Temporary file: /tmp/calibre_web/4ac84fdb39b740f9ed68e4890de25618
[2021-07-20 20:43:48,890] DEBUG {cps.helper:369} Moving title: /tmp/calibre_web/4ac84fdb39b740f9ed68e4890de25618 to /books/Unknown/March 2021 (2813)/March 2021 - Unknown
[2021-07-20 20:43:49,048] DEBUG {cps.services.worker:72} Add Task for user: chbmbl: <cps.tasks.upload.TaskUpload object at 0x14a18edb7880>
```

Couple of differences between my setup and yours.  I'm not using NFS mounts, and I'm using the `nightly` tag and you haven't specified which version you're using.

So might be worth trying nightly and probably worthwhile checking that the user corresponding to the PUID of 21023 has write perms as looking at your logs it looks like a problem moving the file to the destination.

**Comment by ITestInProd** [comment]
The original image was using `latest` and the same issue occurs on `nightly`.

Perms (from host OS) on directory root:
```
[root@docker02 ~]# stat /nfs/data/books
  File: ‘/nfs/data/books’
  Size: 11        	Blocks: 97         IO Block: 32768  directory
Device: 33h/51d	Inode: 4           Links: 9
Access: (0775/drwxrwxr-x)  Uid: (21023/ UNKNOWN)   Gid: (30502/ UNKNOWN)
Context: system_u:object_r:nfs_t:s0
Access: 2018-03-09 09:23:06.132849066 -0600
Modify: 2021-07-20 15:14:24.647097807 -0500
Change: 2021-07-20 15:14:24.647097807 -0500
 Birth: -
[root@docker02 ~]#
```

Perms and file creation test (from container):
```
root@cc990ad4ca17:/# id abc
uid=21023(abc) gid=30502(abc) groups=30502(abc),100(users)
root@cc990ad4ca17:/# stat /books/
  File: /books/
  Size: 126       	Blocks: 33         IO Block: 32768  directory
Device: 33h/51d	Inode: 41          Links: 124
Access: (0775/drwxrwxr-x)  Uid: (21023/     abc)   Gid: (30502/     abc)
Access: 2018-03-09 09:45:41.028502312 -0600
Modify: 2021-07-20 15:35:10.500390257 -0500
Change: 2021-07-20 15:35:10.500390257 -0500
 Birth: -
root@cc990ad4ca17:/# touch /books/abcxyz
root@cc990ad4ca17:/# stat /books/abcxyz 
  File: /books/abcxyz
  Size: 0         	Blocks: 1          IO Block: 131072 regular empty file
Device: 33h/51d	Inode: 33039       Links: 1
Access: (0775/-rwxrwxr-x)  Uid: (    0/    root)   Gid: (30502/     abc)
Access: 2021-07-20 16:02:39.555236962 -0500
Modify: 2021-07-20 16:02:39.555237730 -0500
Change: 2021-07-20 16:02:39.555243387 -0500
 Birth: -
root@cc990ad4ca17:/#
```

**Comment by ServerGeek82** [comment]
I can confirm repro on the current version as well.

On the dark theme, it shows an interesting error in the logs.

`[2021-07-20 17:10:59,642]  INFO {cps:101} Starting Calibre Web...
[2021-07-20 17:10:59,849] ERROR {cps.server:133} [Errno 97] Address family not supported by protocol
[2021-07-20 17:10:59,849]  WARN {cps.server:134} Unable to listen on "", trying on IPv4 only...
[2021-07-20 17:10:59,850]  INFO {cps.server:205} Starting Gevent server on :8083
[2021-07-20 17:12:59,614]  INFO {cps.editbooks:863} Uploaded book probably exists in library
[2021-07-20 19:26:39,277]  INFO {cps.editbooks:863} Uploaded book probably exists in library
[2021-07-20 19:27:27,932]  WARN {cps.admin:159} reconnecting to calibre database
[2021-07-20 19:27:36,092]  INFO {cps.server:273} webserver stop (restart=True)
[2021-07-20 19:27:37,098]  INFO {cps.server:261} Performing restart of Calibre-Web
[2021-07-20 19:27:39,860]  INFO {cps:101} Starting Calibre Web...
[2021-07-20 19:27:40,123] ERROR {cps.server:133} [Errno 97] Address family not supported by protocol
[2021-07-20 19:27:40,124]  WARN {cps.server:134} Unable to listen on "", trying on IPv4 only...
[2021-07-20 19:27:40,125]  INFO {cps.server:205} Starting Gevent server on :8083
[2021-07-20 19:27:43,221]  WARN {cps.admin:159} reconnecting to calibre database
[2021-07-20 19:27:53,061]  INFO {cps.editbooks:863} Uploaded book probably exists in library`


Oops! Selected book title is unavailable. File does not exist or is not accessible

**Comment by CHBMB** [comment]
@ServerGeek82 That looks like a completely unrelated issue to me.

**Comment by CHBMB** [comment]
@ITestInProd Looks like that removes the two possibilities I suggested from the equation.  I'd suggest reporting this upstream then as at the moment I don't see how it's an issue with the image itself but could be a problem in calibre-web itself.

**Comment by ITestInProd** [comment]
Opened https://github.com/janeczku/calibre-web/issues/2062. A potentially similar issue was previously opened in https://github.com/janeczku/calibre-web/issues/1875 and the author referred reporter here (https://github.com/linuxserver/docker-calibre-web/issues/132; abandoned).

Closing in favor of working w/upstream again.
