### ISSUE TITLE
New SSL update in calibre-web breaks container

### ISSUE THREAD

**Issue by donicrosby** [linuxserver/docker-calibre-web#16]
The new update to the calibre-web that added ssl options breaks the containers because it's looking for certs and a key.
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

Debian 8 (Open Media Vault)

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
[s6-init] ensuring user provided files have correct perms...exited 0.,
[fix-attrs.d] applying ownership & permissions fixes...,
[fix-attrs.d] done.,
[cont-init.d] executing container initialization scripts...,
[cont-init.d] 10-adduser: executing... ,
,
-------------------------------------,
          _         (),
         | |  ___   _    __,
         | | / __| | |  /  \ ,
         | | \__ \ | | | () |,
         |_| |___/ |_|  \__/,
,
,
Brought to you by linuxserver.io,
We gratefully accept donations at:,
https://www.linuxserver.io/donations/,
-------------------------------------,
GID/UID,
-------------------------------------,
,
User uid:    1002,
User gid:    996,
-------------------------------------,
,
[cont-init.d] 10-adduser: exited 0.,
[cont-init.d] 30-config: executing... ,
[cont-init.d] 30-config: exited 0.,
[cont-init.d] done.,
[services.d] starting services,
[services.d] done.,
Traceback (most recent call last):,
  File "/usr/lib/python2.7/site-packages/gevent/greenlet.py", line 536, in run,
    result = self._run(*self.args, **self.kwargs),
  File "/usr/lib/python2.7/site-packages/gevent/baseserver.py", line 26, in _handle_and_close_when_done,
    return handle(*args_tuple),
  File "/usr/lib/python2.7/site-packages/gevent/server.py", line 173, in wrap_socket_and_handle,
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args),
  File "/usr/lib/python2.7/site-packages/gevent/_sslgte279.py", line 702, in wrap_socket,
    ciphers=ciphers),
  File "/usr/lib/python2.7/site-packages/gevent/_sslgte279.py", line 187, in __init__,
    raise ValueError("certfile must be specified for server-side ",
ValueError: certfile must be specified for server-side operations,
Fri Mar 30 18:37:17 2018 <Greenlet at 0x7fe684dfd7d0: _handle_and_close_when_done(<bound method WSGIServer.wrap_socket_and_handle of, <bound method WSGIServer.do_close of <WSGIServer a, (<socket at 0x7fe684b34b90 fileno=[Errno 9] Bad fi)> failed with ValueError,
,
Traceback (most recent call last):,
  File "/usr/lib/python2.7/site-packages/gevent/greenlet.py", line 536, in run,
    result = self._run(*self.args, **self.kwargs),
  File "/usr/lib/python2.7/site-packages/gevent/baseserver.py", line 26, in _handle_and_close_when_done,
    return handle(*args_tuple),
  File "/usr/lib/python2.7/site-packages/gevent/server.py", line 173, in wrap_socket_and_handle,
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args),
  File "/usr/lib/python2.7/site-packages/gevent/_sslgte279.py", line 702, in wrap_socket,
    ciphers=ciphers),
  File "/usr/lib/python2.7/site-packages/gevent/_sslgte279.py", line 187, in __init__,
    raise ValueError("certfile must be specified for server-side ",
ValueError: certfile must be specified for server-side operations,
Fri Mar 30 18:37:17 2018 <Greenlet at 0x7fe684dfd7d0: _handle_and_close_when_done(<bound method WSGIServer.wrap_socket_and_handle of, <bound method WSGIServer.do_close of <WSGIServer a, (<socket at 0x7fe684b34b90 fileno=[Errno 9] Bad fi)> failed with ValueError,
,
Traceback (most recent call last):,
  File "/usr/lib/python2.7/site-packages/gevent/greenlet.py", line 536, in run,
    result = self._run(*self.args, **self.kwargs),
  File "/usr/lib/python2.7/site-packages/gevent/baseserver.py", line 26, in _handle_and_close_when_done,
    return handle(*args_tuple),
  File "/usr/lib/python2.7/site-packages/gevent/server.py", line 173, in wrap_socket_and_handle,
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args),
  File "/usr/lib/python2.7/site-packages/gevent/_sslgte279.py", line 702, in wrap_socket,
    ciphers=ciphers),
  File "/usr/lib/python2.7/site-packages/gevent/_sslgte279.py", line 187, in __init__,
    raise ValueError("certfile must be specified for server-side ",
ValueError: certfile must be specified for server-side operations,
Fri Mar 30 18:37:19 2018 <Greenlet at 0x7fe684dfd7d0: _handle_and_close_when_done(<bound method WSGIServer.wrap_socket_and_handle of, <bound method WSGIServer.do_close of <WSGIServer a, (<socket at 0x7fe684b34b90 fileno=[Errno 9] Bad fi)> failed with ValueError,
,
Traceback (most recent call last):,
  File "/usr/lib/python2.7/site-packages/gevent/greenlet.py", line 536, in run,
    result = self._run(*self.args, **self.kwargs),
  File "/usr/lib/python2.7/site-packages/gevent/baseserver.py", line 26, in _handle_and_close_when_done,
    return handle(*args_tuple),
  File "/usr/lib/python2.7/site-packages/gevent/server.py", line 173, in wrap_socket_and_handle,
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args),
  File "/usr/lib/python2.7/site-packages/gevent/_sslgte279.py", line 702, in wrap_socket,
    ciphers=ciphers),
  File "/usr/lib/python2.7/site-packages/gevent/_sslgte279.py", line 187, in __init__,
    raise ValueError("certfile must be specified for server-side ",
ValueError: certfile must be specified for server-side operations,
Fri Mar 30 18:37:19 2018 <Greenlet at 0x7fe684dfd7d0: _handle_and_close_when_done(<bound method WSGIServer.wrap_socket_and_handle of, <bound method WSGIServer.do_close of <WSGIServer a, (<socket at 0x7fe684b34b90 fileno=[Errno 9] Bad fi)> failed with ValueError,
,
Traceback (most recent call last):,
  File "/usr/lib/python2.7/site-packages/gevent/greenlet.py", line 536, in run,
    result = self._run(*self.args, **self.kwargs),
  File "/usr/lib/python2.7/site-packages/gevent/baseserver.py", line 26, in _handle_and_close_when_done,
    return handle(*args_tuple),
  File "/usr/lib/python2.7/site-packages/gevent/server.py", line 173, in wrap_socket_and_handle,
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args),
  File "/usr/lib/python2.7/site-packages/gevent/_sslgte279.py", line 702, in wrap_socket,
    ciphers=ciphers),
  File "/usr/lib/python2.7/site-packages/gevent/_sslgte279.py", line 187, in __init__,
    raise ValueError("certfile must be specified for server-side ",
ValueError: certfile must be specified for server-side operations,
Fri Mar 30 18:42:07 2018 <Greenlet at 0x7fe684dfd7d0: _handle_and_close_when_done(<bound method WSGIServer.wrap_socket_and_handle of, <bound method WSGIServer.do_close of <WSGIServer a, (<socket at 0x7fe684b34b90 fileno=[Errno 9] Bad fi)> failed with ValueError,
,
Traceback (most recent call last):,
  File "/usr/lib/python2.7/site-packages/gevent/greenlet.py", line 536, in run,
    result = self._run(*self.args, **self.kwargs),
  File "/usr/lib/python2.7/site-packages/gevent/baseserver.py", line 26, in _handle_and_close_when_done,
    return handle(*args_tuple),
  File "/usr/lib/python2.7/site-packages/gevent/server.py", line 173, in wrap_socket_and_handle,
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args),
  File "/usr/lib/python2.7/site-packages/gevent/_sslgte279.py", line 702, in wrap_socket,
    ciphers=ciphers),
  File "/usr/lib/python2.7/site-packages/gevent/_sslgte279.py", line 187, in __init__,
    raise ValueError("certfile must be specified for server-side ",
ValueError: certfile must be specified for server-side operations,
Fri Mar 30 18:42:07 2018 <Greenlet at 0x7fe684dfd7d0: _handle_and_close_when_done(<bound method WSGIServer.wrap_socket_and_handle of, <bound method WSGIServer.do_close of <WSGIServer a, (<socket at 0x7fe684b34b90 fileno=[Errno 9] Bad fi)> failed with ValueError,
,
Traceback (most recent call last):,
  File "/usr/lib/python2.7/site-packages/gevent/greenlet.py", line 536, in run,
    result = self._run(*self.args, **self.kwargs),
  File "/usr/lib/python2.7/site-packages/gevent/baseserver.py", line 26, in _handle_and_close_when_done,
    return handle(*args_tuple),
  File "/usr/lib/python2.7/site-packages/gevent/server.py", line 173, in wrap_socket_and_handle,
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args),
  File "/usr/lib/python2.7/site-packages/gevent/_sslgte279.py", line 702, in wrap_socket,
    ciphers=ciphers),
  File "/usr/lib/python2.7/site-packages/gevent/_sslgte279.py", line 187, in __init__,
    raise ValueError("certfile must be specified for server-side ",
ValueError: certfile must be specified for server-side operations,
Fri Mar 30 18:47:52 2018 <Greenlet at 0x7fe684dfd7d0: _handle_and_close_when_done(<bound method WSGIServer.wrap_socket_and_handle of, <bound method WSGIServer.do_close of <WSGIServer a, (<socket at 0x7fe684b34b90 fileno=[Errno 9] Bad fi)> failed with ValueError,
,
[cont-finish.d] executing container finish scripts...,
[cont-finish.d] done.,
[s6-finish] syncing disks.,
[s6-finish] sending all processes the TERM signal.,
[s6-finish] sending all processes the KILL signal and exiting.,
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
[s6-init] ensuring user provided files have correct perms...exited 0.,
[fix-attrs.d] applying ownership & permissions fixes...,
[fix-attrs.d] done.,
[cont-init.d] executing container initialization scripts...,
[cont-init.d] 10-adduser: executing... ,
usermod: no changes,
,
-------------------------------------,
          _         (),
         | |  ___   _    __,
         | | / __| | |  /  \ ,
         | | \__ \ | | | () |,
         |_| |___/ |_|  \__/,
,
,
Brought to you by linuxserver.io,
We gratefully accept donations at:,
https://www.linuxserver.io/donations/,
-------------------------------------,
GID/UID,
-------------------------------------,
,
User uid:    1002,
User gid:    996,
-------------------------------------,
,
[cont-init.d] 10-adduser: exited 0.,
[cont-init.d] 30-config: executing... ,
[cont-init.d] 30-config: exited 0.,
[cont-init.d] done.,
[services.d] starting services,
[services.d] done.,
Traceback (most recent call last):,
  File "/usr/lib/python2.7/site-packages/gevent/greenlet.py", line 536, in run,
    result = self._run(*self.args, **self.kwargs),
  File "/usr/lib/python2.7/site-packages/gevent/baseserver.py", line 26, in _handle_and_close_when_done,
    return handle(*args_tuple),
  File "/usr/lib/python2.7/site-packages/gevent/server.py", line 173, in wrap_socket_and_handle,
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args),
  File "/usr/lib/python2.7/site-packages/gevent/_sslgte279.py", line 702, in wrap_socket,
    ciphers=ciphers),
  File "/usr/lib/python2.7/site-packages/gevent/_sslgte279.py", line 187, in __init__,
    raise ValueError("certfile must be specified for server-side ",
ValueError: certfile must be specified for server-side operations,
Fri Mar 30 18:55:34 2018 <Greenlet at 0x7efc648e87d0: _handle_and_close_when_done(<bound method WSGIServer.wrap_socket_and_handle of, <bound method WSGIServer.do_close of <WSGIServer a, (<socket at 0x7efc648b1e10 fileno=[Errno 9] Bad fi)> failed with ValueError,
,
Traceback (most recent call last):,
  File "/usr/lib/python2.7/site-packages/gevent/greenlet.py", line 536, in run,
    result = self._run(*self.args, **self.kwargs),
  File "/usr/lib/python2.7/site-packages/gevent/baseserver.py", line 26, in _handle_and_close_when_done,
    return handle(*args_tuple),
  File "/usr/lib/python2.7/site-packages/gevent/server.py", line 173, in wrap_socket_and_handle,
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args),
  File "/usr/lib/python2.7/site-packages/gevent/_sslgte279.py", line 702, in wrap_socket,
    ciphers=ciphers),
  File "/usr/lib/python2.7/site-packages/gevent/_sslgte279.py", line 187, in __init__,
    raise ValueError("certfile must be specified for server-side ",
ValueError: certfile must be specified for server-side operations,
Fri Mar 30 18:55:35 2018 <Greenlet at 0x7efc648e87d0: _handle_and_close_when_done(<bound method WSGIServer.wrap_socket_and_handle of, <bound method WSGIServer.do_close of <WSGIServer a, (<socket at 0x7efc648b1e10 fileno=[Errno 9] Bad fi)> failed with ValueError,
,
[cont-finish.d] executing container finish scripts...,
[cont-finish.d] done.,
[s6-finish] syncing disks.,
[s6-finish] sending all processes the TERM signal.,
[s6-finish] sending all processes the KILL signal and exiting.,
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
[s6-init] ensuring user provided files have correct perms...exited 0.,
[fix-attrs.d] applying ownership & permissions fixes...,
[fix-attrs.d] done.,
[cont-init.d] executing container initialization scripts...,
[cont-init.d] 10-adduser: executing... ,
usermod: no changes,
,
-------------------------------------,
          _         (),
         | |  ___   _    __,
         | | / __| | |  /  \ ,
         | | \__ \ | | | () |,
         |_| |___/ |_|  \__/,
,
,
Brought to you by linuxserver.io,
We gratefully accept donations at:,
https://www.linuxserver.io/donations/,
-------------------------------------,
GID/UID,
-------------------------------------,
,
User uid:    1002,
User gid:    996,
-------------------------------------,
,
[cont-init.d] 10-adduser: exited 0.,
[cont-init.d] 30-config: executing... ,
[cont-init.d] 30-config: exited 0.,
[cont-init.d] done.,
[services.d] starting services,
[services.d] done.,
Traceback (most recent call last):,
  File "/usr/lib/python2.7/site-packages/gevent/greenlet.py", line 536, in run,
    result = self._run(*self.args, **self.kwargs),
  File "/usr/lib/python2.7/site-packages/gevent/baseserver.py", line 26, in _handle_and_close_when_done,
    return handle(*args_tuple),
  File "/usr/lib/python2.7/site-packages/gevent/server.py", line 173, in wrap_socket_and_handle,
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args),
  File "/usr/lib/python2.7/site-packages/gevent/_sslgte279.py", line 702, in wrap_socket,
    ciphers=ciphers),
  File "/usr/lib/python2.7/site-packages/gevent/_sslgte279.py", line 187, in __init__,
    raise ValueError("certfile must be specified for server-side ",
ValueError: certfile must be specified for server-side operations,
Fri Mar 30 19:07:21 2018 <Greenlet at 0x7fc6365927d0: _handle_and_close_when_done(<bound method WSGIServer.wrap_socket_and_handle of, <bound method WSGIServer.do_close of <WSGIServer a, (<socket at 0x7fc63655be10 fileno=[Errno 9] Bad fi)> failed with ValueError,
,

**Comment by kendokan** [comment]
Experiencing the same. Is there a workaround?

**Comment by donicrosby** [comment]
Revert to release 51 is what I did.

**Comment by OzzieIsaacs** [comment]
I have found the problem, I think it‘s fixed in calibre-web now

**Comment by sparklyballs** [comment]
i have triggered a rebuild of our image in light of @OzzieIsaacs fix

**Comment by kendokan** [comment]
Confirmed working after pull, thank you both!

**Comment by sparklyballs** [comment]
in that case i'll close this
