### ISSUE TITLE
FakeUserAgentError

### ISSUE THREAD

**Issue by xmu714** [linuxserver/docker-calibre-web#162]
------------------------------

## Environment
**OS:** ProxMox
**CPU architecture:** x86_64
**How docker service was installed:** from dockerhub, update via watchtower

## Command used to create docker container (run/create/compose/screenshot)

![image](https://user-images.githubusercontent.com/25820665/135373745-d71ddfef-9b01-416d-b484-e439a6ab1044.png)

## Docker logs

```
During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/app/calibre-web/cps.py", line 39, in <module>

    from cps.about import about

  File "/app/calibre-web/cps/about.py", line 58, in <module>

    from scholarly import scholarly

  File "/usr/local/lib/python3.8/dist-packages/scholarly/__init__.py", line 4, in <module>

    scholarly = _Scholarly()

  File "/usr/local/lib/python3.8/dist-packages/scholarly/_scholarly.py", line 27, in __init__

    self.__nav = Navigator()

  File "/usr/local/lib/python3.8/dist-packages/scholarly/_navigator.py", line 45, in __call__

    cls._instances[cls] = super(Singleton, cls).__call__(*args,

  File "/usr/local/lib/python3.8/dist-packages/scholarly/_navigator.py", line 59, in __init__

    self.pm = ProxyGenerator()

  File "/usr/local/lib/python3.8/dist-packages/scholarly/_proxy_generator.py", line 54, in __init__

    self._new_session()

  File "/usr/local/lib/python3.8/dist-packages/scholarly/_proxy_generator.py", line 368, in _new_session

    'User-Agent': UserAgent().random,

  File "/usr/local/lib/python3.8/dist-packages/fake_useragent/fake.py", line 69, in __init__

    self.load()

  File "/usr/local/lib/python3.8/dist-packages/fake_useragent/fake.py", line 75, in load

    self.data = load_cached(

  File "/usr/local/lib/python3.8/dist-packages/fake_useragent/utils.py", line 250, in load_cached

    update(path, use_cache_server=use_cache_server, verify_ssl=verify_ssl)

  File "/usr/local/lib/python3.8/dist-packages/fake_useragent/utils.py", line 245, in update

    write(path, load(use_cache_server=use_cache_server, verify_ssl=verify_ssl))

  File "/usr/local/lib/python3.8/dist-packages/fake_useragent/utils.py", line 187, in load

    ret = json.loads(get(

  File "/usr/local/lib/python3.8/dist-packages/fake_useragent/utils.py", line 84, in get

    raise FakeUserAgentError('Maximum amount of retries reached')

fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached
```

**Comment by fabiopovoledo** [comment]
same problem here

**Comment by j0nnymoe** [comment]
No one has provided information on how to replicate this is. Until we get provided the information that's requested in the issue template, it's hard to try and find the fix.

**Comment by fabiopovoledo** [comment]
Sorry, not a developer here, not sure what the correct procedure should be. I installed the docker container following the instructions on https://hub.docker.com/r/linuxserver/calibre-web, using docker-compose (without optional rows).
The container starts without issues but the web interface is not accessible on localhost:8183 (connection denied).
Can post the logs if needed (same as above)

thanks

**Comment by j0nnymoe** [comment]
could you post the full container logs including our startup messages please?

**Comment by fabiopovoledo** [comment]
Sure, see below:

2021-11-02T10:34:30.542107132Z [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
2021-11-02T10:34:30.595659562Z [s6-init] ensuring user provided files have correct perms...exited 0.
2021-11-02T10:34:30.596675242Z [fix-attrs.d] applying ownership & permissions fixes...
2021-11-02T10:34:30.597382596Z [fix-attrs.d] done.
2021-11-02T10:34:30.598038478Z [cont-init.d] executing container initialization scripts...
2021-11-02T10:34:30.599087134Z [cont-init.d] 01-envfile: executing...
2021-11-02T10:34:30.604013352Z [cont-init.d] 01-envfile: exited 0.
2021-11-02T10:34:30.605210763Z [cont-init.d] 10-adduser: executing...
2021-11-02T10:34:31.070742565Z
2021-11-02T10:34:31.070780431Z -------------------------------------
2021-11-02T10:34:31.070787124Z           _         ()
2021-11-02T10:34:31.070793259Z          | |  ___   _    __
2021-11-02T10:34:31.070799510Z          | | / __| | |  /  \
2021-11-02T10:34:31.070806032Z          | | \__ \ | | | () |
2021-11-02T10:34:31.070810744Z          |_| |___/ |_|  \__/
2021-11-02T10:34:31.070815139Z
2021-11-02T10:34:31.070819161Z
2021-11-02T10:34:31.070823139Z Brought to you by linuxserver.io
2021-11-02T10:34:31.070827257Z -------------------------------------
2021-11-02T10:34:31.070831401Z
2021-11-02T10:34:31.070835379Z To support LSIO projects visit:
2021-11-02T10:34:31.070839461Z https://www.linuxserver.io/donate/
2021-11-02T10:34:31.070843542Z -------------------------------------
2021-11-02T10:34:31.070847683Z GID/UID
2021-11-02T10:34:31.070851739Z -------------------------------------
2021-11-02T10:34:31.075050173Z
2021-11-02T10:34:31.075079892Z User uid:    1000
2021-11-02T10:34:31.075084698Z User gid:    1000
2021-11-02T10:34:31.075088642Z -------------------------------------
2021-11-02T10:34:31.075092562Z
2021-11-02T10:34:31.079810390Z [cont-init.d] 10-adduser: exited 0.
2021-11-02T10:34:31.081609969Z [cont-init.d] 30-config: executing...
2021-11-02T10:34:32.612637130Z [cont-init.d] 30-config: exited 0.
2021-11-02T10:34:32.615763901Z [cont-init.d] 90-custom-folders: executing...
2021-11-02T10:34:32.627146844Z [cont-init.d] 90-custom-folders: exited 0.
2021-11-02T10:34:32.628086883Z [cont-init.d] 99-custom-scripts: executing...
2021-11-02T10:34:32.640773033Z [custom-init] no custom files found exiting...
2021-11-02T10:34:32.641415686Z [cont-init.d] 99-custom-scripts: exited 0.
2021-11-02T10:34:32.644365014Z [cont-init.d] done.
2021-11-02T10:34:32.645257006Z [services.d] starting services
2021-11-02T10:34:32.653569203Z [services.d] done.
2021-11-02T10:35:15.455757133Z Traceback (most recent call last):
2021-11-02T10:35:15.455802133Z   File "/usr/lib/python3.8/urllib/request.py", line 1354, in do_open
2021-11-02T10:35:15.455809369Z     h.request(req.get_method(), req.selector, req.data, headers,
2021-11-02T10:35:15.455814405Z   File "/usr/lib/python3.8/http/client.py", line 1252, in request
2021-11-02T10:35:15.455819392Z     self._send_request(method, url, body, headers, encode_chunked)
2021-11-02T10:35:15.455824259Z   File "/usr/lib/python3.8/http/client.py", line 1298, in _send_request
2021-11-02T10:35:15.455829238Z     self.endheaders(body, encode_chunked=encode_chunked)
2021-11-02T10:35:15.455834029Z   File "/usr/lib/python3.8/http/client.py", line 1247, in endheaders
2021-11-02T10:35:15.455839012Z     self._send_output(message_body, encode_chunked=encode_chunked)
2021-11-02T10:35:15.455843854Z   File "/usr/lib/python3.8/http/client.py", line 1007, in _send_output
2021-11-02T10:35:15.455848775Z     self.send(msg)
2021-11-02T10:35:15.455853436Z   File "/usr/lib/python3.8/http/client.py", line 947, in send
2021-11-02T10:35:15.455858312Z     self.connect()
2021-11-02T10:35:15.455862976Z   File "/usr/lib/python3.8/http/client.py", line 1414, in connect
2021-11-02T10:35:15.455867842Z     super().connect()
2021-11-02T10:35:15.455872509Z   File "/usr/lib/python3.8/http/client.py", line 918, in connect
2021-11-02T10:35:15.455877415Z     self.sock = self._create_connection(
2021-11-02T10:35:15.455882159Z   File "/usr/lib/python3.8/socket.py", line 787, in create_connection
2021-11-02T10:35:15.455887063Z     for res in getaddrinfo(host, port, 0, SOCK_STREAM):
2021-11-02T10:35:15.455891871Z   File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
2021-11-02T10:35:15.455896760Z     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
2021-11-02T10:35:15.455901642Z socket.gaierror: [Errno -3] Temporary failure in name resolution
2021-11-02T10:35:15.455906455Z
2021-11-02T10:35:15.455911038Z During handling of the above exception, another exception occurred:
2021-11-02T10:35:15.455915804Z
2021-11-02T10:35:15.455920295Z Traceback (most recent call last):
2021-11-02T10:35:15.455924970Z   File "/usr/local/lib/python3.8/dist-packages/fake_useragent/utils.py", line 64, in get
2021-11-02T10:35:15.455929880Z     with contextlib.closing(urlopen(
2021-11-02T10:35:15.455934603Z   File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
2021-11-02T10:35:15.455939483Z     return opener.open(url, data, timeout)
2021-11-02T10:35:15.455944192Z   File "/usr/lib/python3.8/urllib/request.py", line 525, in open
2021-11-02T10:35:15.455948985Z     response = self._open(req, data)
2021-11-02T10:35:15.455953694Z   File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
2021-11-02T10:35:15.455969675Z     result = self._call_chain(self.handle_open, protocol, protocol +
2021-11-02T10:35:15.455974814Z   File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
2021-11-02T10:35:15.455979348Z     result = func(*args)
2021-11-02T10:35:15.455983673Z   File "/usr/lib/python3.8/urllib/request.py", line 1397, in https_open
2021-11-02T10:35:15.455991802Z     return self.do_open(http.client.HTTPSConnection, req,
2021-11-02T10:35:15.455997993Z   File "/usr/lib/python3.8/urllib/request.py", line 1357, in do_open
2021-11-02T10:35:15.456004148Z     raise URLError(err)
2021-11-02T10:35:15.456010800Z urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>
2021-11-02T10:35:15.456016563Z
2021-11-02T10:35:15.456020790Z During handling of the above exception, another exception occurred:
2021-11-02T10:35:15.456025222Z
2021-11-02T10:35:15.456029341Z Traceback (most recent call last):
2021-11-02T10:35:15.456033616Z   File "/usr/local/lib/python3.8/dist-packages/fake_useragent/utils.py", line 154, in load
2021-11-02T10:35:15.456038121Z     for item in get_browsers(verify_ssl=verify_ssl):
2021-11-02T10:35:15.456042881Z   File "/usr/local/lib/python3.8/dist-packages/fake_useragent/utils.py", line 97, in get_browsers
2021-11-02T10:35:15.456047523Z     html = get(settings.BROWSERS_STATS_PAGE, verify_ssl=verify_ssl)
2021-11-02T10:35:15.456051954Z   File "/usr/local/lib/python3.8/dist-packages/fake_useragent/utils.py", line 84, in get
2021-11-02T10:35:15.456056524Z     raise FakeUserAgentError('Maximum amount of retries reached')
2021-11-02T10:35:15.456060924Z fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached
2021-11-02T10:35:15.456065330Z
2021-11-02T10:35:15.456069451Z During handling of the above exception, another exception occurred:
2021-11-02T10:35:15.456073841Z
2021-11-02T10:35:15.456077988Z Traceback (most recent call last):
2021-11-02T10:35:15.456082271Z   File "/usr/lib/python3.8/urllib/request.py", line 1354, in do_open
2021-11-02T10:35:15.456086706Z     h.request(req.get_method(), req.selector, req.data, headers,
2021-11-02T10:35:15.456091117Z   File "/usr/lib/python3.8/http/client.py", line 1252, in request
2021-11-02T10:35:15.456095568Z     self._send_request(method, url, body, headers, encode_chunked)
2021-11-02T10:35:15.456099976Z   File "/usr/lib/python3.8/http/client.py", line 1298, in _send_request
2021-11-02T10:35:15.456104467Z     self.endheaders(body, encode_chunked=encode_chunked)
2021-11-02T10:35:15.456108806Z   File "/usr/lib/python3.8/http/client.py", line 1247, in endheaders
2021-11-02T10:35:15.456113241Z     self._send_output(message_body, encode_chunked=encode_chunked)
2021-11-02T10:35:15.456117636Z   File "/usr/lib/python3.8/http/client.py", line 1007, in _send_output
2021-11-02T10:35:15.456126783Z     self.send(msg)
2021-11-02T10:35:15.456131595Z   File "/usr/lib/python3.8/http/client.py", line 947, in send
2021-11-02T10:35:15.456136145Z     self.connect()
2021-11-02T10:35:15.456140347Z   File "/usr/lib/python3.8/http/client.py", line 1414, in connect
2021-11-02T10:35:15.456144760Z     super().connect()
2021-11-02T10:35:15.456149018Z   File "/usr/lib/python3.8/http/client.py", line 918, in connect
2021-11-02T10:35:15.456153487Z     self.sock = self._create_connection(
2021-11-02T10:35:15.456157811Z   File "/usr/lib/python3.8/socket.py", line 787, in create_connection
2021-11-02T10:35:15.456162276Z     for res in getaddrinfo(host, port, 0, SOCK_STREAM):
2021-11-02T10:35:15.456166635Z   File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
2021-11-02T10:35:15.456171703Z     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
2021-11-02T10:35:15.456176305Z socket.gaierror: [Errno -3] Temporary failure in name resolution
2021-11-02T10:35:15.456180592Z
2021-11-02T10:35:15.456184615Z During handling of the above exception, another exception occurred:
2021-11-02T10:35:15.456188879Z
2021-11-02T10:35:15.456192884Z Traceback (most recent call last):
2021-11-02T10:35:15.456197077Z   File "/usr/local/lib/python3.8/dist-packages/fake_useragent/utils.py", line 64, in get
2021-11-02T10:35:15.456201553Z     with contextlib.closing(urlopen(
2021-11-02T10:35:15.456205771Z   File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
2021-11-02T10:35:15.456210174Z     return opener.open(url, data, timeout)
2021-11-02T10:35:15.456214402Z   File "/usr/lib/python3.8/urllib/request.py", line 525, in open
2021-11-02T10:35:15.456218802Z     response = self._open(req, data)
2021-11-02T10:35:15.456222996Z   File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
2021-11-02T10:35:15.456227388Z     result = self._call_chain(self.handle_open, protocol, protocol +
2021-11-02T10:35:15.456231778Z   File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
2021-11-02T10:35:15.456236194Z     result = func(*args)
2021-11-02T10:35:15.456240353Z   File "/usr/lib/python3.8/urllib/request.py", line 1397, in https_open
2021-11-02T10:35:15.456244752Z     return self.do_open(http.client.HTTPSConnection, req,
2021-11-02T10:35:15.456249037Z   File "/usr/lib/python3.8/urllib/request.py", line 1357, in do_open
2021-11-02T10:35:15.456253410Z     raise URLError(err)
2021-11-02T10:35:15.456257585Z urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>
2021-11-02T10:35:15.456262077Z
2021-11-02T10:35:15.456266108Z During handling of the above exception, another exception occurred:
2021-11-02T10:35:15.456274138Z
2021-11-02T10:35:15.456278656Z Traceback (most recent call last):
2021-11-02T10:35:15.456282943Z   File "/app/calibre-web/cps.py", line 34, in <module>
2021-11-02T10:35:15.456287501Z     from cps.about import about
2021-11-02T10:35:15.456291722Z   File "/app/calibre-web/cps/about.py", line 61, in <module>
2021-11-02T10:35:15.456296265Z     from scholarly import scholarly
2021-11-02T10:35:15.456300627Z   File "/usr/local/lib/python3.8/dist-packages/scholarly/__init__.py", line 4, in <module>
2021-11-02T10:35:15.456305243Z     scholarly = _Scholarly()
2021-11-02T10:35:15.456309439Z   File "/usr/local/lib/python3.8/dist-packages/scholarly/_scholarly.py", line 27, in __init__
2021-11-02T10:35:15.456313980Z     self.__nav = Navigator()
2021-11-02T10:35:15.456318176Z   File "/usr/local/lib/python3.8/dist-packages/scholarly/_navigator.py", line 45, in __call__
2021-11-02T10:35:15.456322737Z     cls._instances[cls] = super(Singleton, cls).__call__(*args,
2021-11-02T10:35:15.456327057Z   File "/usr/local/lib/python3.8/dist-packages/scholarly/_navigator.py", line 59, in __init__
2021-11-02T10:35:15.456331564Z     self.pm = ProxyGenerator()
2021-11-02T10:35:15.456335776Z   File "/usr/local/lib/python3.8/dist-packages/scholarly/_proxy_generator.py", line 54, in __init__
2021-11-02T10:35:15.456340876Z     self._new_session()
2021-11-02T10:35:15.456345280Z   File "/usr/local/lib/python3.8/dist-packages/scholarly/_proxy_generator.py", line 368, in _new_session
2021-11-02T10:35:15.456349843Z     'User-Agent': UserAgent().random,
2021-11-02T10:35:15.456354037Z   File "/usr/local/lib/python3.8/dist-packages/fake_useragent/fake.py", line 69, in __init__
2021-11-02T10:35:15.456358516Z     self.load()
2021-11-02T10:35:15.456362598Z   File "/usr/local/lib/python3.8/dist-packages/fake_useragent/fake.py", line 75, in load
2021-11-02T10:35:15.456367056Z     self.data = load_cached(
2021-11-02T10:35:15.456371139Z   File "/usr/local/lib/python3.8/dist-packages/fake_useragent/utils.py", line 250, in load_cached
2021-11-02T10:35:15.456375638Z     update(path, use_cache_server=use_cache_server, verify_ssl=verify_ssl)
2021-11-02T10:35:15.456379972Z   File "/usr/local/lib/python3.8/dist-packages/fake_useragent/utils.py", line 245, in update
2021-11-02T10:35:15.456384419Z     write(path, load(use_cache_server=use_cache_server, verify_ssl=verify_ssl))
2021-11-02T10:35:15.456388758Z   File "/usr/local/lib/python3.8/dist-packages/fake_useragent/utils.py", line 187, in load
2021-11-02T10:35:15.456393195Z     ret = json.loads(get(
2021-11-02T10:35:15.456397279Z   File "/usr/local/lib/python3.8/dist-packages/fake_useragent/utils.py", line 84, in get
2021-11-02T10:35:15.456401732Z     raise FakeUserAgentError('Maximum amount of retries reached')
2021-11-02T10:35:15.456405971Z fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached

**Comment by j0nnymoe** [comment]
ok perfect thank you - I'll do some digging.

**Comment by j0nnymoe** [comment]
Could you post your compose as well please?

**Comment by fabiopovoledo** [comment]
---
version: "2.1"
services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - /media/Adam/libri:/config
      - /media/Adam/libri:/books
    ports:
      - 8083:8083
    restart: unless-stopped

**Comment by j0nnymoe** [comment]
ok, could you test something please? do `/home/username/calibre-web:/config` and see if that works? leave the `/books` one.

**Comment by fabiopovoledo** [comment]
substituting "username" with my own username? Such directory does not exist...

**Comment by fabiopovoledo** [comment]
setting "/home/username/calibre-web:/config" the web interface is now accessible

**Comment by fabiopovoledo** [comment]
no errors in logs

**Comment by j0nnymoe** [comment]
ok so, it could be a couple things, but I suspect it's due to the permissions on the folder you were setting for `/config` and the application didn't like it. I would keep your config for containers in your home directory. You were also using the same directory for both mounts which can cause issues.

**Comment by fabiopovoledo** [comment]
Thank you so much, I moved the config to another folder and now it works flawlessy. The strange thing is that I was having the previous configuration on another docker image (technosoft) and it worked fine till the last debian update.

**Comment by Kratosak** [comment]
I have the same issue but when I tried move folders as suggested it did not work.
Details:
OS/docker info (Linux raspberrypi 5.10.63-v7l+ , Docker 20.10)
Hardware: raspberry pi 4 8GB
Docker command or compose snippet: docker run -d –name=Calibre-Web -e PUID=1000 -e PGID=1000 -e TZ=Europe/Bratislava -p 1083:8083 -v /home/pi/DockVols/Calibre-web/config:/config -v /home/pi/DockVols/Syncthing/Media_files/CalibreDatabase/:/books –restart unless-stopped linuxserver/calibre-web
Container logs: https://pastebin.com/j4rgwkz9
Describe the issue you’re having with the container: Cannot open webUI. I checked logs via portainer or Dozzle and I see many errors like this: https://pastebin.com/j4rgwkz9

**Comment by j0nnymoe** [comment]
@Kratosak your issue is that the container is unable to access the internet 
`today at 11:16:58 PM socket.gaierror: [Errno -3] Temporary failure in name resolution`

**Comment by xmu714** [comment]
I finally solved this problem by upgrading docker, without changing any configuration.

**Comment by najibmq** [comment]
I have the same issue, any solution other than changing config folder or updating docker?

**Comment by drizuid** [comment]
> I have the same issue, any solution other than changing config folder or updating docker?

fixing the permissions issue would resolve the issue. Closing this as the OP failed to provide relevant info. if you still have this issue, please fill the template out fully in a NEW issue. NOTE: we do not support or recommend deployment of our containers using portainer.

**Comment by andreas-vester** [comment]
> fixing the permissions issue would resolve the issue.

I am facing exactly the same issue. And it doesn't matter if I bind the volumes to my user folder. So I am wondering how I can ``fix the permission issue``?
