### ISSUE TITLE
Converting AZW3 to EPUB doesnt work anymore

### ISSUE THREAD

**Issue by Dinth** [linuxserver/docker-calibre-web#172]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Queued book conversion should be successful. This functionality used to work fine just a few months ago, but not anymore
## Current Behavior
When i request Calibre-web to convert an AZW3 book to EPUB im getting the following error:
```
[2021-12-11 06:33:34,963]  INFO {cps.editbooks:1080} converting: book id: 1053 from: AZW3 to: EPUB
[2021-12-11 06:33:34,981] DEBUG {cps.services.worker:88} Add Task for user: admin: <cps.tasks.convert.TaskConvert object at 0x7f9e1dfe01f0>
[2021-12-11 06:33:34,998]  INFO {cps.tasks.convert:125} Book id 1053 - target format of .epub does not exist. Moving forward with convert.
[2021-12-11 06:33:35,660] DEBUG {cps.tasks.convert:225} No write access to /root/.config/calibre using a temporary dir instead
[2021-12-11 06:33:35,808] DEBUG {cps.tasks.convert:225} 1% Converting input to HTML...
[2021-12-11 06:33:35,809] DEBUG {cps.tasks.convert:225} InputFormatPlugin: MOBI Input running
[2021-12-11 06:33:35,809] DEBUG {cps.tasks.convert:225} on /books/!Calibre/William Gibson/The Difference Engine (1053)/The Difference Engine - William Gibson.azw3
[2021-12-11 06:33:35,905] DEBUG {cps.tasks.convert:225} Found KF8 MOBI of type 'standalone'
[2021-12-11 06:33:36,139] DEBUG {cps.tasks.convert:225} 
[2021-12-11 06:33:36,139] DEBUG {cps.tasks.convert:238} Traceback (most recent call last):
[2021-12-11 06:33:36,140] DEBUG {cps.tasks.convert:238}   File "runpy.py", line 194, in _run_module_as_main
[2021-12-11 06:33:36,140] DEBUG {cps.tasks.convert:238}   File "runpy.py", line 87, in _run_code
[2021-12-11 06:33:36,140] DEBUG {cps.tasks.convert:238}   File "site.py", line 45, in <module>
[2021-12-11 06:33:36,140] DEBUG {cps.tasks.convert:238}   File "site.py", line 41, in main
[2021-12-11 06:33:36,140] DEBUG {cps.tasks.convert:238}   File "calibre/ebooks/conversion/cli.py", line 419, in main
[2021-12-11 06:33:36,140] DEBUG {cps.tasks.convert:238}   File "calibre/ebooks/conversion/plumber.py", line 1111, in run
[2021-12-11 06:33:36,141] DEBUG {cps.tasks.convert:238}   File "calibre/customize/conversion.py", line 244, in __call__
[2021-12-11 06:33:36,141] DEBUG {cps.tasks.convert:238}   File "calibre/ebooks/conversion/plugins/mobi_input.py", line 44, in convert
[2021-12-11 06:33:36,141] DEBUG {cps.tasks.convert:238}   File "calibre/ebooks/mobi/reader/mobi8.py", line 86, in __call__
[2021-12-11 06:33:36,141] DEBUG {cps.tasks.convert:238}   File "calibre/ebooks/mobi/reader/mobi6.py", line 163, in check_for_drm
[2021-12-11 06:33:36,142] DEBUG {cps.tasks.convert:238} calibre.ebooks.DRMError: The Difference Engine (S.F. MASTERWORKS)
[2021-12-11 06:33:36,143]  INFO {cps.tasks.convert:164} ebook converter failed with error while converting book
[2021-12-11 06:33:51,000] DEBUG {cps.updater:332} Stable version: {'version': '0.6.14'}
```

## Steps to Reproduce

1. Add an AZW3 book to calibre-web (it might be downloaded from Amazon)
2. Try to convert it to EPUB
3. The conversion fails almost instantly.

## Environment
**OS:** Debian
**CPU architecture:** x86_64
**How docker service was installed:** From the distro repo

## Command used to create docker container (run/create/compose/screenshot)

Used portainer

## Docker logs
```
Get:1 http://archive.ubuntu.com/ubuntu focal/main amd64 libxdamage1 amd64 1:1.1.5-2 [6,996 B]
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76, <> line 1.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7, <> line 1.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: 
Fetched 6,996 B in 0s (158 kB/s)
Selecting previously unselected package libxdamage1:amd64.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 12188 files and directories currently installed.)
Preparing to unpack .../libxdamage1_1%3a1.1.5-2_amd64.deb ...
Unpacking libxdamage1:amd64 (1:1.1.5-2) ...
Setting up libxdamage1:amd64 (1:1.1.5-2) ...
Processing triggers for libc-bin (2.31-0ubuntu9.2) ...
[cont-init.d] 98-calibre: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[mod-init] Attempting to run Docker Modification Logic
[mod-init] Applying linuxserver/calibre-web:calibre files to container
[mod-init] linuxserver/calibre-web:calibre at sha256:39da6738908d6b9f908452984309c3dd05abc0ff1df77dbc85cbf9cf7bdf1e54 has been previously applied skipping
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 01-migrations: executing... 
[migrations] started
[migrations] no migrations found
[cont-init.d] 01-migrations: exited 0.
[cont-init.d] 10-adduser: executing... 
usermod: no changes
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
-------------------------------------
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1003
User gid:    100
------------------------------------
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 95-apt-get: executing... 
Hit:1 http://archive.ubuntu.com/ubuntu focal InRelease
Get:2 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Get:3 http://archive.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Get:4 http://archive.ubuntu.com/ubuntu focal-updates/main Sources [567 kB]
Get:5 http://archive.ubuntu.com/ubuntu focal-updates/universe Sources [260 kB]
Get:6 http://archive.ubuntu.com/ubuntu focal-updates/restricted Sources [34.6 kB]
Get:7 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [1,747 kB]
Get:8 http://archive.ubuntu.com/ubuntu focal-updates/restricted amd64 Packages [786 kB]
Get:9 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [1,104 kB]
Get:10 http://archive.ubuntu.com/ubuntu focal-security/universe Sources [96.0 kB]
Get:11 http://archive.ubuntu.com/ubuntu focal-security/main Sources [237 kB]
Get:12 http://archive.ubuntu.com/ubuntu focal-security/universe amd64 Packages [825 kB]
Get:13 http://archive.ubuntu.com/ubuntu focal-security/main amd64 Packages [1,329 kB]
Fetched 7,213 kB in 3s (2,512 kB/s)
Reading package lists...
[cont-init.d] 95-apt-get: exited 0.
[cont-init.d] 98-calibre: executing... 
Reading package lists...
Building dependency tree...
Reading state information...
libxdamage1 is already the newest version (1:1.1.5-2).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
[cont-init.d] 98-calibre: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

```

**Comment by Roxedus** [comment]
This sounds like a issue for the upstream project, if this turns out to not be the case, feel free to comment so we can reopen the issue.
