### ISSUE TITLE
Python modul 'advocate' is not installed but is needed for cover downloads

### ISSUE THREAD

**Issue by Jerome2103** [linuxserver/docker-calibre-web#185]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Python modul 'advocate' is not installed but is needed for cover downloads

------------------------------
## Expected Behavior
Download the cover

## Current Behavior
Error

## Steps to Reproduce

1. go to book
2. paste a url into cover field
3. error

## Environment
OS: Linux 4.4.59+ #25556 SMP PREEMPT Sat Aug 28 02:17:26 CST 2021 x86_64 x86_64
Python: 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
Calibre-Web: 0.6.18 - fee76741a02899d2dfdc2ce29cfc27901a06383c - 2022-04-03T20:17:34+02:00

## Command used to create docker container (run/create/compose/screenshot)
Synology Docker

## Docker logs

[2022-04-03 21:13:06,447] ERROR {cps.search_metadata:61} Import error for metadata source: lubimyczytac - No module named 'html2text'
[2022-04-03 21:13:07,176]  INFO {cps:133} *** "advocate" version does not fit the requirements. Should: available, Found: Not available, please consider installing required version ***
[2022-04-03 21:13:07,177]  INFO {cps:141} Starting Calibre Web...

**Comment by aptalca** [comment]
We install all of their required and optional python packages: https://github.com/linuxserver/docker-calibre-web/blob/master/Dockerfile#L47-L49

**Comment by Jerome2103** [comment]
But I reloaded the image and it still doesn't work.

**Comment by pixous69** [comment]
I've the same problem.

I've also executed pip freeze getting the following error:

pi@pi4:~ $ docker exec -it calibre-web bash
root@733531fb6c7a:/# cd
root@733531fb6c7a:~# pip freeze
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 5, in <module>
    from pip._internal.cli.main import main
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/cli/main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/cli/main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/cli/cmdoptions.py", line 23, in <module>
    from pip._internal.cli.parser import ConfigOptionParser
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/cli/parser.py", line 12, in <module>
    from pip._internal.configuration import Configuration, ConfigurationError
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/configuration.py", line 26, in <module>
    from pip._internal.utils.logging import getLogger
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/utils/logging.py", line 27, in <module>
    from pip._internal.utils.misc import ensure_dir
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/utils/misc.py", line 39, in <module>
    from pip._internal.locations import get_major_minor_version
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/locations/__init__.py", line 14, in <module>
    from . import _distutils, _sysconfig
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/locations/_distutils.py", line 9, in <module>
    from distutils.cmd import Command as DistutilsCommand
ModuleNotFoundError: No module named 'distutils.cmd'


docker inspect -f '{{ index .Config.Labels "build_version" }}' calibre-web
Linuxserver.io version:- 0.6.18-ls156 Build-date:- 2022-04-03T22:16:46+02:00

docker inspect -f '{{ index .Config.Labels "build_version" }}' lscr.io/linuxserver/calibre-web
Linuxserver.io version:- 0.6.18-ls156 Build-date:- 2022-04-03T22:16:46+02:00

docker is running on raspberry OS 64 bin.

**Comment by aptalca** [comment]
What I meant above is, if there is a necessary module missing, it should be reported to the upstream project so they can add it to their requirements.txt file and our image will install it.
