### ISSUE TITLE
Errors when starting the container

### ISSUE THREAD

**Issue by JVT038** [linuxserver/docker-calibre-web#188]
I expected the container to launch without any errors

## Current Behavior
There are various errors that happen.
The first one is:
```
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76, <> line 3.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7, <> line 3.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
```
I don't know what this means, but it doesn't look right.
Later, it says:
```
Setting up command-line completion...
Installing zsh completion to: /usr/share/zsh/vendor-completions/_calibre
Failed to find directory to install bash completions, using default.
Installing bash completion to: /usr/share/bash-completion/completions/

____________________ WARNING ____________________
Setting up completion failed with error:
__________________________________________________


        Traceback (most recent call last):
          File "calibre/linux.py", line 831, in setup_completion
          File "calibre/linux.py", line 573, in write_completion
          File "bypy-importer.py", line 279, in exec_module
          File "calibre/gui2/__init__.py", line 12, in <module>
        ImportError: cannot import name 'QApplication' from 'qt.core' (/app/calibre/lib/calibre-extensions/python-lib.bypy.frozen/qt/core.pyc)

Setting up desktop integration...

____________________ WARNING ____________________
Setting up desktop integration failed with error:
__________________________________________________


Failed to import PyQt module: PyQt5.QtWidgets with error: libGL.so.1: cannot open shared object file: No such file or directory
Failed to import PyQt module: PyQt5.QtGui with error: libGL.so.1: cannot open shared object file: No such file or directory
        Traceback (most recent call last):
          File "calibre/linux.py", line 852, in setup_desktop_integration
          File "calibre/linux.py", line 874, in do_setup_desktop_integration
          File "calibre/linux.py", line 905, in install_xdg_junk
          File "calibre/linux.py", line 890, in install_icons
          File "calibre/linux.py", line 880, in install_single_icon
          File "calibre/linux.py", line 1301, in render_img
        ImportError: cannot import name 'QImage' from 'qt.core' (/app/calibre/lib/calibre-extensions/python-lib.bypy.frozen/qt/core.pyc)

Creating un-installer: /usr/bin/calibre-uninstall


There were 2 warnings

* Setting up completion failed with error:

* Setting up desktop integration failed with error
```
And last, but not least, it says:
```
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76, <> line 1.)
Fetched 6,996 B in 0s (32.9 kB/s)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7, <> line 1.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
```
Another error was this, but I don't think it's related to Linuxserver.io
```python
Traceback (most recent call last):
  File "/app/calibre-web/cps.py", line 40, in <module>
    from cps.search_metadata import meta
  File "/app/calibre-web/cps/search_metadata.py", line 58, in <module>
    importlib.import_module("cps.metadata_provider." + a)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/app/calibre-web/cps/metadata_provider/amazon.py", line 116
    except Exception as e:
    ^
IndentationError: unexpected unindent
```

## Environment
**OS: Diskstation Manager 7**
**CPU architecture:** x86_64
**How docker service was installed: From the Synology Package Center**

## Command used to create docker container (run/create/compose/screenshot)
```docker
  calibre-web:
    image: ghcr.io/linuxserver/calibre-web:nightly
    container_name: calibre-web
    networks: 
      - nginx
    environment:
      - PUID=0
      - PGID=0
      - TZ=$TZ
      - DOCKER_MODS=linuxserver/calibre-web:calibre|ghcr.io/gilbn/theme.park:calibreweb
    volumes:
      - $DOCKERDIR/calibre/webui:/config
      - $DOCKERDIR/calibre/webui/gmail.json:/app/calibre-web/gmail.json
      - $MEDIADIR/ebooks:/data
    ports:
      - 8083:80
    restart: unless-stopped
```
The comment I used was just `docker-compose up -d`, nothing really specal.

**Comment by tobbenb** [comment]
Use something else than root for PUID and PGID. That might be the issue.

**Comment by JVT038** [comment]
It didn't fix the issue, but I think it doesn't really matter, because calibre-web works just fine, with these errors.
I was just wondering where they come from
