### ISSUE TITLE
ERROR 500 after modifications

### ISSUE THREAD

**Issue by bilyboy785** [linuxserver/docker-calibre-web#19]
I've got an error 500 after getting metadata of books, or after upload a new book.

See logs below  : 
```[2018-05-31 15:51:28,475] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/calibre-web/cps/web.py", line 393, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/app/calibre-web/cps/web.py", line 1095, in index
    entries, random, pagination = fill_indexpage(page, db.Books, True, db.Books.timestamp.desc())
  File "/app/calibre-web/cps/web.py", line 543, in fill_indexpage
    .filter(db_filter).filter(common_filters()).all()))
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2773, in all
    return list(self)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2925, in __iter__
    return self._execute_and_instances(context)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2946, in _execute_and_instances
    close_with_result=True)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2955, in _get_bind_args
    **kw
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2937, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1035, in connection
    execution_options=execution_options)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1040, in _connection_for_bind
    engine, execution_options)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 388, in _connection_for_bind
    self._assert_active()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 276, in _assert_active
    % self._rollback_exception
InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (sqlite3.OperationalError) attempt to write a readonly database [SQL: u'UPDATE books SET title=? WHERE books.id = ?'] [parameters: (u'Que serais-je sans toi ?', 29)] (Background on this error at: http://sqlalche.me/e/e3q8)
::ffff:172.18.0.4 - - 
[2018-05-31 15:51:28] "GET / HTTP/1.1" 500 412 0.006725```

**Comment by j0nnymoe** [comment]
As you are getting the webui up and this is crashing when you have changed settings, please report this issue directly to the calibre-web github and they should be able to point out why it's not working. If it is indeed an issue with our container, please re-open the issue.
