### ISSUE TITLE
Calibre-Web failing to start after internal update

### ISSUE THREAD

**Issue by magenbrot** [linuxserver/docker-calibre-web#196]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

After updating calibre-web in the admin area to the latest version it won't start again. I think the python version in the base image is too old or there's a new missing dependency.

------------------------------

## Expected Behavior

Calibre-Web starts.

## Current Behavior

The app is failing with this message:
```
[services.d] starting services
[services.d] done.
Traceback (most recent call last):
  File "/app/calibre-web/cps.py", line 40, in <module>
    from cps.search_metadata import meta
  File "/app/calibre-web/cps/search_metadata.py", line 34, in <module>
    from cps.services.Metadata import Metadata
  File "/app/calibre-web/cps/services/Metadata.py", line 19, in <module>
    import dataclasses
ModuleNotFoundError: No module named 'dataclasses'
```

## Steps to Reproduce

1. Update via Admin-GUI to the latest calibre-web version
2. Restart the container

## Environment
**OS:** Synology DSM 7.1 
**CPU architecture:** x86_64
**How docker service was installed:**

Docker is from Synology Package Center

## Docker logs

```
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    0
User gid:    0
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Traceback (most recent call last):
  File "/app/calibre-web/cps.py", line 40, in <module>
    from cps.search_metadata import meta
  File "/app/calibre-web/cps/search_metadata.py", line 34, in <module>
    from cps.services.Metadata import Metadata
  File "/app/calibre-web/cps/services/Metadata.py", line 19, in <module>
    import dataclasses
ModuleNotFoundError: No module named 'dataclasses'
```

**Comment by magenbrot** [comment]
Yeah, thank you. That's what I tried next and it's running again.
