### ISSUE TITLE
Calibre-Web Docker Container is not reachable : 

### ISSUE THREAD

**Issue by DennisYildirim** [linuxserver/docker-calibre-web#206]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Steps to Reproduce

1. Deploy Docker Container via portainer stack
 and see it yourself. 

version: "2.1"
services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    network_mode: host
    environment:
      # for GroupID
      - PUID=${PUID:-1026}
      # for UserID
      - PGID=${PGID:-100}
      # Specify a timezone to use for example Europe/Amsterdam
      - TZ=${TZ:-Melbourne/Australia}
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - ${BASEDIR:-/volume1/docker}/calibre-web/config:/config
      # Books library location
      - ${BASEDIR:-/volume1/docker}/calibre/library:/ssdbooks #optional
    ports:
      - 8084:8083
    restart: unless-stopped

## Environment
OS: Synology DS1821+

**How docker service was installed:**
Via Poratiner Stack: 

## Docker logs
Portainer Log: 
s6-rc: info: service init-mods-package-install successfully started
s6-rc: info: service init-mods-end: starting
s6-rc: info: service init-mods-end successfully started
s6-rc: info: service init-services: starting
s6-rc: info: service init-services successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun calibre-web (no readiness notification)
s6-rc: info: service legacy-services successfully started
s6-rc: info: service 99-ci-service-check: starting
s6-rc: info: service 99-ci-service-check successfully started
	Symlinking /app/calibre/lrs2lrf to /usr/bin/lrs2lrf
	Symlinking /app/calibre/calibre-debug to /usr/bin/calibre-debug
	Symlinking /app/calibre/calibredb to /usr/bin/calibredb
	Symlinking /app/calibre/calibre-parallel to /usr/bin/calibre-parallel
	Symlinking /app/calibre/calibre-customize to /usr/bin/calibre-customize
	Symlinking /app/calibre/fetch-ebook-metadata to /usr/bin/fetch-ebook-metadata
	Symlinking /app/calibre/calibre-smtp to /usr/bin/calibre-smtp
	Symlinking /app/calibre/calibre to /usr/bin/calibre
	Symlinking /app/calibre/lrfviewer to /usr/bin/lrfviewer
	Symlinking /app/calibre/ebook-viewer to /usr/bin/ebook-viewer
	Symlinking /app/calibre/ebook-edit to /usr/bin/ebook-edit
Setting up command-line completion...
Installing zsh completion to: /usr/share/zsh/vendor-completions/_calibre
Failed to find directory to install bash completions, using default.
Installing bash completion to: /usr/share/bash-completion/completions/

____________________ WARNING ____________________
Setting up completion failed with error:
__________________________________________________

	Traceback (most recent call last):
	  File "calibre/linux.py", line 831, in setup_completion
	  File "calibre/linux.py", line 574, in write_completion
	  File "bypy-importer.py", line 279, in exec_module
	  File "calibre/gui2/viewer/main.py", line 15, in <module>
	  File "bypy-importer.py", line 279, in exec_module
	  File "calibre/gui2/viewer/ui.py", line 29, in <module>
	  File "bypy-importer.py", line 279, in exec_module
	  File "calibre/gui2/viewer/annotations.py", line 13, in <module>
	  File "bypy-importer.py", line 279, in exec_module
	  File "calibre/gui2/viewer/web_view.py", line 14, in <module>
	ImportError: cannot import name 'QWebEnginePage' from 'qt.webengine' (/app/calibre/lib/calibre-extensions/python-lib.bypy.frozen/qt/webengine.pyc)

Setting up desktop integration...

____________________ WARNING ____________________
Setting up desktop integration failed with error:
__________________________________________________

	Traceback (most recent call last):
	  File "calibre/linux.py", line 852, in setup_desktop_integration
	  File "calibre/linux.py", line 874, in do_setup_desktop_integration
	  File "calibre/linux.py", line 905, in install_xdg_junk
	  File "calibre/linux.py", line 890, in install_icons
	  File "calibre/linux.py", line 884, in install_single_icon
	  File "subprocess.py", line 364, in check_call
	  File "subprocess.py", line 345, in call
	  File "subprocess.py", line 966, in __init__
	  File "subprocess.py", line 1842, in _execute_child
	FileNotFoundError: [Errno 2] No such file or directory: 'xdg-icon-resource'

Creating un-installer: /usr/bin/calibre-uninstall

There were 2 warnings

* Setting up completion failed with error:

* Setting up desktop integration failed with error:

[custom-init] no custom files found exiting...
[ls.io-init] done.
Traceback (most recent call last):
  File "/app/calibre-web/cps.py", line 31, in <module>
    main()
  File "/app/calibre-web/cps/main.py", line 26, in main
    app = create_app()
  File "/app/calibre-web/cps/__init__.py", line 173, in create_app
    register_scheduled_tasks(config.schedule_reconnect)
  File "/app/calibre-web/cps/schedule.py", line 55, in register_scheduled_tasks
    scheduler = BackgroundScheduler()
  File "/app/calibre-web/cps/services/background_scheduler.py", line 43, in __new__
    cls.scheduler = BScheduler()
  File "/usr/local/lib/python3.8/dist-packages/apscheduler/schedulers/base.py", line 87, in __init__
    self.configure(gconfig, **options)
  File "/usr/local/lib/python3.8/dist-packages/apscheduler/schedulers/base.py", line 131, in configure
    self._configure(config)
  File "/usr/local/lib/python3.8/dist-packages/apscheduler/schedulers/background.py", line 29, in _configure
    super(BackgroundScheduler, self)._configure(config)
  File "/usr/local/lib/python3.8/dist-packages/apscheduler/schedulers/base.py", line 701, in _configure
    self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
  File "/usr/local/lib/python3.8/dist-packages/tzlocal/unix.py", line 203, in get_localzone
    _cache_tz = _get_localzone()
  File "/usr/local/lib/python3.8/dist-packages/tzlocal/unix.py", line 161, in _get_localzone
    tzenv = utils._tz_from_env()
  File "/usr/local/lib/python3.8/dist-packages/tzlocal/utils.py", line 125, in _tz_from_env
    raise ZoneInfoNotFoundError(
tzlocal.utils.ZoneInfoNotFoundError: 'tzlocal() does not support non-zoneinfo timezones like %s. \nPlease use a timezone in the form of Continent/City'

**Comment by Roxedus** [comment]
Melbourne/Australia Is not a valid timezone, see list.
https://en.m.wikipedia.org/wiki/List_of_tz_database_time_zones

**Comment by DennisYildirim** [comment]
Sorry, No, I changed the timezone to Australia/Melbourne, still does not work.

**Comment by DennisYildirim** [comment]
> 

Now it works!!!!!!!

It looks like it needed sometime to unpack and update itself after the timezone settings!!!!! 

Thanks heaps ! We can close the tread @Roxedus  you're a legend!
