### ISSUE TITLE
s6-rc: fatal: unable to take locks: No such file or directory

### ISSUE THREAD

**Issue by Isilorn** [linuxserver/docker-calibre-web#216]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Calibre-web doesn't start

## Current Behavior
Calibre-web container doesn't start, it exits with the following error : 
`[custom-init] No custom services found, skipping...`
`[mod-init] Attempting to run Docker Modification Logic`
`[mod-init] Applying linuxserver/mods:universal-calibre files to container`
`s6-rc: fatal: unable to take locks: No such file or directory`

## Steps to Reproduce
1. Removed all preexisting configuration
2. Removed preexisting image
3. Recreated the container from the docker-compose file

## Environment
**OS:** Ubuntu 20.04.5 LTS
**CPU architecture:** x86_64
**How docker service was installed:**
From official Docker CE repo

## Command used to create docker container (run/create/compose/screenshot)
Docker compose file :

version: "3"
services:
  calibre:
    image: lscr.io/linuxserver/calibre-web:latest
    networks:
      - DockerNet
    container_name: Calibre
    env_file: ../Common/common.env
    environment:
      - DOCKER_MODS=linuxserver/mods:universal-calibre
    volumes:
      - /home/docker/Calibre/config:/config
      - /volume1/calibre:/volume1/calibre
    ports:
      - 8083:8083
    dns:
       - 192.168.42.244
       - 9.9.9.9
    restart: always
    healthcheck:
      test: curl --fail -s http://localhost:8083/ || exit 1
      interval: 1min
      timeout: 10s
      retries: 3
    labels:
      - autoheal=true

networks:
  DockerNet:
    external: true

## Docker logs
[custom-init] No custom services found, skipping...
[mod-init] Attempting to run Docker Modification Logic
[mod-init] Applying linuxserver/mods:universal-calibre files to container
s6-rc: fatal: unable to take locks: No such file or directory

**Comment by thespad** [comment]
Please can you set an environment variable of `S6_VERBOSITY=2`, run through again, and post the logs?

Does it start up correctly without the calibre mod?

**Comment by Isilorn** [comment]
With S6_VERBOSITY=2

[mod-init] Version 3
[custom-init] No custom services found, skipping...
[mod-init] Attempting to run Docker Modification Logic
[mod-init] Applying linuxserver/mods:universal-calibre files to container
s6-rc: fatal: unable to take locks: No such file or directory
s6-linux-init-shutdownd: warning: /run/s6/basedir/scripts/rc.shutdown exited 111

Without the Calibre mod :

mod-init] Version 3
[custom-init] No custom services found, skipping...
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service 00-legacy: starting
s6-rc: info: service 00-legacy successfully started
s6-rc: info: service init-script-check: starting
s6-rc: info: service init-migrations: starting
s6-rc: info: service init-envfile: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
[migrations] started
[migrations] no migrations found
s6-rc: info: service init-migrations successfully started
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-script-check successfully started
s6-rc: info: service init-adduser: starting
s6-rc: info: service init-envfile successfully started

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1026
User gid:    65539
-------------------------------------

s6-rc: info: service init-adduser successfully started
s6-rc: info: service init-os-end: starting
s6-rc: info: service init-os-end successfully started
s6-rc: info: service init-config: starting
s6-rc: info: service init-config successfully started
s6-rc: info: service init-calibre-web-config: starting
s6-rc: info: service init-calibre-web-config successfully started
s6-rc: info: service init-config-end: starting
s6-rc: info: service init-config-end successfully started
s6-rc: info: service init-mods: starting
s6-rc: info: service init-mods successfully started
s6-rc: info: service init-mods-package-install: starting
s6-rc: info: service init-mods-package-install successfully started
s6-rc: info: service init-mods-end: starting
s6-rc: info: service init-mods-end successfully started
s6-rc: info: service init-custom-files: starting
[custom-init] No custom files found, skipping...
s6-rc: info: service init-custom-files successfully started
s6-rc: info: service init-services: starting
s6-rc: info: service init-services successfully started
s6-rc: info: service svc-calibre-web: starting
Traceback (most recent call last):
  File "/app/calibre-web/cps.py", line 31, in <module>
    main()
  File "/app/calibre-web/cps/main.py", line 26, in main
    app = create_app()
  File "/app/calibre-web/cps/__init__.py", line 124, in create_app
    updater_thread.start()
  File "/usr/lib/python3.10/threading.py", line 935, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Traceback (most recent call last):
  File "/app/calibre-web/cps.py", line 31, in <module>
    main()
  File "/app/calibre-web/cps/main.py", line 26, in main
    app = create_app()
  File "/app/calibre-web/cps/__init__.py", line 124, in create_app
    updater_thread.start()
  File "/usr/lib/python3.10/threading.py", line 935, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Traceback (most recent call last):
  File "/app/calibre-web/cps.py", line 31, in <module>
    main()
  File "/app/calibre-web/cps/main.py", line 26, in main
    app = create_app()
  File "/app/calibre-web/cps/__init__.py", line 124, in create_app
    updater_thread.start()
  File "/usr/lib/python3.10/threading.py", line 935, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Traceback (most recent call last):
  File "/app/calibre-web/cps.py", line 31, in <module>
    main()
  File "/app/calibre-web/cps/main.py", line 26, in main
    app = create_app()
  File "/app/calibre-web/cps/__init__.py", line 124, in create_app
    updater_thread.start()
  File "/usr/lib/python3.10/threading.py", line 935, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Traceback (most recent call last):
  File "/app/calibre-web/cps.py", line 31, in <module>
    main()
  File "/app/calibre-web/cps/main.py", line 26, in main
    app = create_app()
  File "/app/calibre-web/cps/__init__.py", line 124, in create_app
    updater_thread.start()
  File "/usr/lib/python3.10/threading.py", line 935, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Traceback (most recent call last):
  File "/app/calibre-web/cps.py", line 31, in <module>
    main()
  File "/app/calibre-web/cps/main.py", line 26, in main
    app = create_app()
  File "/app/calibre-web/cps/__init__.py", line 124, in create_app
    updater_thread.start()
  File "/usr/lib/python3.10/threading.py", line 935, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Traceback (most recent call last):
  File "/app/calibre-web/cps.py", line 31, in <module>
    main()
  File "/app/calibre-web/cps/main.py", line 26, in main
    app = create_app()
  File "/app/calibre-web/cps/__init__.py", line 124, in create_app
    updater_thread.start()
  File "/usr/lib/python3.10/threading.py", line 935, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Traceback (most recent call last):
  File "/app/calibre-web/cps.py", line 31, in <module>
    main()
  File "/app/calibre-web/cps/main.py", line 26, in main
    app = create_app()
  File "/app/calibre-web/cps/__init__.py", line 124, in create_app
    updater_thread.start()
  File "/usr/lib/python3.10/threading.py", line 935, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Traceback (most recent call last):
  File "/app/calibre-web/cps.py", line 31, in <module>
    main()
  File "/app/calibre-web/cps/main.py", line 26, in main
    app = create_app()
  File "/app/calibre-web/cps/__init__.py", line 124, in create_app
    updater_thread.start()
  File "/usr/lib/python3.10/threading.py", line 935, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Traceback (most recent call last):
  File "/app/calibre-web/cps.py", line 31, in <module>
    main()
  File "/app/calibre-web/cps/main.py", line 26, in main
    app = create_app()
  File "/app/calibre-web/cps/__init__.py", line 124, in create_app
    updater_thread.start()
  File "/usr/lib/python3.10/threading.py", line 935, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Traceback (most recent call last):
  File "/app/calibre-web/cps.py", line 31, in <module>
    main()
  File "/app/calibre-web/cps/main.py", line 26, in main
    app = create_app()
  File "/app/calibre-web/cps/__init__.py", line 124, in create_app
    updater_thread.start()
  File "/usr/lib/python3.10/threading.py", line 935, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Traceback (most recent call last):
  File "/app/calibre-web/cps.py", line 31, in <module>
    main()
  File "/app/calibre-web/cps/main.py", line 26, in main
    app = create_app()
  File "/app/calibre-web/cps/__init__.py", line 124, in create_app
    updater_thread.start()
  File "/usr/lib/python3.10/threading.py", line 935, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Traceback (most recent call last):
  File "/app/calibre-web/cps.py", line 31, in <module>
    main()
  File "/app/calibre-web/cps/main.py", line 26, in main
    app = create_app()
  File "/app/calibre-web/cps/__init__.py", line 124, in create_app
    updater_thread.start()
  File "/usr/lib/python3.10/threading.py", line 935, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Traceback (most recent call last):
  File "/app/calibre-web/cps.py", line 31, in <module>
    main()
  File "/app/calibre-web/cps/main.py", line 26, in main
    app = create_app()
  File "/app/calibre-web/cps/__init__.py", line 124, in create_app
    updater_thread.start()
  File "/usr/lib/python3.10/threading.py", line 935, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread

**Comment by thespad** [comment]
Can you try running with
```yaml
    security_opt:
      - seccomp=unconfined
```
Also what's the output of `docker version`?

**Comment by Isilorn** [comment]
Docker version :

Client: Docker Engine - Community
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:18:05 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:16:00 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

Tried with the security_opt, it works (both without and with module)

**Comment by thespad** [comment]
You need to update your docker install to at least `20.10.10` - although you may still get issues without the `seccomp=unconfined` if you're on an older kernel.

**Comment by Isilorn** [comment]
Ok, I'll check on how to upgrade my 20.04 LTS and my docker install without breaking everything. At least in the meanwhile it works
