### ISSUE TITLE
[BUG] Can not start the container

### ISSUE THREAD

**Issue by free521521521** [linuxserver/docker-calibre-web#226]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The image from Dorker hub on Synology can not run correctly.

### Steps To Reproduce

Install as the tutorals.

### Environment

```markdown
- OS:
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
Install as the tutorals.
```

### Container logs

```bash
Traceback (most recent call last):

File "/usr/local/lib/python3.8/dist-packages/fake_useragent/utils.py", line 154, in load

for item in get_browsers(verify_ssl=verify_ssl):

File "/usr/local/lib/python3.8/dist-packages/fake_useragent/utils.py", line 99, in get_browsers

html = html.split('<table class="w3-table-all notranslate">')[1]

IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/usr/lib/python3.8/urllib/request.py", line 1354, in do_open

h.request(req.get_method(), req.selector, req.data, headers,

File "/usr/lib/python3.8/http/client.py", line 1256, in request

self._send_request(method, url, body, headers, encode_chunked)

File "/usr/lib/python3.8/http/client.py", line 1302, in _send_request

self.endheaders(body, encode_chunked=encode_chunked)

File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders

self._send_output(message_body, encode_chunked=encode_chunked)

File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output

self.send(msg)

File "/usr/lib/python3.8/http/client.py", line 951, in send

self.connect()

File "/usr/lib/python3.8/http/client.py", line 1418, in connect

super().connect()

File "/usr/lib/python3.8/http/client.py", line 922, in connect

self.sock = self._create_connection(

File "/usr/lib/python3.8/socket.py", line 808, in create_connection

raise err

File "/usr/lib/python3.8/socket.py", line 796, in create_connection

sock.connect(sa)

OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/usr/local/lib/python3.8/dist-packages/fake_useragent/utils.py", line 64, in get

with contextlib.closing(urlopen(

File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
```

**Comment by sinslish** [comment]
i have the same problem:

2022-12-23T20:39:26.101309511Z Traceback (most recent call last):

2022-12-23T20:39:26.101850820Z   File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect

2022-12-23T20:39:26.103110765Z     return fn()

2022-12-23T20:39:26.103311846Z   File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/base.py", line 325, in connect

2022-12-23T20:39:26.103486288Z     return _ConnectionFairy._checkout(self)

2022-12-23T20:39:26.103557980Z   File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/base.py", line 888, in _checkout

2022-12-23T20:39:26.103833845Z     fairy = _ConnectionRecord.checkout(pool)

2022-12-23T20:39:26.104019191Z   File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/base.py", line 491, in checkout

2022-12-23T20:39:26.104434567Z     rec = pool._do_get()

2022-12-23T20:39:26.104584143Z   File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/impl.py", line 256, in _do_get

2022-12-23T20:39:26.104726441Z     return self._create_connection()

2022-12-23T20:39:26.104860730Z   File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/base.py", line 271, in _create_connection

2022-12-23T20:39:26.105131822Z     return _ConnectionRecord(self)

2022-12-23T20:39:26.105215987Z   File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/base.py", line 386, in __init__

2022-12-23T20:39:26.105475240Z     self.__connect()

2022-12-23T20:39:26.105604208Z   File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/base.py", line 684, in __connect

2022-12-23T20:39:26.106020304Z     with util.safe_reraise():

2022-12-23T20:39:26.106117425Z   File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__

2022-12-23T20:39:26.106217538Z     compat.raise_(

2022-12-23T20:39:26.106282964Z   File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/util/compat.py", line 211, in raise_

2022-12-23T20:39:26.106734065Z     raise exception

2022-12-23T20:39:26.106878680Z   File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/base.py", line 680, in __connect

2022-12-23T20:39:26.106949015Z     self.dbapi_connection = connection = pool._invoke_creator(self)

2022-12-23T20:39:26.106994478Z   File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/create.py", line 578, in connect

2022-12-23T20:39:26.107414055Z     return dialect.connect(*cargs, **cparams)

2022-12-23T20:39:26.107539619Z   File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/default.py", line 598, in connect

2022-12-23T20:39:26.107811284Z     return self.dbapi.connect(*cargs, **cparams)

2022-12-23T20:39:26.108096109Z sqlite3.OperationalError: unable to open database file

2022-12-23T20:39:26.108194122Z 

2022-12-23T20:39:26.108242146Z The above exception was the direct cause of the following exception:

2022-12-23T20:39:26.108319552Z 

2022-12-23T20:39:26.108355311Z Traceback (most recent call last):

2022-12-23T20:39:26.108409202Z   File "/app/calibre-web/cps.py", line 31, in <module>

2022-12-23T20:39:26.108702210Z     main()

2022-12-23T20:39:26.109075565Z   File "/app/calibre-web/cps/main.py", line 26, in main

2022-12-23T20:39:26.109416819Z     app = create_app()

2022-12-23T20:39:26.109658928Z   File "/app/calibre-web/cps/__init__.py", line 110, in create_app

2022-12-23T20:39:26.109954021Z     ub.init_db(cli_param.settings_path, cli_param.user_credentials)

2022-12-23T20:39:26.110303401Z   File "/app/calibre-web/cps/ub.py", line 836, in init_db

2022-12-23T20:39:26.110822541Z     Base.metadata.create_all(engine)

2022-12-23T20:39:26.111075202Z   File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/sql/schema.py", line 4930, in create_all

2022-12-23T20:39:26.113023284Z     bind._run_ddl_visitor(

2022-12-23T20:39:26.113295513Z   File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 3227, in _run_ddl_visitor

2022-12-23T20:39:26.114654895Z     with self.begin() as conn:

2022-12-23T20:39:26.114923128Z   File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 3143, in begin

2022-12-23T20:39:26.116143175Z     conn = self.connect(close_with_result=close_with_result)

2022-12-23T20:39:26.116444258Z   File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 3315, in connect

2022-12-23T20:39:26.118122873Z     return self._connection_cls(self, close_with_result=close_with_result)

2022-12-23T20:39:26.118429250Z   File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 96, in __init__

2022-12-23T20:39:26.118905950Z     else engine.raw_connection()

2022-12-23T20:39:26.119239590Z   File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 3394, in raw_connection

2022-12-23T20:39:26.120609727Z     return self._wrap_pool_connect(self.pool.connect, _connection)

2022-12-23T20:39:26.120986477Z   File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 3364, in _wrap_pool_connect

2022-12-23T20:39:26.122377333Z     Connection._handle_dbapi_exception_noconnection(

2022-12-23T20:39:26.122697664Z   File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 2198, in _handle_dbapi_exception_noconnection

2022-12-23T20:39:26.123886628Z     util.raise_(

2022-12-23T20:39:26.124249317Z   File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/util/compat.py", line 211, in raise_

2022-12-23T20:39:26.124681496Z     raise exception

2022-12-23T20:39:26.124932394Z   File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect

2022-12-23T20:39:26.126243030Z     return fn()

2022-12-23T20:39:26.126635903Z   File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/base.py", line 325, in connect

2022-12-23T20:39:26.127304878Z     return _ConnectionFairy._checkout(self)

2022-12-23T20:39:26.127724557Z   File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/base.py", line 888, in _checkout

2022-12-23T20:39:26.128253472Z     fairy = _ConnectionRecord.checkout(pool)

2022-12-23T20:39:26.128556511Z   File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/base.py", line 491, in checkout

2022-12-23T20:39:26.129089143Z     rec = pool._do_get()

2022-12-23T20:39:26.129376787Z   File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/impl.py", line 256, in _do_get

2022-12-23T20:39:26.129697478Z     return self._create_connection()

2022-12-23T20:39:26.130051701Z   File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/base.py", line 271, in _create_connection

2022-12-23T20:39:26.130452620Z     return _ConnectionRecord(self)

2022-12-23T20:39:26.130696436Z   File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/base.py", line 386, in __init__

2022-12-23T20:39:26.131182252Z     self.__connect()

2022-12-23T20:39:26.131474502Z   File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/base.py", line 684, in __connect

2022-12-23T20:39:26.131913711Z     with util.safe_reraise():

2022-12-23T20:39:26.132289320Z   File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__

2022-12-23T20:39:26.132639251Z     compat.raise_(

2022-12-23T20:39:26.133070734Z   File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/util/compat.py", line 211, in raise_

2022-12-23T20:39:26.133626271Z     raise exception

2022-12-23T20:39:26.133888683Z   File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/base.py", line 680, in __connect

2022-12-23T20:39:26.134345308Z     self.dbapi_connection = connection = pool._invoke_creator(self)

2022-12-23T20:39:26.135122147Z   File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/create.py", line 578, in connect

2022-12-23T20:39:26.135654099Z     return dialect.connect(*cargs, **cparams)

2022-12-23T20:39:26.136062338Z   File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/default.py", line 598, in connect

2022-12-23T20:39:26.136781822Z     return self.dbapi.connect(*cargs, **cparams)

2022-12-23T20:39:26.137725785Z sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file

2022-12-23T20:39:26.137839788Z (Background on this error at: https://sqlalche.me/e/14/e3q8)

**Comment by drizuid** [comment]
thanks for opening an issue. Please keep in mind for the future that the template has no optional fields (unless specified as optional) meaning, you need to fill it all out.

1) we have no tutorial and following unofficial guidance is bad
2) we do not support or recommend using the synology docker ui to install our containers, it's very broken
3) you could try (using docker run or docker compose) to add
**Compose**
```
    security_opt:
      - seccomp:unconfined
```
**docker run**
`--security-opt seccomp=unconfined`

and see if this helps

**Comment by j0nnymoe** [comment]
Closing as no update in 2 weeks.
