### ISSUE TITLE
[BUG] <Cover image does not show up in meta, and "You are not allowed to access localhost or the local network for cover uploads" >

### ISSUE THREAD

**Issue by free521521521** [linuxserver/docker-calibre-web#233]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have installed the Calibre-web 0.6.19.
When I fetch the metadata, all the cover image do not show up in the search result.
https://prnt.sc/DNn1CuK_ZOqE
or sometimes it show "Search error!!"
https://prnt.sc/uUuXYIzPfhOl
I inspected the page there is a error may be the key issue:
Failed to load resource: the server responded with a status of 500 ()

When I update the metadata, there is a red banner show:
"You are not allowed to access localhost or the local network for cover uploads"

### Steps To Reproduce

1. install Calibre-web from Synology Docker
2. login and uplod a book
3. search the metadata of this book
4. See error for the cover
5. save the metadata
6. error"You are not allowed to access localhost or the local network for cover uploads"

### Environment

```markdown
- OS:DMS7.1
- How docker service was installed: Docker container
```

### CPU architecture

x86-64

### Docker creation

```bash
I install the docker by UI step by step.
```

### Container logs

```bash
F Library Search
Search Library
 Advanced Search
 Tasks
 Admin
 FREEZhao
 Logout
BROWSE
 Books
 Hot Books
 Downloaded Books
 Top Rated Books
 Read Books
 Unread Books
 Discover
 Categories
 Series
 Authors
 Publishers
 Languages
 Ratings
 File formats
 Archived Books
 Books List
SHELVES
Create a Shelf
 About
 Show Calibre-Web Log:/app/calibre-web/calibre-web.log
[2023-01-06 16:49:24,926]  INFO {cps:143} *** "APScheduler" version does not fit the requirements. Should: available, Found: Not available, please consider installing required version ***
[2023-01-06 16:49:24,927]  INFO {cps:143} *** "PyPDF2" version does not fit the requirements. Should: available, Found: Not available, please consider installing required version ***
[2023-01-06 16:49:24,927]  INFO {cps:143} *** "greenlet" version does not fit the requirements. Should: available, Found: Not available, please consider installing required version ***
[2023-01-06 16:49:24,927]  INFO {cps:152} Starting Calibre Web...
[2023-01-06 16:49:26,557]  INFO {apscheduler.scheduler:171} Scheduler started
[2023-01-06 16:49:26,874]  WARN {py.warnings:109} /usr/local/lib/python3.10/dist-packages/apscheduler/util.py:436: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return tzinfo.localize(dt)
[2023-01-06 16:49:26,875]  INFO {apscheduler.scheduler:885} Added job "end scheduled task" to job store "default"
[2023-01-06 16:49:28,686]  INFO {cps.server:205} Starting Gevent server on [::]:8083
[2023-01-06 16:50:07,060]  WARN {cps.metadata_provider.douban:113} 403 Client Error: Forbidden for url: https://sec.douban.com/b?r=https%3A%2F%2Fwww.douban.com%2Fsearch%3Fcat%3D1001%26q%3D%25E7%2586%258A%25E8%25B0%25B7%25E6%2599%2583%25E5%2595%2586%25E4%25B8%259A%25E9%259D%2599%25E7%2589%25A9%25E6%2591%2584%25E5%25BD%25B1%25E5%25B8%2583%25E5%2585%2589%25E4%25B8%258E%25E5%25B8%2583%25E6%2599%25AF
[2023-01-06 16:50:07,061]  INFO {scholarly:95} Getting https://scholar.google.com/scholar?hl=en&q=%25E7%2586%258A%25E8%25B0%25B7%25E6%2599%2583%25E5%2595%2586%25E4%25B8%259A%25E9%259D%2599%25E7%2589%25A9%25E6%2591%2584%25E5%25BD%25B1%25E5%25B8%2583%25E5%2585%2589%25E4%25B8%258E%25E5%25B8%2583%25E6%2599%25AF&as_vis=0&as_sdt=0,33
[2023-01-06 16:50:07,199] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 16:50:07,200] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 16:50:07,200] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 16:50:07,200] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 16:50:07,200] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 16:50:07,200] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 16:50:08,863]  WARN {cps.metadata_provider.amazon:65} 404 Client Error: Not Found for url: https://www.amazon.com/https://www.amazon.com/ap/signin?openid.return_to=https%3A%2F%2Fwww.amazon.com%2Fs%3Fk%3D%25E7%2586%258A%25E8%25B0%25B7%25E6%2599%2583%25E5%2595%2586%25E4%25B8%259A%25E9%259D%2599%25E7%2589%25A9%25E6%2591%2584%25E5%25BD%25B1%25E5%25B8%2583%25E5%2585%2589%25E4%25B8%258E%25E5%25B8%2583%25E6%2599%25AF%26i%3Ddigital-text%26sprefix%3D%25E7%2586%258A%25E8%25B0%25B7%25E6%2599%2583%25E5%2595%2586%25E4%25B8%259A%25E9%259D%2599%25E7%2589%25A9%25E6%2591%2584%25E5%25BD%25B1%25E5%25B8%2583%25E5%2585%2589%25E4%25B8%258E%25E5%25B8%2583%25E6%2599%25AF%252Cdigital-text%26ref%3Dnb_sb_noss&marketPlaceId=ATVPDKIKX0DER&openid.assoc_handle=usflex&openid.mode=checkid_setup&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select
[2023-01-06 16:50:48,375]  WARN {cps.metadata_provider.douban:113} 403 Client Error: Forbidden for url: https://sec.douban.com/b?r=https%3A%2F%2Fwww.douban.com%2Fsearch%3Fcat%3D1001%26q%3D%25E7%2586%258A%25E8%25B0%25B7%25E6%2599%2583
[2023-01-06 16:50:48,376]  INFO {scholarly:95} Getting https://scholar.google.com/scholar?hl=en&q=%25E7%2586%258A%25E8%25B0%25B7%25E6%2599%2583&as_vis=0&as_sdt=0,33
[2023-01-06 16:50:49,141] ERROR {cps.metadata_provider.amazon:129} 503 Server Error: Service Unavailable for url: https://www.amazon.com/s?k=%E7%86%8A%E8%B0%B7%E6%99%83&i=digital-text&sprefix=%E7%86%8A%E8%B0%B7%E6%99%83%2Cdigital-text&ref=nb_sb_noss
[2023-01-06 16:50:49,597] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 16:50:49,597] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 16:50:49,597] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 16:50:50,526] ERROR {cps:1457} Exception on /metadata/search [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.10/dist-packages/flask_login/utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/app/calibre-web/cps/search_metadata.py", line 141, in metadata_search
    data.extend([asdict(x) for x in future.result() if x])
TypeError: 'NoneType' object is not iterable
[2023-01-06 16:51:02,606]  WARN {cps.metadata_provider.douban:113} 403 Client Error: Forbidden for url: https://sec.douban.com/b?r=https%3A%2F%2Fwww.douban.com%2Fsearch%3Fcat%3D1001%26q%3D%25E5%258F%2591%25E6%2598%258E%25EF%25BC%259A%25E8%25A9%25B9%25E5%25A7%2586%25E6%2596%25AF%25C2%25B7%25E6%2588%25B4%25E6%25A3%25AE%25E5%2588%259B%25E9%2580%25A0%25E4%25B9%258B%25E6%2597%2585
[2023-01-06 16:51:02,606]  INFO {scholarly:95} Getting https://scholar.google.com/scholar?hl=en&q=%25E5%258F%2591%25E6%2598%258E%25EF%25BC%259A%25E8%25A9%25B9%25E5%25A7%2586%25E6%2596%25AF%25C2%25B7%25E6%2588%25B4%25E6%25A3%25AE%25E5%2588%259B%25E9%2580%25A0%25E4%25B9%258B%25E6%2597%2585&as_vis=0&as_sdt=0,33
[2023-01-06 16:51:02,777] ERROR {cps.metadata_provider.amazon:129} 503 Server Error: Service Unavailable for url: https://www.amazon.com/s?k=%E5%8F%91%E6%98%8E%EF%BC%9A%E8%A9%B9%E5%A7%86%E6%96%AF%C2%B7%E6%88%B4%E6%A3%AE%E5%88%9B%E9%80%A0%E4%B9%8B%E6%97%85&i=digital-text&sprefix=%E5%8F%91%E6%98%8E%EF%BC%9A%E8%A9%B9%E5%A7%86%E6%96%AF%C2%B7%E6%88%B4%E6%A3%AE%E5%88%9B%E9%80%A0%E4%B9%8B%E6%97%85%2Cdigital-text&ref=nb_sb_noss
[2023-01-06 16:51:03,859] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 16:51:03,859] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 16:51:03,859] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 16:51:03,860] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 16:51:03,860] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 16:51:03,860] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 16:51:03,860] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 16:51:03,860] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 16:51:03,861] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 16:51:03,861] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 16:51:05,748] ERROR {cps:1457} Exception on /metadata/search [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.10/dist-packages/flask_login/utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/app/calibre-web/cps/search_metadata.py", line 141, in metadata_search
    data.extend([asdict(x) for x in future.result() if x])
TypeError: 'NoneType' object is not iterable
[2023-01-06 16:51:05,874]  WARN {cps.metadata_provider.douban:113} 403 Client Error: Forbidden for url: https://sec.douban.com/b?r=https%3A%2F%2Fwww.douban.com%2Fsearch%3Fcat%3D1001%26q%3D%25E5%258F%2591%25E6%2598%258E%25EF%25BC%259A%25E8%25A9%25B9%25E5%25A7%2586%25E6%2596%25AF%25C2%25B7%25E6%2588%25B4%25E6%25A3%25AE%25E5%2588%259B%25E9%2580%25A0%25E4%25B9%258B%25E6%2597%2585
[2023-01-06 16:51:05,875]  INFO {scholarly:95} Getting https://scholar.google.com/scholar?hl=en&q=%25E5%258F%2591%25E6%2598%258E%25EF%25BC%259A%25E8%25A9%25B9%25E5%25A7%2586%25E6%2596%25AF%25C2%25B7%25E6%2588%25B4%25E6%25A3%25AE%25E5%2588%259B%25E9%2580%25A0%25E4%25B9%258B%25E6%2597%2585&as_vis=0&as_sdt=0,33
[2023-01-06 16:51:06,104] ERROR {cps.metadata_provider.amazon:129} 503 Server Error: Service Unavailable for url: https://www.amazon.com/s?k=%E5%8F%91%E6%98%8E%EF%BC%9A%E8%A9%B9%E5%A7%86%E6%96%AF%C2%B7%E6%88%B4%E6%A3%AE%E5%88%9B%E9%80%A0%E4%B9%8B%E6%97%85&i=digital-text&sprefix=%E5%8F%91%E6%98%8E%EF%BC%9A%E8%A9%B9%E5%A7%86%E6%96%AF%C2%B7%E6%88%B4%E6%A3%AE%E5%88%9B%E9%80%A0%E4%B9%8B%E6%97%85%2Cdigital-text&ref=nb_sb_noss
[2023-01-06 16:51:06,747] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 16:51:06,748] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 16:51:06,748] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 16:51:06,748] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 16:51:06,748] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 16:51:06,749] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 16:51:06,749] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 16:51:06,749] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 16:51:06,749] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 16:51:06,749] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 16:51:08,363] ERROR {cps:1457} Exception on /metadata/search [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.10/dist-packages/flask_login/utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/app/calibre-web/cps/search_metadata.py", line 141, in metadata_search
    data.extend([asdict(x) for x in future.result() if x])
TypeError: 'NoneType' object is not iterable
[2023-01-06 16:55:18,746] ERROR {cps.metadata_provider.amazon:129} 503 Server Error: Service Unavailable for url: https://www.amazon.com/s?k=Contextual+Design&i=digital-text&sprefix=Contextual+Design%2Cdigital-text&ref=nb_sb_noss
[2023-01-06 16:55:18,747]  INFO {scholarly:95} Getting https://scholar.google.com/scholar?hl=en&q=Contextual%20Design&as_vis=0&as_sdt=0,33
[2023-01-06 16:55:19,457]  WARN {cps.metadata_provider.douban:113} 403 Client Error: Forbidden for url: https://sec.douban.com/b?r=https%3A%2F%2Fwww.douban.com%2Fsearch%3Fcat%3D1001%26q%3DContextual%252BDesign
[2023-01-06 16:55:21,718] ERROR {cps:1457} Exception on /metadata/search [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.10/dist-packages/flask_login/utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/app/calibre-web/cps/search_metadata.py", line 141, in metadata_search
    data.extend([asdict(x) for x in future.result() if x])
TypeError: 'NoneType' object is not iterable
[2023-01-06 16:55:24,298]  WARN {cps.metadata_provider.douban:113} 403 Client Error: Forbidden for url: https://sec.douban.com/b?r=https%3A%2F%2Fwww.douban.com%2Fsearch%3Fcat%3D1001%26q%3DContextual%252BDesign
[2023-01-06 16:55:24,299]  INFO {scholarly:95} Getting https://scholar.google.com/scholar?hl=en&q=Contextual%20Design&as_vis=0&as_sdt=0,33
[2023-01-06 16:55:24,472] ERROR {cps.metadata_provider.amazon:129} 503 Server Error: Service Unavailable for url: https://www.amazon.com/s?k=Contextual+Design&i=digital-text&sprefix=Contextual+Design%2Cdigital-text&ref=nb_sb_noss
[2023-01-06 16:55:26,684] ERROR {cps:1457} Exception on /metadata/search [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.10/dist-packages/flask_login/utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/app/calibre-web/cps/search_metadata.py", line 141, in metadata_search
    data.extend([asdict(x) for x in future.result() if x])
TypeError: 'NoneType' object is not iterable
[2023-01-06 16:56:03,915] ERROR {cps.metadata_provider.amazon:129} 503 Server Error: Service Unavailable for url: https://www.amazon.com/s?k=%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%BD%91%E7%BB%9C%EF%BC%88%E7%AC%AC7%E7%89%88%EF%BC%89&i=digital-text&sprefix=%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%BD%91%E7%BB%9C%EF%BC%88%E7%AC%AC7%E7%89%88%EF%BC%89%2Cdigital-text&ref=nb_sb_noss
[2023-01-06 16:56:03,916]  INFO {scholarly:95} Getting https://scholar.google.com/scholar?hl=en&q=%25E8%25AE%25A1%25E7%25AE%2597%25E6%259C%25BA%25E7%25BD%2591%25E7%25BB%259C%25EF%25BC%2588%25E7%25AC%25AC7%25E7%2589%2588%25EF%25BC%2589&as_vis=0&as_sdt=0,33
[2023-01-06 16:56:04,822] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 16:56:04,823] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 16:56:04,823] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 16:56:04,823] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 16:56:04,823] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 16:56:04,824] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 16:56:04,824] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 16:56:04,824] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 16:56:04,824] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 16:56:05,287]  WARN {cps.metadata_provider.douban:113} 403 Client Error: Forbidden for url: https://sec.douban.com/b?r=https%3A%2F%2Fwww.douban.com%2Fsearch%3Fcat%3D1001%26q%3D%25E8%25AE%25A1%25E7%25AE%2597%25E6%259C%25BA%25E7%25BD%2591%25E7%25BB%259C%25EF%25BC%2588%25E7%25AC%25AC7%25E7%2589%2588%25EF%25BC%2589
[2023-01-06 16:56:05,869] ERROR {cps:1457} Exception on /metadata/search [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.10/dist-packages/flask_login/utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/app/calibre-web/cps/search_metadata.py", line 141, in metadata_search
    data.extend([asdict(x) for x in future.result() if x])
TypeError: 'NoneType' object is not iterable
[2023-01-06 16:57:48,103] ERROR {cps.metadata_provider.amazon:129} 503 Server Error: Service Unavailable for url: https://www.amazon.com/s?k=%E6%9A%B4%E5%8A%9B%E6%8B%93%E6%89%91%E5%AD%A6&i=digital-text&sprefix=%E6%9A%B4%E5%8A%9B%E6%8B%93%E6%89%91%E5%AD%A6%2Cdigital-text&ref=nb_sb_noss
[2023-01-06 16:57:48,104]  INFO {scholarly:95} Getting https://scholar.google.com/scholar?hl=en&q=%25E6%259A%25B4%25E5%258A%259B%25E6%258B%2593%25E6%2589%2591%25E5%25AD%25A6&as_vis=0&as_sdt=0,33
[2023-01-06 16:57:48,817]  WARN {cps.metadata_provider.douban:113} 403 Client Error: Forbidden for url: https://sec.douban.com/b?r=https%3A%2F%2Fwww.douban.com%2Fsearch%3Fcat%3D1001%26q%3D%25E6%259A%25B4%25E5%258A%259B%25E6%258B%2593%25E6%2589%2591%25E5%25AD%25A6
[2023-01-06 16:57:49,010] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 16:57:49,010] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 16:57:49,011] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 16:57:49,011] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 16:57:49,011] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 16:57:49,012] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 16:57:49,012] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 16:57:49,012] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 16:57:49,012] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 16:57:49,012] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 16:57:50,618] ERROR {cps:1457} Exception on /metadata/search [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.10/dist-packages/flask_login/utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/app/calibre-web/cps/search_metadata.py", line 141, in metadata_search
    data.extend([asdict(x) for x in future.result() if x])
TypeError: 'NoneType' object is not iterable
[2023-01-06 16:58:42,838]  WARN {cps.metadata_provider.douban:113} 403 Client Error: Forbidden for url: https://sec.douban.com/b?r=https%3A%2F%2Fwww.douban.com%2Fsearch%3Fcat%3D1001%26q%3D%25E4%25B8%25BA%25E7%259C%259F%25E5%25AE%259E%25E7%259A%2584%25E4%25B8%2596%25E7%2595%258C%25E8%25AE%25BE%25E8%25AE%25A1
[2023-01-06 16:58:42,839]  INFO {scholarly:95} Getting https://scholar.google.com/scholar?hl=en&q=%25E4%25B8%25BA%25E7%259C%259F%25E5%25AE%259E%25E7%259A%2584%25E4%25B8%2596%25E7%2595%258C%25E8%25AE%25BE%25E8%25AE%25A1&as_vis=0&as_sdt=0,33
[2023-01-06 16:58:43,032] ERROR {cps.metadata_provider.amazon:129} 503 Server Error: Service Unavailable for url: https://www.amazon.com/s?k=%E4%B8%BA%E7%9C%9F%E5%AE%9E%E7%9A%84%E4%B8%96%E7%95%8C%E8%AE%BE%E8%AE%A1&i=digital-text&sprefix=%E4%B8%BA%E7%9C%9F%E5%AE%9E%E7%9A%84%E4%B8%96%E7%95%8C%E8%AE%BE%E8%AE%A1%2Cdigital-text&ref=nb_sb_noss
[2023-01-06 16:58:44,056] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 16:58:44,057] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 16:58:44,057] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 16:58:44,057] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 16:58:44,058] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 16:58:44,058] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 16:58:44,058] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 16:58:44,058] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 16:58:44,058] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 16:58:45,360] ERROR {cps:1457} Exception on /metadata/search [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.10/dist-packages/flask_login/utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/app/calibre-web/cps/search_metadata.py", line 141, in metadata_search
    data.extend([asdict(x) for x in future.result() if x])
TypeError: 'NoneType' object is not iterable
[2023-01-06 17:00:17,454] ERROR {cps.metadata_provider.amazon:129} 503 Server Error: Service Unavailable for url: https://www.amazon.com/s?k=%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%BD%91%E7%BB%9C%EF%BC%88%E7%AC%AC7%E7%89%88%EF%BC%89&i=digital-text&sprefix=%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%BD%91%E7%BB%9C%EF%BC%88%E7%AC%AC7%E7%89%88%EF%BC%89%2Cdigital-text&ref=nb_sb_noss
[2023-01-06 17:00:17,455]  INFO {scholarly:95} Getting https://scholar.google.com/scholar?hl=en&q=%25E8%25AE%25A1%25E7%25AE%2597%25E6%259C%25BA%25E7%25BD%2591%25E7%25BB%259C%25EF%25BC%2588%25E7%25AC%25AC7%25E7%2589%2588%25EF%25BC%2589&as_vis=0&as_sdt=0,33
[2023-01-06 17:00:18,143]  WARN {cps.metadata_provider.douban:113} 403 Client Error: Forbidden for url: https://sec.douban.com/b?r=https%3A%2F%2Fwww.douban.com%2Fsearch%3Fcat%3D1001%26q%3D%25E8%25AE%25A1%25E7%25AE%2597%25E6%259C%25BA%25E7%25BD%2591%25E7%25BB%259C%25EF%25BC%2588%25E7%25AC%25AC7%25E7%2589%2588%25EF%25BC%2589
[2023-01-06 17:00:18,300] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 17:00:18,300] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 17:00:18,301] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 17:00:18,301] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 17:00:18,301] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 17:00:18,301] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 17:00:18,302] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 17:00:18,302] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 17:00:18,302] ERROR {cps.isoLanguages:59} Missing translation for language name: 
[2023-01-06 17:00:20,143] ERROR {cps:1457} Exception on /metadata/search [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.10/dist-packages/flask_login/utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/app/calibre-web/cps/search_metadata.py", line 141, in metadata_search
    data.extend([asdict(x) for x in future.result() if x])
TypeError: 'NoneType' object is not iterable
```

**Comment by drizuid** [comment]
are you able to replicate the issue if you deploy the container using docker run or docker compose from the cli? The syno gui is janky and can causes issues so we do not support it. Also, without the requested data (such as the volumes that would show in docker run/compose) we can't really help.
