### ISSUE TITLE
[BUG] Permission error for log-files in v0.6.20-ls205

### ISSUE THREAD

**Issue by PhilippKammann** [linuxserver/docker-calibre-web#249]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Container fails to run with a permission denied error for `'/app/calibre-web/calibre-web.log'` and `'/app/calibre-web/access.log'` in v[0.6.20-ls205](https://github.com/linuxserver/docker-calibre-web/releases/tag/0.6.20-ls205). Error didn't occur with v[0.6.20-ls204](https://github.com/linuxserver/docker-calibre-web/releases/tag/0.6.20-ls204) and reverting to v[0.6.20-ls204](https://github.com/linuxserver/docker-calibre-web/releases/tag/0.6.20-ls204) removes the error. 

### Expected Behavior

Container should start succesfully in v[0.6.20-ls205](https://github.com/linuxserver/docker-calibre-web/releases/tag/0.6.20-ls205) with the same docker-compose settings as v[0.6.20-ls204](https://github.com/linuxserver/docker-calibre-web/releases/tag/0.6.20-ls204)

### Steps To Reproduce

1. Run the container with docker-compose file in v[0.6.20-ls204](https://github.com/linuxserver/docker-calibre-web/releases/tag/0.6.20-ls204)
2. Remove the container
3. Try to run the container with same docker-compose file in [0.6.20-ls205](https://github.com/linuxserver/docker-calibre-web/releases/tag/0.6.20-ls205)
4. Get permission error

### Environment

```markdown
- OS: OOpenmediavault 6 (based on Debian 11)
- How docker service was installed: OMV Extras
- Docker managed with Portainer
```

### CPU architecture

x86-64

### Docker creation

```bash
---
version: "2.1"
services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - DOCKER_MODS=linuxserver/mods:universal-calibre
    volumes:
      - /data/config/calibre-config:/config
      - /data/media/books:/books
    ports:
      - 8083:8083
    restart: unless-stopped
```

### Container logs

```bash
main()

  File "/app/calibre-web/cps/main.py", line 31, in main

    app = create_app()

  File "/app/calibre-web/cps/__init__.py", line 123, in create_app

    log.error(error)

Message: PermissionError(13, 'Permission denied')

Arguments: ()

--- Logging error ---

Traceback (most recent call last):

  File "/usr/lib/python3.10/logging/handlers.py", line 74, in emit

    self.doRollover()

  File "/usr/lib/python3.10/logging/handlers.py", line 179, in doRollover

    self.rotate(self.baseFilename, dfn)

  File "/usr/lib/python3.10/logging/handlers.py", line 115, in rotate

    os.rename(source, dest)

PermissionError: [Errno 13] Permission denied: '/app/calibre-web/calibre-web.log' -> '/app/calibre-web/calibre-web.log.1'

Call stack:

  File "/app/calibre-web/cps.py", line 31, in <module>

    main()

  File "/app/calibre-web/cps/main.py", line 31, in main

    app = create_app()

  File "/app/calibre-web/cps/__init__.py", line 176, in create_app

    log.info('Starting Calibre Web...')

Message: 'Starting Calibre Web...'

Arguments: ()

Traceback (most recent call last):

  File "/app/calibre-web/cps.py", line 31, in <module>

    main()

  File "/app/calibre-web/cps/main.py", line 31, in main

    app = create_app()

  File "/app/calibre-web/cps/__init__.py", line 181, in create_app

    web_server.init_app(app, config)

  File "/app/calibre-web/cps/server.py", line 78, in init_app

    self.access_logger, logfile = logger.create_access_log(config.config_access_logfile, log_name, formatter)

  File "/app/calibre-web/cps/logger.py", line 179, in create_access_log

    file_handler = RotatingFileHandler(log_file, maxBytes=50000, backupCount=2, encoding='utf-8')

  File "/usr/lib/python3.10/logging/handlers.py", line 155, in __init__

    BaseRotatingHandler.__init__(self, filename, mode, encoding=encoding,

  File "/usr/lib/python3.10/logging/handlers.py", line 58, in __init__

    logging.FileHandler.__init__(self, filename, mode=mode,

  File "/usr/lib/python3.10/logging/__init__.py", line 1169, in __init__

    StreamHandler.__init__(self, self._open())

  File "/usr/lib/python3.10/logging/__init__.py", line 1201, in _open

    return open_func(self.baseFilename, self.mode,

PermissionError: [Errno 13] Permission denied: '/app/calibre-web/access.log'
```

**Comment by Gummibaer** [comment]
Same here

**Comment by fire1ce** [comment]
same here.

**Comment by thespad** [comment]
Please test with `lspipepr/calibre-web:0.6.20-pkg-4675aaca-pr-250` and see if it resolves your issues.

**Comment by PhilippKammann** [comment]
> Please test with `lspipepr/calibre-web:0.6.20-pkg-4675aaca-pr-250` and see if it resolves your issues.

Issue is resolved with this image 👍
