### ISSUE TITLE
[BUG] Conversion fails with ImportError

### ISSUE THREAD

**Issue by zgentry** [linuxserver/docker-calibre-web#258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After creating a new calibre-web container with the DOCKER_MODS=linuxserver/mods:universal-calibre flag enabled and the ebook-converter directory setup in the web-ui, all book conversions I try are failing. They are failing immediately with the logs ending with:

`[2023-06-13 01:10:31,975]  INFO {cps.tasks.convert:188} ebook converter failed with error while converting book
[2023-06-13 01:10:31,976] ERROR {cps.tasks.convert:192} Calibre failed with error: ImportError: cannot import name 'QWebEnginePage' from 'qt.webengine' (/app/calibre/lib/calibre-extensions/python-lib.bypy.frozen/qt/webengine.pyc)`

or 

`[2023-06-13 01:10:13,445]  INFO {cps.tasks.convert:188} ebook converter failed with error while converting book
[2023-06-13 01:10:13,446] ERROR {cps.tasks.convert:192} Calibre failed with error: ImportError: cannot import name 'QBuffer' from 'qt.core' (/app/calibre/lib/calibre-extensions/python-lib.bypy.frozen/qt/core.pyc)`

I have tried multiple conversions including MOBI->EPUB, MOBI->LRF, EPUB->MOBI, EPUB->PDF with all ending with either of those two logs. 

### Expected Behavior

The conversion should succeed. 

### Steps To Reproduce

1. Create a new container using docker compose with the DOCKER_MODS=linuxserver/mods:universal-calibre flag 
2. Enable conversion in the web-ui settings by configuring the path.
3. Try to convert a file

### Environment

```markdown
- OS: CentOS 7
- How docker service was installed: YUM
- Kernal: 3.10.0-1160.71.1.el7.x86_64
```

### CPU architecture

x86-64

### Docker creation

```bash
---
version: "2.1"
services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - /var/lib/calibre-web/config:/config
      - /var/lib/calibre-web/library:/books
    ports:
      - 8083:8083
    restart: unless-stopped
```

### Container logs

```bash
[mod-init] Attempting to run Docker Modification Logic
[mod-init] Adding linuxserver/mods:universal-calibre to container
[mod-init] Downloading linuxserver/mods:universal-calibre from lscr.io
[mod-init] Installing linuxserver/mods:universal-calibre
[mod-init] linuxserver/mods:universal-calibre applied to container
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    0
User GID:    0
───────────────────────────────────────

**** Adding calibre dependencies to package install list ****
[mod-init] **** Installing all mod packages ****
Get:1 http://archive.ubuntu.com/ubuntu jammy InRelease [270 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Get:4 http://archive.ubuntu.com/ubuntu jammy/universe Sources [22.0 MB]
Get:5 http://archive.ubuntu.com/ubuntu jammy/main Sources [1,668 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy/multiverse Sources [361 kB]
Get:7 http://archive.ubuntu.com/ubuntu jammy/restricted Sources [28.2 kB]
Get:8 http://archive.ubuntu.com/ubuntu jammy/multiverse amd64 Packages [266 kB]
Get:9 http://archive.ubuntu.com/ubuntu jammy/restricted amd64 Packages [164 kB]
Get:10 http://archive.ubuntu.com/ubuntu jammy/universe amd64 Packages [17.5 MB]
Get:11 http://archive.ubuntu.com/ubuntu jammy/main amd64 Packages [1,792 kB]
Get:12 http://archive.ubuntu.com/ubuntu jammy-updates/multiverse Sources [19.5 kB]
Get:13 http://archive.ubuntu.com/ubuntu jammy-updates/main Sources [495 kB]
Get:14 http://archive.ubuntu.com/ubuntu jammy-updates/universe Sources [309 kB]
Get:15 http://archive.ubuntu.com/ubuntu jammy-updates/restricted Sources [44.3 kB]
Get:16 http://archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [42.2 kB]
Get:17 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [861 kB]
Get:18 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,178 kB]
Get:19 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [457 kB]
Get:20 http://archive.ubuntu.com/ubuntu jammy-security/multiverse Sources [9,759 B]
Get:21 http://archive.ubuntu.com/ubuntu jammy-security/restricted Sources [41.6 kB]
Get:22 http://archive.ubuntu.com/ubuntu jammy-security/universe Sources [181 kB]
Get:23 http://archive.ubuntu.com/ubuntu jammy-security/main Sources [239 kB]
Get:24 http://archive.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [36.3 kB]
Get:25 http://archive.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [456 kB]
Get:26 http://archive.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [928 kB]
Get:27 http://archive.ubuntu.com/ubuntu jammy-security/main amd64 Packages [579 kB]
Fetched 50.1 MB in 5s (9,136 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libdrm-amdgpu1 libdrm-common libdrm-nouveau2 libdrm-radeon1 libdrm2 libedit2
  libegl-mesa0 libelf1 libgbm1 libgl1 libgl1-mesa-dri libglapi-mesa libglvnd0
  libglx-mesa0 libglx0 libllvm15 libsensors-config libsensors5
  libwayland-client0 libwayland-server0 libx11-xcb1 libxcb-dri2-0
  libxcb-dri3-0 libxcb-glx0 libxcb-present0 libxcb-shm0 libxcb-sync1
  libxcb-xfixes0 libxfixes3 libxshmfence1 libxxf86vm1 xkb-data
Suggested packages:
  lm-sensors
Recommended packages:
  libgl1-amber-dri
The following NEW packages will be installed:
  libdrm-amdgpu1 libdrm-common libdrm-nouveau2 libdrm-radeon1 libdrm2 libedit2
  libegl-mesa0 libegl1 libelf1 libgbm1 libgl1 libgl1-mesa-dri libgl1-mesa-glx
  libglapi-mesa libglvnd0 libglx-mesa0 libglx0 libllvm15 libopengl0
  libsensors-config libsensors5 libwayland-client0 libwayland-server0
  libx11-xcb1 libxcb-dri2-0 libxcb-dri3-0 libxcb-glx0 libxcb-present0
  libxcb-shm0 libxcb-sync1 libxcb-xfixes0 libxdamage1 libxfixes3 libxkbcommon0
  libxshmfence1 libxxf86vm1 xkb-data xz-utils
0 upgraded, 38 newly installed, 0 to remove and 1 not upgraded.
Need to get 34.6 MB of archives.
After this operation, 152 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 libelf1 amd64 0.186-1build1 [51.0 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/main amd64 xkb-data all 2.33-1 [394 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libdrm-common all 2.4.113-2~ubuntu0.22.04.1 [5,450 B]
Get:4 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libdrm2 amd64 2.4.113-2~ubuntu0.22.04.1 [38.1 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy/main amd64 libedit2 amd64 3.1-20210910-1build1 [96.8 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy/main amd64 xz-utils amd64 5.2.5-2ubuntu1 [84.8 kB]
Get:7 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libdrm-amdgpu1 amd64 2.4.113-2~ubuntu0.22.04.1 [19.9 kB]
Get:8 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libdrm-nouveau2 amd64 2.4.113-2~ubuntu0.22.04.1 [17.5 kB]
Get:9 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libdrm-radeon1 amd64 2.4.113-2~ubuntu0.22.04.1 [21.6 kB]
Get:10 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libwayland-server0 amd64 1.20.0-1ubuntu0.1 [34.3 kB]
Get:11 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgbm1 amd64 22.2.5-0ubuntu0.1~22.04.1 [33.0 kB]
Get:12 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libglapi-mesa amd64 22.2.5-0ubuntu0.1~22.04.1 [35.3 kB]
Get:13 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libwayland-client0 amd64 1.20.0-1ubuntu0.1 [25.9 kB]
Get:14 http://archive.ubuntu.com/ubuntu jammy/main amd64 libx11-xcb1 amd64 2:1.7.5-1 [7,790 B]
Get:15 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcb-dri2-0 amd64 1.14-3ubuntu3 [7,206 B]
Get:16 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcb-dri3-0 amd64 1.14-3ubuntu3 [6,968 B]
Get:17 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcb-present0 amd64 1.14-3ubuntu3 [5,734 B]
Get:18 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcb-sync1 amd64 1.14-3ubuntu3 [9,416 B]
Get:19 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcb-xfixes0 amd64 1.14-3ubuntu3 [9,996 B]
Get:20 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxshmfence1 amd64 1.3-1build4 [5,394 B]
Get:21 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libegl-mesa0 amd64 22.2.5-0ubuntu0.1~22.04.1 [111 kB]
Get:22 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libllvm15 amd64 1:15.0.7-0ubuntu0.22.04.1 [25.4 MB]
Get:23 http://archive.ubuntu.com/ubuntu jammy/main amd64 libsensors-config all 1:3.6.0-7ubuntu1 [5,274 B]
Get:24 http://archive.ubuntu.com/ubuntu jammy/main amd64 libsensors5 amd64 1:3.6.0-7ubuntu1 [26.3 kB]
Get:25 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgl1-mesa-dri amd64 22.2.5-0ubuntu0.1~22.04.1 [7,511 kB]
Get:26 http://archive.ubuntu.com/ubuntu jammy/main amd64 libglvnd0 amd64 1.4.0-1 [73.6 kB]
Get:27 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcb-glx0 amd64 1.14-3ubuntu3 [25.9 kB]
Get:28 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcb-shm0 amd64 1.14-3ubuntu3 [5,780 B]
Get:29 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxfixes3 amd64 1:6.0.0-1 [11.7 kB]
Get:30 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxxf86vm1 amd64 1:1.1.4-1build3 [10.4 kB]
Get:31 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libglx-mesa0 amd64 22.2.5-0ubuntu0.1~22.04.1 [158 kB]
Get:32 http://archive.ubuntu.com/ubuntu jammy/main amd64 libglx0 amd64 1.4.0-1 [41.0 kB]
Get:33 http://archive.ubuntu.com/ubuntu jammy/main amd64 libgl1 amd64 1.4.0-1 [110 kB]
Get:34 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 libgl1-mesa-glx amd64 22.2.5-0ubuntu0.1~22.04.1 [5,466 B]
Get:35 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxdamage1 amd64 1:1.1.5-2build2 [7,154 B]
Get:36 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxkbcommon0 amd64 1.4.0-1 [125 kB]
Get:37 http://archive.ubuntu.com/ubuntu jammy/main amd64 libegl1 amd64 1.4.0-1 [28.6 kB]
Get:38 http://archive.ubuntu.com/ubuntu jammy/main amd64 libopengl0 amd64 1.4.0-1 [36.5 kB]
Fetched 34.6 MB in 3s (11.0 MB/s)
Selecting previously unselected package libelf1:amd64.
(Reading database ... 12535 files and directories currently installed.)
Preparing to unpack .../00-libelf1_0.186-1build1_amd64.deb ...
Unpacking libelf1:amd64 (0.186-1build1) ...
Selecting previously unselected package xkb-data.
Preparing to unpack .../01-xkb-data_2.33-1_all.deb ...
Unpacking xkb-data (2.33-1) ...
Selecting previously unselected package libdrm-common.
Preparing to unpack .../02-libdrm-common_2.4.113-2~ubuntu0.22.04.1_all.deb ...
Unpacking libdrm-common (2.4.113-2~ubuntu0.22.04.1) ...
Selecting previously unselected package libdrm2:amd64.
Preparing to unpack .../03-libdrm2_2.4.113-2~ubuntu0.22.04.1_amd64.deb ...
Unpacking libdrm2:amd64 (2.4.113-2~ubuntu0.22.04.1) ...
Selecting previously unselected package libedit2:amd64.
Preparing to unpack .../04-libedit2_3.1-20210910-1build1_amd64.deb ...
Unpacking libedit2:amd64 (3.1-20210910-1build1) ...
Selecting previously unselected package xz-utils.
Preparing to unpack .../05-xz-utils_5.2.5-2ubuntu1_amd64.deb ...
Unpacking xz-utils (5.2.5-2ubuntu1) ...
Selecting previously unselected package libdrm-amdgpu1:amd64.
Preparing to unpack .../06-libdrm-amdgpu1_2.4.113-2~ubuntu0.22.04.1_amd64.deb ...
Unpacking libdrm-amdgpu1:amd64 (2.4.113-2~ubuntu0.22.04.1) ...
Selecting previously unselected package libdrm-nouveau2:amd64.
Preparing to unpack .../07-libdrm-nouveau2_2.4.113-2~ubuntu0.22.04.1_amd64.deb ...
Unpacking libdrm-nouveau2:amd64 (2.4.113-2~ubuntu0.22.04.1) ...
Selecting previously unselected package libdrm-radeon1:amd64.
Preparing to unpack .../08-libdrm-radeon1_2.4.113-2~ubuntu0.22.04.1_amd64.deb ...
Unpacking libdrm-radeon1:amd64 (2.4.113-2~ubuntu0.22.04.1) ...
Selecting previously unselected package libwayland-server0:amd64.
Preparing to unpack .../09-libwayland-server0_1.20.0-1ubuntu0.1_amd64.deb ...
Unpacking libwayland-server0:amd64 (1.20.0-1ubuntu0.1) ...
Selecting previously unselected package libgbm1:amd64.
Preparing to unpack .../10-libgbm1_22.2.5-0ubuntu0.1~22.04.1_amd64.deb ...
Unpacking libgbm1:amd64 (22.2.5-0ubuntu0.1~22.04.1) ...
Selecting previously unselected package libglapi-mesa:amd64.
Preparing to unpack .../11-libglapi-mesa_22.2.5-0ubuntu0.1~22.04.1_amd64.deb ...
Unpacking libglapi-mesa:amd64 (22.2.5-0ubuntu0.1~22.04.1) ...
Selecting previously unselected package libwayland-client0:amd64.
Preparing to unpack .../12-libwayland-client0_1.20.0-1ubuntu0.1_amd64.deb ...
Unpacking libwayland-client0:amd64 (1.20.0-1ubuntu0.1) ...
Selecting previously unselected package libx11-xcb1:amd64.
Preparing to unpack .../13-libx11-xcb1_2%3a1.7.5-1_amd64.deb ...
Unpacking libx11-xcb1:amd64 (2:1.7.5-1) ...
Selecting previously unselected package libxcb-dri2-0:amd64.
Preparing to unpack .../14-libxcb-dri2-0_1.14-3ubuntu3_amd64.deb ...
Unpacking libxcb-dri2-0:amd64 (1.14-3ubuntu3) ...
Selecting previously unselected package libxcb-dri3-0:amd64.
Preparing to unpack .../15-libxcb-dri3-0_1.14-3ubuntu3_amd64.deb ...
Unpacking libxcb-dri3-0:amd64 (1.14-3ubuntu3) ...
Selecting previously unselected package libxcb-present0:amd64.
Preparing to unpack .../16-libxcb-present0_1.14-3ubuntu3_amd64.deb ...
Unpacking libxcb-present0:amd64 (1.14-3ubuntu3) ...
Selecting previously unselected package libxcb-sync1:amd64.
Preparing to unpack .../17-libxcb-sync1_1.14-3ubuntu3_amd64.deb ...
Unpacking libxcb-sync1:amd64 (1.14-3ubuntu3) ...
Selecting previously unselected package libxcb-xfixes0:amd64.
Preparing to unpack .../18-libxcb-xfixes0_1.14-3ubuntu3_amd64.deb ...
Unpacking libxcb-xfixes0:amd64 (1.14-3ubuntu3) ...
Selecting previously unselected package libxshmfence1:amd64.
Preparing to unpack .../19-libxshmfence1_1.3-1build4_amd64.deb ...
Unpacking libxshmfence1:amd64 (1.3-1build4) ...
Selecting previously unselected package libegl-mesa0:amd64.
Preparing to unpack .../20-libegl-mesa0_22.2.5-0ubuntu0.1~22.04.1_amd64.deb ...
Unpacking libegl-mesa0:amd64 (22.2.5-0ubuntu0.1~22.04.1) ...
Selecting previously unselected package libllvm15:amd64.
Preparing to unpack .../21-libllvm15_1%3a15.0.7-0ubuntu0.22.04.1_amd64.deb ...
Unpacking libllvm15:amd64 (1:15.0.7-0ubuntu0.22.04.1) ...
Selecting previously unselected package libsensors-config.
Preparing to unpack .../22-libsensors-config_1%3a3.6.0-7ubuntu1_all.deb ...
Unpacking libsensors-config (1:3.6.0-7ubuntu1) ...
Selecting previously unselected package libsensors5:amd64.
Preparing to unpack .../23-libsensors5_1%3a3.6.0-7ubuntu1_amd64.deb ...
Unpacking libsensors5:amd64 (1:3.6.0-7ubuntu1) ...
Selecting previously unselected package libgl1-mesa-dri:amd64.
Preparing to unpack .../24-libgl1-mesa-dri_22.2.5-0ubuntu0.1~22.04.1_amd64.deb ...
Unpacking libgl1-mesa-dri:amd64 (22.2.5-0ubuntu0.1~22.04.1) ...
Selecting previously unselected package libglvnd0:amd64.
Preparing to unpack .../25-libglvnd0_1.4.0-1_amd64.deb ...
Unpacking libglvnd0:amd64 (1.4.0-1) ...
Selecting previously unselected package libxcb-glx0:amd64.
Preparing to unpack .../26-libxcb-glx0_1.14-3ubuntu3_amd64.deb ...
Unpacking libxcb-glx0:amd64 (1.14-3ubuntu3) ...
Selecting previously unselected package libxcb-shm0:amd64.
Preparing to unpack .../27-libxcb-shm0_1.14-3ubuntu3_amd64.deb ...
Unpacking libxcb-shm0:amd64 (1.14-3ubuntu3) ...
Selecting previously unselected package libxfixes3:amd64.
Preparing to unpack .../28-libxfixes3_1%3a6.0.0-1_amd64.deb ...
Unpacking libxfixes3:amd64 (1:6.0.0-1) ...
Selecting previously unselected package libxxf86vm1:amd64.
Preparing to unpack .../29-libxxf86vm1_1%3a1.1.4-1build3_amd64.deb ...
Unpacking libxxf86vm1:amd64 (1:1.1.4-1build3) ...
Selecting previously unselected package libglx-mesa0:amd64.
Preparing to unpack .../30-libglx-mesa0_22.2.5-0ubuntu0.1~22.04.1_amd64.deb ...
Unpacking libglx-mesa0:amd64 (22.2.5-0ubuntu0.1~22.04.1) ...
Selecting previously unselected package libglx0:amd64.
Preparing to unpack .../31-libglx0_1.4.0-1_amd64.deb ...
Unpacking libglx0:amd64 (1.4.0-1) ...
Selecting previously unselected package libgl1:amd64.
Preparing to unpack .../32-libgl1_1.4.0-1_amd64.deb ...
Unpacking libgl1:amd64 (1.4.0-1) ...
Selecting previously unselected package libgl1-mesa-glx:amd64.
Preparing to unpack .../33-libgl1-mesa-glx_22.2.5-0ubuntu0.1~22.04.1_amd64.deb ...
Unpacking libgl1-mesa-glx:amd64 (22.2.5-0ubuntu0.1~22.04.1) ...
Selecting previously unselected package libxdamage1:amd64.
Preparing to unpack .../34-libxdamage1_1%3a1.1.5-2build2_amd64.deb ...
Unpacking libxdamage1:amd64 (1:1.1.5-2build2) ...
Selecting previously unselected package libxkbcommon0:amd64.
Preparing to unpack .../35-libxkbcommon0_1.4.0-1_amd64.deb ...
Unpacking libxkbcommon0:amd64 (1.4.0-1) ...
Selecting previously unselected package libegl1:amd64.
Preparing to unpack .../36-libegl1_1.4.0-1_amd64.deb ...
Unpacking libegl1:amd64 (1.4.0-1) ...
Selecting previously unselected package libopengl0:amd64.
Preparing to unpack .../37-libopengl0_1.4.0-1_amd64.deb ...
Unpacking libopengl0:amd64 (1.4.0-1) ...
Setting up libxcb-dri3-0:amd64 (1.14-3ubuntu3) ...
Setting up libwayland-server0:amd64 (1.20.0-1ubuntu0.1) ...
Setting up libx11-xcb1:amd64 (2:1.7.5-1) ...
Setting up libxdamage1:amd64 (1:1.1.5-2build2) ...
Setting up libxcb-xfixes0:amd64 (1.14-3ubuntu3) ...
Setting up libglvnd0:amd64 (1.4.0-1) ...
Setting up libxcb-glx0:amd64 (1.14-3ubuntu3) ...
Setting up libedit2:amd64 (3.1-20210910-1build1) ...
Setting up libsensors-config (1:3.6.0-7ubuntu1) ...
Setting up xkb-data (2.33-1) ...
Setting up libxcb-shm0:amd64 (1.14-3ubuntu3) ...
Setting up libopengl0:amd64 (1.4.0-1) ...
Setting up libxxf86vm1:amd64 (1:1.1.4-1build3) ...
Setting up libxcb-present0:amd64 (1.14-3ubuntu3) ...
Setting up libxfixes3:amd64 (1:6.0.0-1) ...
Setting up libxcb-sync1:amd64 (1.14-3ubuntu3) ...
Setting up xz-utils (5.2.5-2ubuntu1) ...
update-alternatives: using /usr/bin/xz to provide /usr/bin/lzma (lzma) in auto mode
update-alternatives: warning: skip creation of /usr/share/man/man1/lzma.1.gz because associated file /usr/share/man/man1/xz.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/unlzma.1.gz because associated file /usr/share/man/man1/unxz.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzcat.1.gz because associated file /usr/share/man/man1/xzcat.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzmore.1.gz because associated file /usr/share/man/man1/xzmore.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzless.1.gz because associated file /usr/share/man/man1/xzless.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzdiff.1.gz because associated file /usr/share/man/man1/xzdiff.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzcmp.1.gz because associated file /usr/share/man/man1/xzcmp.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzgrep.1.gz because associated file /usr/share/man/man1/xzgrep.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzegrep.1.gz because associated file /usr/share/man/man1/xzegrep.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzfgrep.1.gz because associated file /usr/share/man/man1/xzfgrep.1.gz (of link group lzma) doesn't exist
Setting up libsensors5:amd64 (1:3.6.0-7ubuntu1) ...
Setting up libglapi-mesa:amd64 (22.2.5-0ubuntu0.1~22.04.1) ...
Setting up libxcb-dri2-0:amd64 (1.14-3ubuntu3) ...
Setting up libxshmfence1:amd64 (1.3-1build4) ...
Setting up libllvm15:amd64 (1:15.0.7-0ubuntu0.22.04.1) ...
Setting up libdrm-common (2.4.113-2~ubuntu0.22.04.1) ...
Setting up libelf1:amd64 (0.186-1build1) ...
Setting up libxkbcommon0:amd64 (1.4.0-1) ...
Setting up libwayland-client0:amd64 (1.20.0-1ubuntu0.1) ...
Setting up libdrm2:amd64 (2.4.113-2~ubuntu0.22.04.1) ...
Setting up libdrm-amdgpu1:amd64 (2.4.113-2~ubuntu0.22.04.1) ...
Setting up libdrm-nouveau2:amd64 (2.4.113-2~ubuntu0.22.04.1) ...
Setting up libgbm1:amd64 (22.2.5-0ubuntu0.1~22.04.1) ...
Setting up libdrm-radeon1:amd64 (2.4.113-2~ubuntu0.22.04.1) ...
Setting up libgl1-mesa-dri:amd64 (22.2.5-0ubuntu0.1~22.04.1) ...
Setting up libegl-mesa0:amd64 (22.2.5-0ubuntu0.1~22.04.1) ...
Setting up libegl1:amd64 (1.4.0-1) ...
Setting up libglx-mesa0:amd64 (22.2.5-0ubuntu0.1~22.04.1) ...
Setting up libglx0:amd64 (1.4.0-1) ...
Setting up libgl1:amd64 (1.4.0-1) ...
Setting up libgl1-mesa-glx:amd64 (22.2.5-0ubuntu0.1~22.04.1) ...
Processing triggers for libc-bin (2.35-0ubuntu3.1) ...
**** Installing/updating calibre ****
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  130M  100  130M    0     0  30.5M      0  0:00:04  0:00:04 --:--:-- 35.5M
Failed to import PyQt module: PyQt6.QtCore with error: libQt6Core.so.6: cannot open shared object file: No such file or directory
Failed to import PyQt module: PyQt6.QtGui with error: libQt6Core.so.6: cannot open shared object file: No such file or directory
Creating symlinks...
        Symlinking /app/calibre/ebook-device to /usr/bin/ebook-device
        Symlinking /app/calibre/ebook-meta to /usr/bin/ebook-meta
        Symlinking /app/calibre/ebook-convert to /usr/bin/ebook-convert
        Symlinking /app/calibre/ebook-polish to /usr/bin/ebook-polish
        Symlinking /app/calibre/markdown-calibre to /usr/bin/markdown-calibre
        Symlinking /app/calibre/web2disk to /usr/bin/web2disk
        Symlinking /app/calibre/calibre-server to /usr/bin/calibre-server
        Symlinking /app/calibre/lrf2lrs to /usr/bin/lrf2lrs
        Symlinking /app/calibre/lrs2lrf to /usr/bin/lrs2lrf
        Symlinking /app/calibre/calibre-debug to /usr/bin/calibre-debug
        Symlinking /app/calibre/calibredb to /usr/bin/calibredb
        Symlinking /app/calibre/calibre-parallel to /usr/bin/calibre-parallel
        Symlinking /app/calibre/calibre-customize to /usr/bin/calibre-customize
        Symlinking /app/calibre/fetch-ebook-metadata to /usr/bin/fetch-ebook-metadata
        Symlinking /app/calibre/calibre-smtp to /usr/bin/calibre-smtp
        Symlinking /app/calibre/calibre to /usr/bin/calibre
        Symlinking /app/calibre/lrfviewer to /usr/bin/lrfviewer
        Symlinking /app/calibre/ebook-viewer to /usr/bin/ebook-viewer
        Symlinking /app/calibre/ebook-edit to /usr/bin/ebook-edit
Setting up command-line completion...
Installing zsh completion to: /usr/share/zsh/vendor-completions/_calibre
Failed to find directory to install bash completions, using default.
Installing bash completion to: /usr/share/bash-completion/completions/

____________________ WARNING ____________________
Setting up completion failed with error:
__________________________________________________


        Traceback (most recent call last):
          File "calibre/linux.py", line 837, in setup_completion
          File "calibre/linux.py", line 582, in write_completion
          File "bypy-importer.py", line 279, in exec_module
          File "calibre/ebooks/metadata/sources/cli.py", line 15, in <module>
          File "bypy-importer.py", line 279, in exec_module
          File "calibre/utils/img.py", line 13, in <module>
        ImportError: cannot import name 'QBuffer' from 'qt.core' (/app/calibre/lib/calibre-extensions/python-lib.bypy.frozen/qt/core.pyc)

Setting up desktop integration...

____________________ WARNING ____________________
Setting up desktop integration failed with error:
__________________________________________________


        Traceback (most recent call last):
          File "calibre/linux.py", line 858, in setup_desktop_integration
          File "calibre/linux.py", line 880, in do_setup_desktop_integration
          File "calibre/linux.py", line 911, in install_xdg_junk
          File "calibre/linux.py", line 896, in install_icons
          File "calibre/linux.py", line 886, in install_single_icon
          File "calibre/linux.py", line 1308, in render_img
        ImportError: cannot import name 'QImage' from 'qt.core' (/app/calibre/lib/calibre-extensions/python-lib.bypy.frozen/qt/core.pyc)

Creating un-installer: /usr/bin/calibre-uninstall


There were 2 warnings

* Setting up completion failed with error:

* Setting up desktop integration failed with error:

[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

**Comment by kasha695** [comment]
I'm currently facing the exact same issue, with the same errors. Fresh install today with the DOCKER_MODS variable and it fails to find libQt6Core.so.6

**Comment by aptalca** [comment]
those errors in the log are expected

**Comment by kasha695** [comment]
Sorry I should have added that I get the same errors in the docker log for libQt6Core.so.6 as well as both of the ImportError when attempting any kind of conversion in the calibre-web log files

**Comment by kasha695** [comment]
After looking further into the issue and the bug reports already closed I can see the issue here for both myself and @zgentry is to do with the linux kernel version 3.x as discussed [here](https://github.com/linuxserver/docker-calibre-web/issues/197)

Following the advice in the report, using the following DOCKER_MODS allows converting to work for the 3.x kernels:
`DOCKER_MODS=linuxserver/calibre-web:5.44.0-calibre`

**Comment by drizuid** [comment]
We are glad you guys found a solution. Unfortunately, we have no plans to directly support or make changes to support a kernel base from 2011. If something happens to work, we are happy, but we make no promises it will continue to work.

We also do not support puid/pgid of 0 nor do we test at all on redhat derivatives.
