### ISSUE TITLE
[BUG] <HTTP Error: API rate limit exceeded for 78.191.40.69.>

### ISSUE THREAD

**Issue by azataiot** [linuxserver/docker-calibre-web#260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When i click the check updates button on the admin dashboard, i got this error: 

![2023-07-07-at-06 22 10](https://github.com/linuxserver/docker-calibre-web/assets/8280770/65ce20ce-7457-45f7-97fe-29a797d3e0b7)

### Expected Behavior

It should shove me available versions to update

### Steps To Reproduce

1. Just go to admin dashboard
2. Click the button named "Check for Updates"

### Environment

```markdown
Running with the docker-compose with those settings: 


version: "3"
services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - ./config:/config
      - ./books:/books
      - ./certificates:/certificates
    ports:
      - 8008:8083
    restart: unless-stopped
```

### CPU architecture

x86-64

### Docker creation

```bash
version: "3"
services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - ./config:/config
      - ./books:/books
      - ./certificates:/certificates
    ports:
      - 8008:8083
    restart: unless-stopped
```
```


### Container logs

```bash
calibre-web  | Failed to find directory to install bash completions, using default.
calibre-web  | Installing bash completion to: /usr/share/bash-completion/completions/
calibre-web  | Setting up desktop integration...
calibre-web  | 
calibre-web  | 
calibre-web  | ____________________ WARNING ____________________
calibre-web  | Setting up desktop integration failed with error:
calibre-web  | __________________________________________________
calibre-web  | 
calibre-web  | 
calibre-web  | 
calibre-web  | 
calibre-web  |  Traceback (most recent call last):
calibre-web  |    File "calibre/linux.py", line 858, in setup_desktop_integration
calibre-web  |    File "calibre/linux.py", line 880, in do_setup_desktop_integration
calibre-web  |    File "calibre/linux.py", line 911, in install_xdg_junk
calibre-web  |    File "calibre/linux.py", line 896, in install_icons
calibre-web  |    File "calibre/linux.py", line 890, in install_single_icon
calibre-web  |    File "subprocess.py", line 364, in check_call
calibre-web  |    File "subprocess.py", line 345, in call
calibre-web  |    File "subprocess.py", line 966, in __init__
calibre-web  |    File "subprocess.py", line 1842, in _execute_child
calibre-web  |  FileNotFoundError: [Errno 2] No such file or directory: 'xdg-icon-resource'
calibre-web  | 
calibre-web  | 
calibre-web  | Creating un-installer: /usr/bin/calibre-uninstall
calibre-web  | 
calibre-web  | 
calibre-web  | 
calibre-web  | 
calibre-web  | There were 1 warnings
calibre-web  | 
calibre-web  | 
calibre-web  | * Setting up desktop integration failed with error:
calibre-web  | 
calibre-web  | 
calibre-web  | [custom-init] No custom files found, skipping...
calibre-web  | [ls.io-init] done.
```

**Comment by drizuid** [comment]
the readme tells you how to update calibre-web, what you are doing is not what it says.
