### ISSUE TITLE
[BUG] Lubimyczytac - scrapper

### ISSUE THREAD

**Issue by ozzinse** [linuxserver/docker-calibre-web#262]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Cannot get matadata from scrapper lubimyczytac.pl

### Steps To Reproduce

1. Add book to library 
2.  Start scrapper 

### Environment

```markdown
- docker
```

### CPU architecture

x86-64

### Docker creation

```bash
Standard docker command
```

### Container logs

```bash
TypeError: 'NoneType' object is not iterable
[2023-07-12 10:48:08,721] ERROR {cps:1449} Exception on /metadata/search [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.10/dist-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/app/calibre-web/cps/search_metadata.py", line 141, in metadata_search
    data.extend([asdict(x) for x in future.result() if x])
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/calibre-web/cps/metadata_provider/lubimyczytac.py", line 129, in search
    final_matches = pool.starmap(
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/app/calibre-web/cps/metadata_provider/lubimyczytac.py", line 225, in parse_single_book
    match.tags = self._parse_tags()
  File "/app/calibre-web/cps/metadata_provider/lubimyczytac.py", line 285, in _parse_tags
    return [
TypeError: 'NoneType' object is not iterable
```

**Comment by ozzinse** [comment]
What do you need to mark this bug as valid ?

**Comment by Roxedus** [comment]
A filled issue template, including full container logs, and the compose/run

**Comment by ozzinse** [comment]
I dont know my compose run colse this i will swich this container to other distribution

**Comment by ozzinse** [comment]
Here is the issue fix 
https://github.com/janeczku/calibre-web/pull/2833
