### ISSUE TITLE
Calibre-web tries and fails to update itself

### ISSUE THREAD

**Issue by kaibagley** [linuxserver/docker-calibre-web#264]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using calibre-web docker container, when it starts it checks repositories, finds a bunch of lib* updates, downloads about 30MB of updates, unpacks etc etc until it fails

After this process, the container starts and works as expected. Just maybe in an older version

### Expected Behavior

Container completes update and applies it to itself.

### Steps To Reproduce

1. docker compose up -d
2. docker logs calibre-web

### Environment

```markdown
OS: Ubuntu 22.04
Python version: 3.10.6
Calibre-Web version: linuxserver/calibre-web:latest
Docker container: linuxserver
```

### CPU architecture

x86-64

### Docker creation

```bash
version "3"
services:

...

calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Perth
      - DOCKER_MODS=linuxserver/mods:universal-calibre
    volumes:
      - /server/calibre/calibre-web:/config
      - /server/calibre/Calibre_Library:/books
    restart: unless-stopped
    depends_on:
      - calibre
    ports:
      - "8083:8083"
    networks:
      - ebooks

...

networks:
  ...
  ebooks:
    external: true
  ...
```

### Container logs

```bash
Symlinking /app/calibre/calibre-customize to /usr/bin/calibre-customize
Symlinking /app/calibre/fetch-ebook-metadata to /usr/bin/fetch-ebook-metadata
Symlinking /app/calibre/calibre-smtp to /usr/bin/calibre-smtp
Symlinking /app/calibre/calibre to /usr/bin/calibre
Symlinking /app/calibre/lrfviewer to /usr/bin/lrfviewer
Symlinking /app/calibre/ebook-viewer to /usr/bin/ebook-viewer
Symlinking /app/calibre/ebook-edit to /usr/bin/ebook-edit
Setting up command-line completion...
Installing zsh completion to: /usr/share/zsh/vendor-completions/_calibre
Failed to find directory to install bash completions, using default.
Installing bash completion to: /usr/share/bash-completion/completions/
Setting up desktop integration...

____________________ WARNING ____________________
Setting up desktop integration failed with error:

Traceback (most recent call last):
File "calibre/linux.py", line 858, in setup_desktop_integration
File "calibre/linux.py", line 880, in do_setup_desktop_integration
File "calibre/linux.py", line 911, in install_xdg_junk
File "calibre/linux.py", line 896, in install_icons
File "calibre/linux.py", line 890, in install_single_icon
File "subprocess.py", line 364, in check_call
File "subprocess.py", line 345, in call
File "subprocess.py", line 966, in init
File "subprocess.py", line 1842, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'xdg-icon-resource'

Creating un-installer: /usr/bin/calibre-uninstall

There were 1 warnings

    Setting up desktop integration failed with error:

[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

**Comment by kaibagley** [comment]
Right after I submitted this I found a duplicate issue... Sorry guys
