### ISSUE TITLE
[BUG] Can't get Calibre to Work past saving db location

### ISSUE THREAD

**Issue by psyciknz** [linuxserver/docker-calibre-web#266]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Trying to migrate a docker container from one machine to another.
I've got an existing metadata.db, and app.db.  If I let the latest version install with no app.db I do get a login page.  But as soon as I give it the metadata.db then the page just never loads.

Is it indexing or something?
I can't see any logs updating, either container logs or the calibre-web.log while all this is occuring.

### Expected Behavior

Page should respond.

### Steps To Reproduce

Starting blank container with existing metadata.db

### Environment

```markdown
- OS: Linux fosco 5.15.107-2-pve #1 SMP PVE 5.15.107-2 (2023-05-10T09:10Z) x86_64 x86_64 x86_64 GNU/Linux
Debian LXC Container

- How docker service was installed:
Docker version 24.0.2, build cb74dfc
Apt I think.

Docker Compose 
Docker Compose version v2.19.0
```

### CPU architecture

x86-64

### Docker creation

```bash
calibreweb:
    container_name: calibreweb
    image: lscr.io/linuxserver/calibre-web:latest
    restart: always
    mem_limit: 200m
    environment:
      - TZ=Pacific/Auckland
      - PUID=1000
      - PGID=998
      - DOCKER_MODS=linuxserver/mods:universal-calibre
    security_opt:
      - seccomp=unconfined
    env_file:
      - .env
    healthcheck:
      # I tried adding '&& exit 1',  '|| exit `' it doesn't work.
      test: bash -c "test  -f  /books/metadata.db && exit 0 || exit 1"
      interval: 5m
      timeout: 30s
      retries: 20
    networks:
      - media
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /mnt/omv-media/books/Calibre-Library:/books
      - /hdd/docker-data/media/calibre/:/config
    ports:
      - "8087:8083"
```
```


### Container logs

```bash
[mod-init] Attempting to run Docker Modification Logic
[mod-init] Adding linuxserver/mods:universal-calibre to container
[mod-init] Downloading linuxserver/mods:universal-calibre from lscr.io
[mod-init] Installing linuxserver/mods:universal-calibre
[mod-init] linuxserver/mods:universal-calibre applied to container
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    998
───────────────────────────────────────

**** Adding calibre dependencies to package install list ****
[mod-init] **** Installing all mod packages ****
Get:1 http://archive.ubuntu.com/ubuntu jammy InRelease [270 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Get:4 http://archive.ubuntu.com/ubuntu jammy/main Sources [1,668 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy/multiverse Sources [361 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy/restricted Sources [28.2 kB]
Get:7 http://archive.ubuntu.com/ubuntu jammy/universe Sources [22.0 MB]
Get:8 http://archive.ubuntu.com/ubuntu jammy/restricted amd64 Packages [164 kB]
Get:9 http://archive.ubuntu.com/ubuntu jammy/main amd64 Packages [1,792 kB]
Get:10 http://archive.ubuntu.com/ubuntu jammy/universe amd64 Packages [17.5 MB]
Get:11 http://archive.ubuntu.com/ubuntu jammy/multiverse amd64 Packages [266 kB]
Get:12 http://archive.ubuntu.com/ubuntu jammy-updates/multiverse Sources [21.0 kB]
Get:13 http://archive.ubuntu.com/ubuntu jammy-updates/restricted Sources [56.0 kB]
Get:14 http://archive.ubuntu.com/ubuntu jammy-updates/main Sources [530 kB]
Get:15 http://archive.ubuntu.com/ubuntu jammy-updates/universe Sources [342 kB]
Get:16 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [1,110 kB]
Get:17 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,236 kB]
Get:18 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [876 kB]
Get:19 http://archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [49.8 kB]
Get:20 http://archive.ubuntu.com/ubuntu jammy-security/main Sources [267 kB]
Get:21 http://archive.ubuntu.com/ubuntu jammy-security/universe Sources [199 kB]
Get:22 http://archive.ubuntu.com/ubuntu jammy-security/restricted Sources [53.2 kB]
Get:23 http://archive.ubuntu.com/ubuntu jammy-security/multiverse Sources [11.3 kB]
Get:24 http://archive.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [862 kB]
Get:25 http://archive.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [44.0 kB]
Get:26 http://archive.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [979 kB]
Get:27 http://archive.ubuntu.com/ubuntu jammy-security/main amd64 Packages [840 kB]
Fetched 51.7 MB in 11s (4,857 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libdrm-amdgpu1 libdrm-common libdrm-intel1 libdrm-nouveau2 libdrm-radeon1
  libdrm2 libedit2 libegl-mesa0 libelf1 libgbm1 libgl1 libgl1-mesa-dri
  libglapi-mesa libglvnd0 libglx-mesa0 libglx0 libllvm15 libpciaccess0
  libsensors-config libsensors5 libwayland-client0 libwayland-server0
  libx11-xcb1 libxcb-dri2-0 libxcb-dri3-0 libxcb-glx0 libxcb-present0
  libxcb-randr0 libxcb-shm0 libxcb-sync1 libxcb-xfixes0 libxfixes3
  libxshmfence1 libxxf86vm1 xkb-data
Suggested packages:
  pciutils lm-sensors
Recommended packages:
  libgl1-amber-dri
The following NEW packages will be installed:
  libdrm-amdgpu1 libdrm-common libdrm-intel1 libdrm-nouveau2 libdrm-radeon1
  libdrm2 libedit2 libegl-mesa0 libegl1 libelf1 libgbm1 libgl1 libgl1-mesa-dri
  libgl1-mesa-glx libglapi-mesa libglvnd0 libglx-mesa0 libglx0 libllvm15
  libopengl0 libpciaccess0 libsensors-config libsensors5 libwayland-client0
  libwayland-server0 libx11-xcb1 libxcb-dri2-0 libxcb-dri3-0 libxcb-glx0
  libxcb-present0 libxcb-randr0 libxcb-shm0 libxcb-sync1 libxcb-xfixes0
  libxdamage1 libxfixes3 libxkbcommon0 libxshmfence1 libxxf86vm1 xkb-data
  xz-utils
0 upgraded, 41 newly installed, 0 to remove and 3 not upgraded.
Need to get 35.4 MB of archives.
After this operation, 158 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 libelf1 amd64 0.186-1build1 [51.0 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/main amd64 xkb-data all 2.33-1 [394 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libdrm-common all 2.4.113-2~ubuntu0.22.04.1 [5,450 B]
Get:4 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libdrm2 amd64 2.4.113-2~ubuntu0.22.04.1 [38.1 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy/main amd64 libedit2 amd64 3.1-20210910-1build1 [96.8 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy/main amd64 xz-utils amd64 5.2.5-2ubuntu1 [84.8 kB]
Get:7 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libdrm-amdgpu1 amd64 2.4.113-2~ubuntu0.22.04.1 [19.9 kB]
Get:8 http://archive.ubuntu.com/ubuntu jammy/main amd64 libpciaccess0 amd64 0.16-3 [19.1 kB]
Get:9 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libdrm-intel1 amd64 2.4.113-2~ubuntu0.22.04.1 [66.7 kB]
Get:10 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libdrm-nouveau2 amd64 2.4.113-2~ubuntu0.22.04.1 [17.5 kB]
Get:11 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libdrm-radeon1 amd64 2.4.113-2~ubuntu0.22.04.1 [21.6 kB]
Get:12 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libwayland-server0 amd64 1.20.0-1ubuntu0.1 [34.3 kB]
Get:13 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgbm1 amd64 23.0.4-0ubuntu1~22.04.1 [33.1 kB]
Get:14 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libglapi-mesa amd64 23.0.4-0ubuntu1~22.04.1 [40.1 kB]
Get:15 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libwayland-client0 amd64 1.20.0-1ubuntu0.1 [25.9 kB]
Get:16 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libx11-xcb1 amd64 2:1.7.5-1ubuntu0.2 [7,800 B]
Get:17 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcb-dri2-0 amd64 1.14-3ubuntu3 [7,206 B]
Get:18 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcb-dri3-0 amd64 1.14-3ubuntu3 [6,968 B]
Get:19 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcb-present0 amd64 1.14-3ubuntu3 [5,734 B]
Get:20 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcb-randr0 amd64 1.14-3ubuntu3 [18.3 kB]
Get:21 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcb-sync1 amd64 1.14-3ubuntu3 [9,416 B]
Get:22 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcb-xfixes0 amd64 1.14-3ubuntu3 [9,996 B]
Get:23 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxshmfence1 amd64 1.3-1build4 [5,394 B]
Get:24 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libegl-mesa0 amd64 23.0.4-0ubuntu1~22.04.1 [117 kB]
Get:25 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libllvm15 amd64 1:15.0.7-0ubuntu0.22.04.3 [25.4 MB]
Get:26 http://archive.ubuntu.com/ubuntu jammy/main amd64 libsensors-config all 1:3.6.0-7ubuntu1 [5,274 B]
Get:27 http://archive.ubuntu.com/ubuntu jammy/main amd64 libsensors5 amd64 1:3.6.0-7ubuntu1 [26.3 kB]
Get:28 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgl1-mesa-dri amd64 23.0.4-0ubuntu1~22.04.1 [8,182 kB]
Get:29 http://archive.ubuntu.com/ubuntu jammy/main amd64 libglvnd0 amd64 1.4.0-1 [73.6 kB]
Get:30 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcb-glx0 amd64 1.14-3ubuntu3 [25.9 kB]
Get:31 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcb-shm0 amd64 1.14-3ubuntu3 [5,780 B]
Get:32 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxfixes3 amd64 1:6.0.0-1 [11.7 kB]
Get:33 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxxf86vm1 amd64 1:1.1.4-1build3 [10.4 kB]
Get:34 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libglx-mesa0 amd64 23.0.4-0ubuntu1~22.04.1 [158 kB]
Get:35 http://archive.ubuntu.com/ubuntu jammy/main amd64 libglx0 amd64 1.4.0-1 [41.0 kB]
Get:36 http://archive.ubuntu.com/ubuntu jammy/main amd64 libgl1 amd64 1.4.0-1 [110 kB]
Get:37 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 libgl1-mesa-glx amd64 23.0.4-0ubuntu1~22.04.1 [5,584 B]
Get:38 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxdamage1 amd64 1:1.1.5-2build2 [7,154 B]
Get:39 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxkbcommon0 amd64 1.4.0-1 [125 kB]
Get:40 http://archive.ubuntu.com/ubuntu jammy/main amd64 libegl1 amd64 1.4.0-1 [28.6 kB]
Get:41 http://archive.ubuntu.com/ubuntu jammy/main amd64 libopengl0 amd64 1.4.0-1 [36.5 kB]
Fetched 35.4 MB in 6s (5,455 kB/s)
Selecting previously unselected package libelf1:amd64.
(Reading database ... 12538 files and directories currently installed.)
Preparing to unpack .../00-libelf1_0.186-1build1_amd64.deb ...
Unpacking libelf1:amd64 (0.186-1build1) ...
Selecting previously unselected package xkb-data.
Preparing to unpack .../01-xkb-data_2.33-1_all.deb ...
Unpacking xkb-data (2.33-1) ...
Selecting previously unselected package libdrm-common.
Preparing to unpack .../02-libdrm-common_2.4.113-2~ubuntu0.22.04.1_all.deb ...
Unpacking libdrm-common (2.4.113-2~ubuntu0.22.04.1) ...
Selecting previously unselected package libdrm2:amd64.
Preparing to unpack .../03-libdrm2_2.4.113-2~ubuntu0.22.04.1_amd64.deb ...
Unpacking libdrm2:amd64 (2.4.113-2~ubuntu0.22.04.1) ...
Selecting previously unselected package libedit2:amd64.
Preparing to unpack .../04-libedit2_3.1-20210910-1build1_amd64.deb ...
Unpacking libedit2:amd64 (3.1-20210910-1build1) ...
Selecting previously unselected package xz-utils.
Preparing to unpack .../05-xz-utils_5.2.5-2ubuntu1_amd64.deb ...
Unpacking xz-utils (5.2.5-2ubuntu1) ...
Selecting previously unselected package libdrm-amdgpu1:amd64.
Preparing to unpack .../06-libdrm-amdgpu1_2.4.113-2~ubuntu0.22.04.1_amd64.deb ...
Unpacking libdrm-amdgpu1:amd64 (2.4.113-2~ubuntu0.22.04.1) ...
Selecting previously unselected package libpciaccess0:amd64.
Preparing to unpack .../07-libpciaccess0_0.16-3_amd64.deb ...
Unpacking libpciaccess0:amd64 (0.16-3) ...
Selecting previously unselected package libdrm-intel1:amd64.
Preparing to unpack .../08-libdrm-intel1_2.4.113-2~ubuntu0.22.04.1_amd64.deb ...
Unpacking libdrm-intel1:amd64 (2.4.113-2~ubuntu0.22.04.1) ...
Selecting previously unselected package libdrm-nouveau2:amd64.
Preparing to unpack .../09-libdrm-nouveau2_2.4.113-2~ubuntu0.22.04.1_amd64.deb ...
Unpacking libdrm-nouveau2:amd64 (2.4.113-2~ubuntu0.22.04.1) ...
Selecting previously unselected package libdrm-radeon1:amd64.
Preparing to unpack .../10-libdrm-radeon1_2.4.113-2~ubuntu0.22.04.1_amd64.deb ...
Unpacking libdrm-radeon1:amd64 (2.4.113-2~ubuntu0.22.04.1) ...
Selecting previously unselected package libwayland-server0:amd64.
Preparing to unpack .../11-libwayland-server0_1.20.0-1ubuntu0.1_amd64.deb ...
Unpacking libwayland-server0:amd64 (1.20.0-1ubuntu0.1) ...
Selecting previously unselected package libgbm1:amd64.
Preparing to unpack .../12-libgbm1_23.0.4-0ubuntu1~22.04.1_amd64.deb ...
Unpacking libgbm1:amd64 (23.0.4-0ubuntu1~22.04.1) ...
Selecting previously unselected package libglapi-mesa:amd64.
Preparing to unpack .../13-libglapi-mesa_23.0.4-0ubuntu1~22.04.1_amd64.deb ...
Unpacking libglapi-mesa:amd64 (23.0.4-0ubuntu1~22.04.1) ...
Selecting previously unselected package libwayland-client0:amd64.
Preparing to unpack .../14-libwayland-client0_1.20.0-1ubuntu0.1_amd64.deb ...
Unpacking libwayland-client0:amd64 (1.20.0-1ubuntu0.1) ...
Selecting previously unselected package libx11-xcb1:amd64.
Preparing to unpack .../15-libx11-xcb1_2%3a1.7.5-1ubuntu0.2_amd64.deb ...
Unpacking libx11-xcb1:amd64 (2:1.7.5-1ubuntu0.2) ...
Selecting previously unselected package libxcb-dri2-0:amd64.
Preparing to unpack .../16-libxcb-dri2-0_1.14-3ubuntu3_amd64.deb ...
Unpacking libxcb-dri2-0:amd64 (1.14-3ubuntu3) ...
Selecting previously unselected package libxcb-dri3-0:amd64.
Preparing to unpack .../17-libxcb-dri3-0_1.14-3ubuntu3_amd64.deb ...
Unpacking libxcb-dri3-0:amd64 (1.14-3ubuntu3) ...
Selecting previously unselected package libxcb-present0:amd64.
Preparing to unpack .../18-libxcb-present0_1.14-3ubuntu3_amd64.deb ...
Unpacking libxcb-present0:amd64 (1.14-3ubuntu3) ...
Selecting previously unselected package libxcb-randr0:amd64.
Preparing to unpack .../19-libxcb-randr0_1.14-3ubuntu3_amd64.deb ...
Unpacking libxcb-randr0:amd64 (1.14-3ubuntu3) ...
Selecting previously unselected package libxcb-sync1:amd64.
Preparing to unpack .../20-libxcb-sync1_1.14-3ubuntu3_amd64.deb ...
Unpacking libxcb-sync1:amd64 (1.14-3ubuntu3) ...
Selecting previously unselected package libxcb-xfixes0:amd64.
Preparing to unpack .../21-libxcb-xfixes0_1.14-3ubuntu3_amd64.deb ...
Unpacking libxcb-xfixes0:amd64 (1.14-3ubuntu3) ...
Selecting previously unselected package libxshmfence1:amd64.
Preparing to unpack .../22-libxshmfence1_1.3-1build4_amd64.deb ...
Unpacking libxshmfence1:amd64 (1.3-1build4) ...
Selecting previously unselected package libegl-mesa0:amd64.
Preparing to unpack .../23-libegl-mesa0_23.0.4-0ubuntu1~22.04.1_amd64.deb ...
Unpacking libegl-mesa0:amd64 (23.0.4-0ubuntu1~22.04.1) ...
Selecting previously unselected package libllvm15:amd64.
Preparing to unpack .../24-libllvm15_1%3a15.0.7-0ubuntu0.22.04.3_amd64.deb ...
Unpacking libllvm15:amd64 (1:15.0.7-0ubuntu0.22.04.3) ...
Selecting previously unselected package libsensors-config.
Preparing to unpack .../25-libsensors-config_1%3a3.6.0-7ubuntu1_all.deb ...
Unpacking libsensors-config (1:3.6.0-7ubuntu1) ...
Selecting previously unselected package libsensors5:amd64.
Preparing to unpack .../26-libsensors5_1%3a3.6.0-7ubuntu1_amd64.deb ...
Unpacking libsensors5:amd64 (1:3.6.0-7ubuntu1) ...
Selecting previously unselected package libgl1-mesa-dri:amd64.
Preparing to unpack .../27-libgl1-mesa-dri_23.0.4-0ubuntu1~22.04.1_amd64.deb ...
Unpacking libgl1-mesa-dri:amd64 (23.0.4-0ubuntu1~22.04.1) ...
Selecting previously unselected package libglvnd0:amd64.
Preparing to unpack .../28-libglvnd0_1.4.0-1_amd64.deb ...
Unpacking libglvnd0:amd64 (1.4.0-1) ...
Selecting previously unselected package libxcb-glx0:amd64.
Preparing to unpack .../29-libxcb-glx0_1.14-3ubuntu3_amd64.deb ...
Unpacking libxcb-glx0:amd64 (1.14-3ubuntu3) ...
Selecting previously unselected package libxcb-shm0:amd64.
Preparing to unpack .../30-libxcb-shm0_1.14-3ubuntu3_amd64.deb ...
Unpacking libxcb-shm0:amd64 (1.14-3ubuntu3) ...
Selecting previously unselected package libxfixes3:amd64.
Preparing to unpack .../31-libxfixes3_1%3a6.0.0-1_amd64.deb ...
Unpacking libxfixes3:amd64 (1:6.0.0-1) ...
Selecting previously unselected package libxxf86vm1:amd64.
Preparing to unpack .../32-libxxf86vm1_1%3a1.1.4-1build3_amd64.deb ...
Unpacking libxxf86vm1:amd64 (1:1.1.4-1build3) ...
Selecting previously unselected package libglx-mesa0:amd64.
Preparing to unpack .../33-libglx-mesa0_23.0.4-0ubuntu1~22.04.1_amd64.deb ...
Unpacking libglx-mesa0:amd64 (23.0.4-0ubuntu1~22.04.1) ...
Selecting previously unselected package libglx0:amd64.
Preparing to unpack .../34-libglx0_1.4.0-1_amd64.deb ...
Unpacking libglx0:amd64 (1.4.0-1) ...
Selecting previously unselected package libgl1:amd64.
Preparing to unpack .../35-libgl1_1.4.0-1_amd64.deb ...
Unpacking libgl1:amd64 (1.4.0-1) ...
Selecting previously unselected package libgl1-mesa-glx:amd64.
Preparing to unpack .../36-libgl1-mesa-glx_23.0.4-0ubuntu1~22.04.1_amd64.deb ...
Unpacking libgl1-mesa-glx:amd64 (23.0.4-0ubuntu1~22.04.1) ...
Selecting previously unselected package libxdamage1:amd64.
Preparing to unpack .../37-libxdamage1_1%3a1.1.5-2build2_amd64.deb ...
Unpacking libxdamage1:amd64 (1:1.1.5-2build2) ...
Selecting previously unselected package libxkbcommon0:amd64.
Preparing to unpack .../38-libxkbcommon0_1.4.0-1_amd64.deb ...
Unpacking libxkbcommon0:amd64 (1.4.0-1) ...
Selecting previously unselected package libegl1:amd64.
Preparing to unpack .../39-libegl1_1.4.0-1_amd64.deb ...
Unpacking libegl1:amd64 (1.4.0-1) ...
Selecting previously unselected package libopengl0:amd64.
Preparing to unpack .../40-libopengl0_1.4.0-1_amd64.deb ...
Unpacking libopengl0:amd64 (1.4.0-1) ...
Setting up libxcb-dri3-0:amd64 (1.14-3ubuntu3) ...
Setting up libwayland-server0:amd64 (1.20.0-1ubuntu0.1) ...
Setting up libx11-xcb1:amd64 (2:1.7.5-1ubuntu0.2) ...
Setting up libpciaccess0:amd64 (0.16-3) ...
Setting up libxdamage1:amd64 (1:1.1.5-2build2) ...
Setting up libxcb-xfixes0:amd64 (1.14-3ubuntu3) ...
Setting up libglvnd0:amd64 (1.4.0-1) ...
Setting up libxcb-glx0:amd64 (1.14-3ubuntu3) ...
Setting up libedit2:amd64 (3.1-20210910-1build1) ...
Setting up libsensors-config (1:3.6.0-7ubuntu1) ...
Setting up xkb-data (2.33-1) ...
Setting up libxcb-shm0:amd64 (1.14-3ubuntu3) ...
Setting up libopengl0:amd64 (1.4.0-1) ...
Setting up libxxf86vm1:amd64 (1:1.1.4-1build3) ...
Setting up libxcb-present0:amd64 (1.14-3ubuntu3) ...
Setting up libxfixes3:amd64 (1:6.0.0-1) ...
Setting up libxcb-sync1:amd64 (1.14-3ubuntu3) ...
Setting up xz-utils (5.2.5-2ubuntu1) ...
update-alternatives: using /usr/bin/xz to provide /usr/bin/lzma (lzma) in auto mode
update-alternatives: warning: skip creation of /usr/share/man/man1/lzma.1.gz because associated file /usr/share/man/man1/xz.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/unlzma.1.gz because associated file /usr/share/man/man1/unxz.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzcat.1.gz because associated file /usr/share/man/man1/xzcat.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzmore.1.gz because associated file /usr/share/man/man1/xzmore.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzless.1.gz because associated file /usr/share/man/man1/xzless.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzdiff.1.gz because associated file /usr/share/man/man1/xzdiff.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzcmp.1.gz because associated file /usr/share/man/man1/xzcmp.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzgrep.1.gz because associated file /usr/share/man/man1/xzgrep.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzegrep.1.gz because associated file /usr/share/man/man1/xzegrep.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzfgrep.1.gz because associated file /usr/share/man/man1/xzfgrep.1.gz (of link group lzma) doesn't exist
Setting up libsensors5:amd64 (1:3.6.0-7ubuntu1) ...
Setting up libglapi-mesa:amd64 (23.0.4-0ubuntu1~22.04.1) ...
Setting up libxcb-dri2-0:amd64 (1.14-3ubuntu3) ...
Setting up libxshmfence1:amd64 (1.3-1build4) ...
Setting up libxcb-randr0:amd64 (1.14-3ubuntu3) ...
Setting up libllvm15:amd64 (1:15.0.7-0ubuntu0.22.04.3) ...
Setting up libdrm-common (2.4.113-2~ubuntu0.22.04.1) ...
Setting up libelf1:amd64 (0.186-1build1) ...
Setting up libxkbcommon0:amd64 (1.4.0-1) ...
Setting up libwayland-client0:amd64 (1.20.0-1ubuntu0.1) ...
Setting up libdrm2:amd64 (2.4.113-2~ubuntu0.22.04.1) ...
Setting up libdrm-amdgpu1:amd64 (2.4.113-2~ubuntu0.22.04.1) ...
Setting up libdrm-nouveau2:amd64 (2.4.113-2~ubuntu0.22.04.1) ...
Setting up libgbm1:amd64 (23.0.4-0ubuntu1~22.04.1) ...
Setting up libdrm-radeon1:amd64 (2.4.113-2~ubuntu0.22.04.1) ...
Setting up libdrm-intel1:amd64 (2.4.113-2~ubuntu0.22.04.1) ...
Setting up libgl1-mesa-dri:amd64 (23.0.4-0ubuntu1~22.04.1) ...
Setting up libegl-mesa0:amd64 (23.0.4-0ubuntu1~22.04.1) ...
Setting up libegl1:amd64 (1.4.0-1) ...
Setting up libglx-mesa0:amd64 (23.0.4-0ubuntu1~22.04.1) ...
Setting up libglx0:amd64 (1.4.0-1) ...
Setting up libgl1:amd64 (1.4.0-1) ...
Setting up libgl1-mesa-glx:amd64 (23.0.4-0ubuntu1~22.04.1) ...
Processing triggers for libc-bin (2.35-0ubuntu3.1) ...
**** Installing/updating calibre ****
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  130M  100  130M    0     0  18.8M      0  0:00:06  0:00:06 --:--:-- 22.5M
Creating symlinks...
        Symlinking /app/calibre/ebook-device to /usr/bin/ebook-device
        Symlinking /app/calibre/ebook-meta to /usr/bin/ebook-meta
        Symlinking /app/calibre/ebook-convert to /usr/bin/ebook-convert
        Symlinking /app/calibre/ebook-polish to /usr/bin/ebook-polish
        Symlinking /app/calibre/markdown-calibre to /usr/bin/markdown-calibre
        Symlinking /app/calibre/web2disk to /usr/bin/web2disk
        Symlinking /app/calibre/calibre-server to /usr/bin/calibre-server
        Symlinking /app/calibre/lrf2lrs to /usr/bin/lrf2lrs
        Symlinking /app/calibre/lrs2lrf to /usr/bin/lrs2lrf
        Symlinking /app/calibre/calibre-debug to /usr/bin/calibre-debug
        Symlinking /app/calibre/calibredb to /usr/bin/calibredb
        Symlinking /app/calibre/calibre-parallel to /usr/bin/calibre-parallel
        Symlinking /app/calibre/calibre-customize to /usr/bin/calibre-customize
        Symlinking /app/calibre/fetch-ebook-metadata to /usr/bin/fetch-ebook-metadata
        Symlinking /app/calibre/calibre-smtp to /usr/bin/calibre-smtp
        Symlinking /app/calibre/calibre to /usr/bin/calibre
        Symlinking /app/calibre/lrfviewer to /usr/bin/lrfviewer
        Symlinking /app/calibre/ebook-viewer to /usr/bin/ebook-viewer
        Symlinking /app/calibre/ebook-edit to /usr/bin/ebook-edit
Setting up command-line completion...
Installing zsh completion to: /usr/share/zsh/vendor-completions/_calibre
Failed to find directory to install bash completions, using default.
Installing bash completion to: /usr/share/bash-completion/completions/
Setting up desktop integration...

____________________ WARNING ____________________
Setting up desktop integration failed with error:
__________________________________________________


        Traceback (most recent call last):
          File "calibre/linux.py", line 858, in setup_desktop_integration
          File "calibre/linux.py", line 880, in do_setup_desktop_integration
          File "calibre/linux.py", line 911, in install_xdg_junk
          File "calibre/linux.py", line 896, in install_icons
          File "calibre/linux.py", line 890, in install_single_icon
          File "subprocess.py", line 364, in check_call
          File "subprocess.py", line 345, in call
          File "subprocess.py", line 966, in __init__
          File "subprocess.py", line 1842, in _execute_child
        FileNotFoundError: [Errno 2] No such file or directory: 'xdg-icon-resource'

Creating un-installer: /usr/bin/calibre-uninstall


There were 1 warnings

* Setting up desktop integration failed with error:

[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

Calibre-web.log
```
[2023-08-12 16:24:48,887]  WARN {cps.config_sql:350} Log path None not valid, falling back to default
[2023-08-12 16:24:48,972]  WARN {cps.config_sql:385} invalidating configuration
[2023-08-12 16:24:49,028]  INFO {cps:176} Starting Calibre Web...
[2023-08-12 16:24:49,728]  WARN {py.warnings:109} /usr/local/lib/python3.10/dist-packages/flask_limiter/extension.py:293: UserWarning: Using the in-memory storage for tracking rate limits as no storage was explicitly specified. This is not recommended for production use. See: https://flask-limiter.readthedocs.io#configuring-a-storage-backend for documentation about configuring the storage backend.
  warnings.warn(

[2023-08-12 16:24:51,452]  INFO {apscheduler.scheduler:171} Scheduler started
[2023-08-12 16:24:51,453]  INFO {apscheduler.scheduler:885} Added job "end scheduled task" to job store "default"
[2023-08-12 16:24:51,789]  INFO {cps.ub:898} github Blueprint Created
[2023-08-12 16:24:51,881]  INFO {cps.ub:898} google Blueprint Created
[2023-08-12 16:24:53,934]  INFO {cps.server:207} Starting Gevent server on [::]:8083
```
```

**Comment by drizuid** [comment]
few things here
1) the proxmox devs do not support or recommend running docker in an LXC, they suggest using a vm. If the creators of what you use don't support it, we surely do not either.
2) there are a lot of bugs in your docker version <https://docs.docker.com/engine/release-notes/24.0/> but this may not be relevant at all
3) it SOUNDS like you have a db issue, i would suggest testing with calibre or perhaps calibre-web's other binaries to rule out corruption.

all that said, we do not support your setup and cannot assist further.

**Comment by BartAgterbosch** [comment]
Same here, for some reason it seems that upon creation (and I most definitely did use the template as suggested) there is no metadata.db created, which doesn't seem to be isolated to this container, because well, here, https://github.com/janeczku/calibre-web/issues/1828
However it seems like they have fixed it in later versions in the official calibre-web repo, and they added an empty metadata.db database about 8 months ago, could it be that that is missing here?

**Comment by psyciknz** [comment]
Not sure, biggest issue, is very little debug logging.  It just doesn't stay running, so you're just guessing reasons.

**Comment by BartAgterbosch** [comment]
Well I just tested with the skeleton metadata.db from the official repo and it seems to work, except ofc that database is empty, I feel like I'm either missing something or a metadata.db is supposed to be generated upon container creation and/or startup, which it doesn't, the file doesn't exist nor can it be generated from the webui by the looks of it.
From the logs it seems like it doesn't throw any errors anymore once I put the empty metadata.db file in there, however it doesn't seem to actually update the metadata after that either, I wonder if it has enough permissions to see the files, though I think user 1000 should have those rights

**Comment by aptalca** [comment]
Calibre-web requires an existing calibre database. This is made clear by both the upstream project and our readme. There is no auto generation of calibre db. Upstream project provides an empty db for you to manually copy if needed, to get you started.

These last few comments have nothing to do with the original post.
