### ISSUE TITLE
[BUG] Won't start with latest version, flask error

### ISSUE THREAD

**Issue by yieldhog** [linuxserver/docker-calibre-web#275]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Container web interface won't startup

### Steps To Reproduce

1. Docker container 0.6.20 pulled on 8-Oct-23
2. Start container

### Environment

```markdown
- OS: Synology
- How docker service was installed: Portainer
```

### CPU architecture

x86-64

### Docker creation

```bash
NA, default
```

### Container logs

```bash
from cps.main import main
  File "/app/calibre-web/cps/__init__.py", line 28, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "/app/calibre-web/cps.py", line 28, in <module>
    from cps.main import main
  File "/app/calibre-web/cps/__init__.py", line 28, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "/app/calibre-web/cps.py", line 28, in <module>
    from cps.main import main
  File "/app/calibre-web/cps/__init__.py", line 28, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "/app/calibre-web/cps.py", line 28, in <module>
    from cps.main import main
  File "/app/calibre-web/cps/__init__.py", line 28, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "/app/calibre-web/cps.py", line 28, in <module>
    from cps.main import main
  File "/app/calibre-web/cps/__init__.py", line 28, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "/app/calibre-web/cps.py", line 28, in <module>
    from cps.main import main
  File "/app/calibre-web/cps/__init__.py", line 28, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "/app/calibre-web/cps.py", line 28, in <module>
    from cps.main import main
  File "/app/calibre-web/cps/__init__.py", line 28, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "/app/calibre-web/cps.py", line 28, in <module>
    from cps.main import main
  File "/app/calibre-web/cps/__init__.py", line 28, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "/app/calibre-web/cps.py", line 28, in <module>
    from cps.main import main
  File "/app/calibre-web/cps/__init__.py", line 28, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "/app/calibre-web/cps.py", line 28, in <module>
    from cps.main import main
  File "/app/calibre-web/cps/__init__.py", line 28, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "/app/calibre-web/cps.py", line 28, in <module>
    from cps.main import main
  File "/app/calibre-web/cps/__init__.py", line 28, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "/app/calibre-web/cps.py", line 28, in <module>
    from cps.main import main
  File "/app/calibre-web/cps/__init__.py", line 28, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "/app/calibre-web/cps.py", line 28, in <module>
    from cps.main import main
  File "/app/calibre-web/cps/__init__.py", line 28, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "/app/calibre-web/cps.py", line 28, in <module>
    from cps.main import main
  File "/app/calibre-web/cps/__init__.py", line 28, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "/app/calibre-web/cps.py", line 28, in <module>
    from cps.main import main
  File "/app/calibre-web/cps/__init__.py", line 28, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "/app/calibre-web/cps.py", line 28, in <module>
    from cps.main import main
  File "/app/calibre-web/cps/__init__.py", line 28, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "/app/calibre-web/cps.py", line 28, in <module>
    from cps.main import main
  File "/app/calibre-web/cps/__init__.py", line 28, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'
```

**Comment by aptalca** [comment]
https://info.linuxserver.io/issues/2023-05-22-portainer/

**Comment by yieldhog** [comment]
That appears to have been the issue -- updated w/ Portainer and it broke. I removed the container, re-installed w/ Container Manager (Synology) and its back up and running, thank you

**Comment by nguyenhung** [comment]
> That appears to have been the issue -- updated w/ Portainer and it broke. I removed the container, re-installed w/ Container Manager (Synology) and its back up and running, thank you

I fixed it by editing the PATH to: `/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`

**Comment by dartzon** [comment]
I faced the same issue today after upgrading Calibre-web to the latest version. To fix it, all I had to do was to delete all of the environment variables expect the ones I set manually (tid, gid and tz) as well as all the labels then restart the container!
