### ISSUE TITLE
[BUG] Upload book failed

### ISSUE THREAD

**Issue by zouyonghe** [linuxserver/docker-calibre-web#283]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Upload a book about 26M. But it showed "Error: File size may be too big".

### Expected Behavior

Upload successfully

### Steps To Reproduce

Upload a book using cloudflare tunnel or frp

### Environment

```markdown
- OS:Arch linux
- How docker service was installed:pacman
```

### CPU architecture

x86-64

### Docker creation

```bash
-web.yml

version: "3.8"
services:
  calibre-web:
    image: linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - /root/calibre/config:/config
      - /root/calibre/books:/books
    ports:
      - 24002:8083
    restart: unless-stopped

docker compose -f calibre-web.yml up -d
```

### Container logs

```bash
nothing unusual but in calibre-web's logs, I found below:

[2023-12-14 01:03:08,425] ERROR {cps:1414} Exception on /upload [POST]
Traceback (most recent call last):
  File "/lsiopy/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/lsiopy/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/lsiopy/lib/python3.10/site-packages/flask/app.py", line 1482, in full_dispatch_request
    rv = self.preprocess_request()
  File "/lsiopy/lib/python3.10/site-packages/flask/app.py", line 1974, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/lsiopy/lib/python3.10/site-packages/flask_wtf/csrf.py", line 229, in csrf_protect
    self.protect()
  File "/lsiopy/lib/python3.10/site-packages/flask_wtf/csrf.py", line 261, in protect
    validate_csrf(self._get_csrf_token())
  File "/lsiopy/lib/python3.10/site-packages/flask_wtf/csrf.py", line 234, in _get_csrf_token
    base_token = request.form.get(field_name)
  File "/lsiopy/lib/python3.10/site-packages/werkzeug/utils.py", line 106, in __get__
    value = self.fget(obj)  # type: ignore
  File "/lsiopy/lib/python3.10/site-packages/werkzeug/wrappers/request.py", line 446, in form
    self._load_form_data()
  File "/lsiopy/lib/python3.10/site-packages/flask/wrappers.py", line 114, in _load_form_data
    super()._load_form_data()
  File "/lsiopy/lib/python3.10/site-packages/werkzeug/wrappers/request.py", line 270, in _load_form_data
    data = parser.parse(
  File "/lsiopy/lib/python3.10/site-packages/werkzeug/formparser.py", line 328, in parse
    return parse_func(stream, mimetype, content_length, options)
  File "/lsiopy/lib/python3.10/site-packages/werkzeug/formparser.py", line 357, in _parse_multipart
    form, files = parser.parse(stream, boundary, content_length)
  File "/lsiopy/lib/python3.10/site-packages/werkzeug/formparser.py", line 495, in parse
    for data in _chunk_iter(stream.read, self.buffer_size):
  File "/lsiopy/lib/python3.10/site-packages/werkzeug/formparser.py", line 540, in _chunk_iter
    data = read(size)
  File "/lsiopy/lib/python3.10/site-packages/gevent/pywsgi.py", line 434, in read
    return self._do_read(length)
  File "/lsiopy/lib/python3.10/site-packages/gevent/pywsgi.py", line 234, in _do_read
    raise IOError("unexpected end of file while reading request at position %s" % (self.position,))
OSError: unexpected end of file while reading request at position 29429903
[2023-12-14 01:04:19,522] DEBUG {cps.updater:329} Stable version: {'version': '0.6.21'}
```

**Comment by drizuid** [comment]
upload directly without going through the tunnel, does the issue persist?

**Comment by zouyonghe** [comment]
Thank you for your reply.
Normally, I think it is obviously convenient to upload the books by pulling them from folder directly to the calibre site. But recently, because of my large amounts of books, I just wrote a little shell script to upload my books using scp and docker exec.
Now I wont worry about the upload errors any more.

**Comment by zouyonghe** [comment]
Thank you for your reply.
Normally, I think it is obviously convenient to upload the books by pulling them from folder directly to the calibre site. But recently, because of my large amounts of books, I just wrote a little shell script to upload my books using scp and docker exec.
Now I wont worry about the upload errors any more.

**Comment by drizuid** [comment]
sounds good, if you're happy, im happy :D
