### ISSUE TITLE
[BUG]Caliber database file does not exist.

### ISSUE THREAD

**Issue by QAQ5555** [linuxserver/docker-calibre-web#284]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The initial configuration requires a database file which is not provided in the docker image. You need to obtain it from the original author's github and map it to the container before continuing.
![图片](https://github.com/linuxserver/docker-calibre-web/assets/61168182/a2f778d8-ed4e-4dbc-9f99-6cdb367737cb)

https://github.com/janeczku/calibre-web#quick-start
Step 4 of this link

### Expected Behavior

No need to configure Caliber database file.

### Steps To Reproduce

fresh install

### Environment

```markdown
- OS:
- How docker service was installed:
ubuntu22.04
```

### CPU architecture

x86-64

### Docker creation

```bash
services:
  calibre-web:
    container_name: calibre-web
    image: lscr.io/linuxserver/calibre-web:latest
    restart: unless-stopped
    ports:
      - 8083:8083
    volumes:
      - ./calibre/config:/config
      - ./calibre/books:/books
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
```

### Container logs

```bash
Setting up libxfixes3:amd64 (1:6.0.0-1) ...
Setting up libxcb-sync1:amd64 (1.14-3ubuntu3) ...
Setting up xz-utils (5.2.5-2ubuntu1) ...
update-alternatives: using /usr/bin/xz to provide /usr/bin/lzma (lzma) in auto mode
update-alternatives: warning: skip creation of /usr/share/man/man1/lzma.1.gz because associated file /usr/share/man/man1/xz.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/unlzma.1.gz because associated file /usr/share/man/man1/unxz.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzcat.1.gz because associated file /usr/share/man/man1/xzcat.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzmore.1.gz because associated file /usr/share/man/man1/xzmore.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzless.1.gz because associated file /usr/share/man/man1/xzless.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzdiff.1.gz because associated file /usr/share/man/man1/xzdiff.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzcmp.1.gz because associated file /usr/share/man/man1/xzcmp.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzgrep.1.gz because associated file /usr/share/man/man1/xzgrep.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzegrep.1.gz because associated file /usr/share/man/man1/xzegrep.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzfgrep.1.gz because associated file /usr/share/man/man1/xzfgrep.1.gz (of link group lzma) doesn't exist
Setting up libxrandr2:amd64 (2:1.5.2-1build1) ...
Setting up libsensors5:amd64 (1:3.6.0-7ubuntu1) ...
Setting up libglapi-mesa:amd64 (23.0.4-0ubuntu1~22.04.1) ...
Setting up libxcb-dri2-0:amd64 (1.14-3ubuntu3) ...
Setting up libxshmfence1:amd64 (1.3-1build4) ...
Setting up libxcb-randr0:amd64 (1.14-3ubuntu3) ...
Setting up libllvm15:amd64 (1:15.0.7-0ubuntu0.22.04.3) ...
Setting up libxkbfile1:amd64 (1:1.1.0-1build3) ...
Setting up libdrm-common (2.4.113-2~ubuntu0.22.04.1) ...
Setting up libelf1:amd64 (0.186-1build1) ...
Setting up libxcomposite1:amd64 (1:0.4.5-1build2) ...
Setting up libxkbcommon0:amd64 (1.4.0-1) ...
Setting up libwayland-client0:amd64 (1.20.0-1ubuntu0.1) ...
Setting up libxtst6:amd64 (2:1.2.3-1build4) ...
Setting up libnss3:amd64 (2:3.68.2-0ubuntu1.2) ...
Setting up libdrm2:amd64 (2.4.113-2~ubuntu0.22.04.1) ...
Setting up libdrm-amdgpu1:amd64 (2.4.113-2~ubuntu0.22.04.1) ...
Setting up libdrm-nouveau2:amd64 (2.4.113-2~ubuntu0.22.04.1) ...
Setting up libgbm1:amd64 (23.0.4-0ubuntu1~22.04.1) ...
Setting up libdrm-radeon1:amd64 (2.4.113-2~ubuntu0.22.04.1) ...
Setting up libdrm-intel1:amd64 (2.4.113-2~ubuntu0.22.04.1) ...
Setting up libgl1-mesa-dri:amd64 (23.0.4-0ubuntu1~22.04.1) ...
Setting up libegl-mesa0:amd64 (23.0.4-0ubuntu1~22.04.1) ...
Setting up libegl1:amd64 (1.4.0-1) ...
Setting up libglx-mesa0:amd64 (23.0.4-0ubuntu1~22.04.1) ...
Setting up libglx0:amd64 (1.4.0-1) ...
Setting up libgl1:amd64 (1.4.0-1) ...
Setting up libgl1-mesa-glx:amd64 (23.0.4-0ubuntu1~22.04.1) ...
Processing triggers for libc-bin (2.35-0ubuntu3.1) ...
**** Installing/updating calibre ****
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0

 24  139M   24 34.6M    0     0  17.5M      0  0:00:07  0:00:01  0:00:06 17.5M
 80  139M   80  112M    0     0  37.8M      0  0:00:03  0:00:02  0:00:01 78.4M
100  139M  100  139M    0     0  40.5M      0  0:00:03  0:00:03 --:--:-- 71.5M
Creating symlinks...
	Symlinking /app/calibre/ebook-device to /usr/bin/ebook-device
	Symlinking /app/calibre/ebook-meta to /usr/bin/ebook-meta
	Symlinking /app/calibre/ebook-convert to /usr/bin/ebook-convert
	Symlinking /app/calibre/ebook-polish to /usr/bin/ebook-polish
	Symlinking /app/calibre/markdown-calibre to /usr/bin/markdown-calibre
	Symlinking /app/calibre/web2disk to /usr/bin/web2disk
	Symlinking /app/calibre/calibre-server to /usr/bin/calibre-server
	Symlinking /app/calibre/lrf2lrs to /usr/bin/lrf2lrs
	Symlinking /app/calibre/lrs2lrf to /usr/bin/lrs2lrf
	Symlinking /app/calibre/calibre-debug to /usr/bin/calibre-debug
	Symlinking /app/calibre/calibredb to /usr/bin/calibredb
	Symlinking /app/calibre/calibre-parallel to /usr/bin/calibre-parallel
	Symlinking /app/calibre/calibre-customize to /usr/bin/calibre-customize
	Symlinking /app/calibre/fetch-ebook-metadata to /usr/bin/fetch-ebook-metadata
	Symlinking /app/calibre/calibre-smtp to /usr/bin/calibre-smtp
	Symlinking /app/calibre/calibre to /usr/bin/calibre
	Symlinking /app/calibre/lrfviewer to /usr/bin/lrfviewer
	Symlinking /app/calibre/ebook-viewer to /usr/bin/ebook-viewer
	Symlinking /app/calibre/ebook-edit to /usr/bin/ebook-edit
Setting up command-line completion...
Installing zsh completion to: /usr/share/zsh/vendor-completions/_calibre
Failed to find directory to install bash completions, using default.
Installing bash completion to: /usr/share/bash-completion/completions/
Setting up desktop integration...
____________________ WARNING ____________________
Setting up desktop integration failed with error:
__________________________________________________
	Traceback (most recent call last):
	  File "calibre/linux.py", line 858, in setup_desktop_integration
	  File "calibre/linux.py", line 880, in do_setup_desktop_integration
	  File "calibre/linux.py", line 911, in install_xdg_junk
	  File "calibre/linux.py", line 896, in install_icons
	  File "calibre/linux.py", line 890, in install_single_icon
	  File "subprocess.py", line 408, in check_call
	  File "subprocess.py", line 389, in call
	  File "subprocess.py", line 1026, in __init__
	  File "subprocess.py", line 1950, in _execute_child
	FileNotFoundError: [Errno 2] No such file or directory: 'xdg-icon-resource'
Creating un-installer: /usr/bin/calibre-uninstall
There were 1 warnings
* Setting up desktop integration failed with error:
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

**Comment by j0nnymoe** [comment]
Not a bug. As mentioned in the readme, calibre-web requires an existing calibre database.

**Comment by cassie-nahar** [comment]
Readme does mention requiring an existing calibre database, but as a new user I didn't know how to accomplish that. This deviates from the level of instruction on all the other linuxserver guides. Recommend "fixing" by adding a little more detail to the readme.

**Comment by j0nnymoe** [comment]
It's in the description.
![image](https://github.com/linuxserver/docker-calibre-web/assets/10374553/b6f5bc5d-a734-48d3-82c4-208ad05cc1f8)

**Comment by cassie-nahar** [comment]
> It's in the description. ![image](https://private-user-images.githubusercontent.com/10374553/322156752-b6f5bc5d-a734-48d3-82c4-208ad05cc1f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5NjM0NTUsIm5iZiI6MTcxMjk2MzE1NSwicGF0aCI6Ii8xMDM3NDU1My8zMjIxNTY3NTItYjZmNWJjNWQtYTczNC00OGQzLTgyYzQtMjA4YWQwNWNjMWY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDIzMDU1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyYmY2NDE2NzM0YjcwOGIzYTk4MTJlN2ViMWEwMzlkMmRhNGM3MGU5NWUwZTNlZWYyMDk3ZmU5NTBjMjRmZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HUyazsY2ekwsZw_FWoufHFzwvwdGqGooV-Hh6dqEWdE)

I said that. My comment and recommendation stands.

![Screenshot_20240412_190632_Chrome](https://github.com/linuxserver/docker-calibre-web/assets/8941243/eb9ae99b-5e82-43a2-a5d3-8acd4aa6278c)

**Comment by aptalca** [comment]
We don't develop calibre-web. We develop the docker image. The instructions are for the container. The app requirement is also listed. If you want to know more about what the app is or what it does, we also link to the upstream website/repo.

There is nothing to "fix" as nothing is broken.

**Comment by cassie-nahar** [comment]
The instructions for the container do not currently guide an unfamiliar user through creating a working environment.

True, nothing is *broken* since the user should infer that they need to investigate the documentation of calibre. But multiple users are stating that this is an area where the container documentation could benefit from *improvement*. Dismissing that is unhelpful.

If I have time later I'll try to write up a sentence or two linking to the appropriate sections of the calibre or calibre-web documentation and make a PR.
