### ISSUE TITLE
[BUG] Unable to login with the local admin account

### ISSUE THREAD

**Issue by kabaga** [linuxserver/docker-calibre-web#285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am running the latest version. I am have LDAP enabled for user accounts and using the local account for admin purposes. When I logged in as the local admin, I am getting the "Wrong Username or Password" error. I bashed-in to the container and tried to reset the admin password using this command "python3 cps.py -p /config/app.db -s admin:password", and got a confirmation message "Password for user 'admin' changed".

However, when I tried to login, I am still getting the same error message "Wrong Username or Password".

I am able to login again by rolling back to version 0.6.21-ls248.

### Expected Behavior

I should be able to be able to use the local account to administer the calibre-web. 

### Steps To Reproduce

Make sure enable the LDAP
1. Ugraded to the latest version of the Linuxserver calibre-web container
2. Login as local admin account 
3. Get the error "Wrong Username or Password"

### Environment

```markdown
- OS: Debian 12
- How docker service was installed: Installed using the official Docker instruction for Debian
https://docs.docker.com/engine/install/debian/
```

### CPU architecture

x86-64

### Docker creation

```bash
---
version: "3.1"
services:
  calibre:
    env_file: .env
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=UTC
      - PASSWORD=${PASSWD}
      - CLI_ARGS= #optional
    volumes:
      - ${APPDATA}:/config
      - ${DATA}:/library
      - ${OLDLIB}:/old_library
    ports:
      - ${PORT}:8080
      - ${PORT2}:8081
    restart: "no"

  calibre-web:
    env_file: .env
    image: lscr.io/linuxserver/calibre-web:0.6.21-ls248 
    container_name: calibre-web
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=UTC
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - ${APPDATA2}:/config
      - ${DATA}:/books
    ports:
      - ${PORT3}:8083
    depends_on: 
      - calibre
    restart: "no"
```

### Container logs

```bash
calibre-web    |        Symlinking /app/calibre/lrf2lrs to /usr/bin/lrf2lrs
calibre-web    |        Symlinking /app/calibre/lrs2lrf to /usr/bin/lrs2lrf
calibre-web    |        Symlinking /app/calibre/calibre-debug to /usr/bin/calibre-debug
calibre-web    |        Symlinking /app/calibre/calibredb to /usr/bin/calibredb
calibre-web    |        Symlinking /app/calibre/calibre-parallel to /usr/bin/calibre-parallel
calibre-web    |        Symlinking /app/calibre/calibre-customize to /usr/bin/calibre-customize
calibre-web    |        Symlinking /app/calibre/fetch-ebook-metadata to /usr/bin/fetch-ebook-metadata
calibre-web    |        Symlinking /app/calibre/calibre-smtp to /usr/bin/calibre-smtp
calibre-web    |        Symlinking /app/calibre/calibre to /usr/bin/calibre
calibre-web    |        Symlinking /app/calibre/lrfviewer to /usr/bin/lrfviewer
calibre-web    |        Symlinking /app/calibre/ebook-viewer to /usr/bin/ebook-viewer
calibre-web    |        Symlinking /app/calibre/ebook-edit to /usr/bin/ebook-edit
calibre-web    | Setting up command-line completion...
calibre-web    | Installing zsh completion to: /usr/share/zsh/vendor-completions/_calibre
calibre-web    | Failed to find directory to install bash completions, using default.
calibre-web    | Installing bash completion to: /usr/share/bash-completion/completions/
calibre-web    | Setting up desktop integration...
calibre-web    | 
calibre-web    | ____________________ WARNING ____________________
calibre-web    | Setting up desktop integration failed with error:
calibre-web    | __________________________________________________
calibre-web    | 
calibre-web    | 
calibre-web    |        Traceback (most recent call last):
calibre-web    |          File "calibre/linux.py", line 858, in setup_desktop_integration
calibre-web    |          File "calibre/linux.py", line 880, in do_setup_desktop_integration
calibre-web    |          File "calibre/linux.py", line 911, in install_xdg_junk
calibre-web    |          File "calibre/linux.py", line 896, in install_icons
calibre-web    |          File "calibre/linux.py", line 890, in install_single_icon
calibre-web    |          File "subprocess.py", line 408, in check_call
calibre-web    |          File "subprocess.py", line 389, in call
calibre-web    |          File "subprocess.py", line 1026, in __init__
calibre-web    |          File "subprocess.py", line 1950, in _execute_child
calibre-web    |        FileNotFoundError: [Errno 2] No such file or directory: 'xdg-icon-resource'
calibre-web    | 
calibre-web    | Creating un-installer: /usr/bin/calibre-uninstall
calibre-web    | 
calibre-web    | 
calibre-web    | There were 1 warnings
calibre-web    | 
calibre-web    | * Setting up desktop integration failed with error:
calibre-web    | 
calibre-web    | [custom-init] No custom files found, skipping...
calibre-web    | [ls.io-init] done.
```

**Comment by homerr** [comment]
I'd recommend changing the compose file to not use variables, use fresh directories and try again;

`---
services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD= #optional
      - CLI_ARGS= #optional
    volumes:
      - /path/to/data:/config
    ports:
      - 8080:8080
      - 8181:8181
      - 8081:8081
    restart: unless-stopped`

As the container is working OK I'd recommend coming to Discord for support with setting up.
