### ISSUE TITLE
docker container could not be started

### ISSUE THREAD

**Issue by stefaneliu** [linuxserver/docker-calibre-web#296]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello
I am using synology docker. and the calibre-web container worked well until recent.
It was stopped unexpectedly.
I tried updating to the newest version and did not help.

### Steps To Reproduce

1. installing docker container with docker run or docker-compose.

### Environment

```markdown
- OS:synology dsm
- How docker service was installed:synology itself
```

### CPU architecture

x86-64

### Docker creation

```bash
---
services:
  calibre-web:
    image: linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1024
      - PGID=100
      - TZ=Asia/shanghai
      - DOCKER_MODS=linuxserver/mods:universal-calibre
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1
    volumes:
      - /volume5/docker/calibre-web:/config
      - /volume5/eBooks/Calibre:/books
    ports:
      - 8083:8083
    restart: unless-stopped
```

### Container logs

```bash
[2024-05-31 13:16:23,648]  WARN {cps.config_sql:318} Log path None not valid, falling back to default
[2024-05-31 13:16:26,042]  WARN {cps.config_sql:349} invalidating configuration
[2024-05-31 13:16:28,151]  INFO {cps.ub:851} github Blueprint Created
[2024-05-31 13:16:28,298]  INFO {cps.ub:851} google Blueprint Created
[2024-05-31 13:16:30,606]  WARN {fake_useragent:180} Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.11
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/fake_useragent/utils.py", line 154, in load
    for item in get_browsers(verify_ssl=verify_ssl):
  File "/usr/local/lib/python3.8/dist-packages/fake_useragent/utils.py", line 99, in get_browsers
    html = html.split('<table class="w3-table-all notranslate">')[1]
IndexError: list index out of range
[2024-05-31 13:19:18,640]  INFO {cps.server:272} webserver stop (restart=False)
[2024-05-31 13:22:02,422]  WARN {cps.config_sql:349} invalidating configuration
[2024-05-31 13:22:10,458]  WARN {fake_useragent:180} Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.11
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/fake_useragent/utils.py", line 154, in load
    for item in get_browsers(verify_ssl=verify_ssl):
  File "/usr/local/lib/python3.8/dist-packages/fake_useragent/utils.py", line 99, in get_browsers
    html = html.split('<table class="w3-table-all notranslate">')[1]
IndexError: list index out of range
[2024-05-31 13:36:33,621]  INFO {cps.server:272} webserver stop (restart=False)
[2024-05-31 13:41:02,804]  WARN {cps.config_sql:349} invalidating configuration
[2024-05-31 13:41:05,941]  WARN {fake_useragent:180} Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.11
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/fake_useragent/utils.py", line 154, in load
    for item in get_browsers(verify_ssl=verify_ssl):
  File "/usr/local/lib/python3.8/dist-packages/fake_useragent/utils.py", line 99, in get_browsers
    html = html.split('<table class="w3-table-all notranslate">')[1]
IndexError: list index out of range
```

**Comment by drizuid** [comment]
what's the output of 
`uname -mr && docker version`

did you deploy this container with the docker run above or did you use synology's ui to do so?

is your db in /books or /config?
what is the filesystem of /volume5

**Comment by stefaneliu** [comment]
> what's the output of `uname -mr && docker version`
> 
> did you deploy this container with the docker run above or did you use synology's ui to do so?
> 
> is your db in /books or /config? what is the filesystem of /volume5

uname -mr && docker version
the result is 
```
4.4.302+ x86_64
Client:
 Version:           20.10.23
 API version:       1.41
 Go version:        go1.19.1
 Git commit:        876964a
 Built:             Fri Sep  8 08:19:48 2023
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.23
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.19.1
  Git commit:       5fcb1cf
  Built:            Fri Sep  8 08:18:18 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.6.15
  GitCommit:        b23a389d8c181697302d163356e97dec04eb8d88
 runc:
  Version:          v1.1.4
  GitCommit:        5af893d
 docker-init:
  Version:          0.19.0
  GitCommit:        ed96d00
```

did you deploy this container with the docker run above or did you use synology's ui to do so?
```
i deployed it with docker run and synology ui also. all have this problem.
```
is your db in /books or /config? what is the filesystem of /volume5
```
if you mean my ebook, they are stored in /books. and configuration of calibre-web is in /config.
the file system of /volume5 is Btrfs.
```

Thank you.

**Comment by drizuid** [comment]
> if you mean my ebook, they are stored in /books. and configuration of calibre-web is in /config.

I mean, specifically, the metadata.db

> the file system of /volume5 is Btrfs.

this could be or be part of your problem. What is the output of `docker info | grep 'Storage Driver'`

**Comment by stefaneliu** [comment]
Thank you. after updating docker container to the newest version, the app seems to be operational.
i have been using watchtower to manage docker update for a long time but it seems not working for some images with tag: latest now and i have no idea why. 
never mind, that is another story.
i manually updated sonarr and everything is working well now.
thanks again.
