### ISSUE TITLE
[BUG]Unable to Use certs for SSL on QNAP NAS QTS 5.20.2851

### ISSUE THREAD

**Issue by eiauo** [linuxserver/docker-calibre-web#320]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have successfully installed docker-calibre-web 0.6.23-ls290 Latest on QNAP NAS  QTS 5.20.2851，I can successfully set up the Server Configuration to http.
When use a passphrase protected key and cert file in the in the Server Configuration, the server not responding.

### Expected Behavior

Able to use HTTPS/SSL

### Steps To Reproduce

Use a passphrase protected key and cert file in the in the Server Configuration
Look at calibre-web.log to see error log.

### Environment

```markdown
- OS:qnap TS-453D QTS 5.2.0.2851

Calibre-Web version: 0.6.23-ls290
Browser: Chrome
```

### CPU architecture

x86-64

### Docker creation

```bash
Use Container Station, Create Docker linuxserver/calibre-web:latest.
```

### Container logs

```bash
Repeat error log like this: 
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "/lsiopy/lib/python3.10/site-packages/gevent/baseserver.py", line 34, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/lsiopy/lib/python3.10/site-packages/gevent/pywsgi.py", line 1700, in handle
    handler.handle()
  File "/lsiopy/lib/python3.10/site-packages/gevent/pywsgi.py", line 584, in handle
    self.log_request()
  File "/lsiopy/lib/python3.10/site-packages/gevent/pywsgi.py", line 1016, in log_request
    self.server.log.write(self.format_request() + '\n')
  File "/app/calibre-web/cps/gevent_wsgi.py", line 37, in format_request
    forwarded = self.environ.get('HTTP_X_FORWARDED_FOR', None)
AttributeError: 'NoneType' object has no attribute 'get'
2024-09-16T23:54:48Z <Greenlet at 0x7f0bcb46dee0: _handle_and_close_when_done(<bound method WSGIServer.handle of <WSGIServer at , <bound method StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket [closed] at 0x7f0bcb32dba)> failed with AttributeError

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "/lsiopy/lib/python3.10/site-packages/gevent/baseserver.py", line 34, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/lsiopy/lib/python3.10/site-packages/gevent/pywsgi.py", line 1700, in handle
    handler.handle()
  File "/lsiopy/lib/python3.10/site-packages/gevent/pywsgi.py", line 584, in handle
    self.log_request()
  File "/lsiopy/lib/python3.10/site-packages/gevent/pywsgi.py", line 1016, in log_request
    self.server.log.write(self.format_request() + '\n')
  File "/app/calibre-web/cps/gevent_wsgi.py", line 37, in format_request
    forwarded = self.environ.get('HTTP_X_FORWARDED_FOR', None)
AttributeError: 'NoneType' object has no attribute 'get'
2024-09-17T00:04:18Z <Greenlet at 0x7f0bcb46dee0: _handle_and_close_when_done(<bound method WSGIServer.handle of <WSGIServer at , <bound method StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket [closed] at 0x7f0bcb32dc0)> failed with AttributeError
```

**Comment by drizuid** [comment]
Our recommendation is to put this behind a reverse proxy. We also do not offer support when the container is created with a ui (other than unraid). We support docker run and docker compose, as noted on our container readme.  My suggestion, as this appears to be an application issue, is for you to seek help from the application developer. Closing this as it's out of scope for support.
