### ISSUE TITLE
Can't acces to Edit Basic Configuration 

### ISSUE THREAD

**Issue by 97carmine** [linuxserver/docker-calibre-web#78]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
You should be able to access the page that allows you to edit options such as LDAP authentication or add the path of the ebook converter

## Current Behavior
Show this: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

```
Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/local/lib/python3.6/dist-packages/flask_login/utils.py", line 272, in decorated_view
return func(*args, **kwargs)
File "/app/calibre-web/cps/web.py", line 213, in inner
return f(*args, **kwargs)
File "/app/calibre-web/cps/admin.py", line 143, in configuration
return _configuration_result()
File "/app/calibre-web/cps/admin.py", line 704, in _configuration_result
title=_(u"Basic Configuration"), page="config")
File "/app/calibre-web/cps/web.py", line 281, in render_title_template
*args, **kwargs)
File "/usr/local/lib/python3.6/dist-packages/flask/templating.py", line 140, in render_template
ctx.app,
File "/usr/local/lib/python3.6/dist-packages/flask/templating.py", line 120, in _render
rv = template.render(context)
File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 1090, in render
self.environment.handle_exception()
File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 832, in handle_exception
reraise(*rewrite_traceback_stack(source=source))
File "/usr/local/lib/python3.6/dist-packages/jinja2/_compat.py", line 28, in reraise
raise value.with_traceback(tb)
File "/app/calibre-web/cps/templates/config_edit.html", line 1, in top-level template code
{% extends "layout.html" %}
File "/app/calibre-web/cps/templates/layout.html", line 153, in top-level template code
{% block body %}{% endblock %}
File "/app/calibre-web/cps/templates/config_edit.html", line 300, in block "body"
<a href="{{prov['obtain_link']}}" target="_blank">{{_('Obtain %(provider)s OAuth Credential', provider=prov['provider_name'])}}</a>
File "/usr/local/lib/python3.6/dist-packages/jinja2/ext.py", line 144, in _gettext_alias
return __context.call(__conext.resolve("gettext"), *args, **kwargs)
File "/usr/local/lib/python3.6/dist-packages/jinja2/ext.py", line 156, in gettext
return rv % variables
File "/usr/local/lib/python3.6/dist-packages/markupsafe/__init__.py", line 102, in __mod__
return self.__class__(text_type.__mod__(self, arg))
File "/usr/local/lib/python3.6/dist-packages/markupsafe/__init__.py", line 301, in __getitem__
return _MarkupEscapeHelper(self.obj[item], self.escape)
KeyError: 'proveedor'
```

## Steps to Reproduce

Click on the option _Edit basic configuration_

## Environment
**OS:** Proxmox (Debian)
**CPU architecture:** x86_64
**How docker service was installed:**      

Using the [repository](https://docs.docker.com/engine/install/debian/#install-using-the-repository)

## Command used to create docker container (run/create/compose/screenshot)

```
docker run -d --net downloads --name=calibre-web -e PUID=1000 -e PGID=1000 -e TZ=Europe/Madrid -e DOCKER_MODS=linuxserver/calibre-web:calibre -p 8083:8083 -v calibre-web_data:/config -v /mnt/pve/pCloud/Datos/Biblioteca:/books --restart unless-stopped linuxserver/calibre-web
```

## Docker logs

<details> <summary> Docker logs </summary>

```
[mod-init] Attempting to run Docker Modification Logic
[mod-init] Applying linuxserver/calibre-web:calibre files to container
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 60-calibre-config: executing... 
Creating symlinks...
        Symlinking /app/calibre/calibre-debug to /usr/bin/calibre-debug
        Symlinking /app/calibre/markdown-calibre to /usr/bin/markdown-calibre
        Symlinking /app/calibre/fetch-ebook-metadata to /usr/bin/fetch-ebook-metadata
        Symlinking /app/calibre/lrs2lrf to /usr/bin/lrs2lrf
        Symlinking /app/calibre/ebook-edit to /usr/bin/ebook-edit
        Symlinking /app/calibre/ebook-device to /usr/bin/ebook-device
        Symlinking /app/calibre/calibre-server to /usr/bin/calibre-server
        Symlinking /app/calibre/calibredb to /usr/bin/calibredb
        Symlinking /app/calibre/lrf2lrs to /usr/bin/lrf2lrs
        Symlinking /app/calibre/calibre-smtp to /usr/bin/calibre-smtp
        Symlinking /app/calibre/ebook-convert to /usr/bin/ebook-convert
        Symlinking /app/calibre/web2disk to /usr/bin/web2disk
        Symlinking /app/calibre/ebook-polish to /usr/bin/ebook-polish
        Symlinking /app/calibre/lrfviewer to /usr/bin/lrfviewer
        Symlinking /app/calibre/ebook-viewer to /usr/bin/ebook-viewer
        Symlinking /app/calibre/ebook-meta to /usr/bin/ebook-meta
        Symlinking /app/calibre/calibre to /usr/bin/calibre
        Symlinking /app/calibre/calibre-parallel to /usr/bin/calibre-parallel
        Symlinking /app/calibre/calibre-customize to /usr/bin/calibre-customize
Setting up command-line completion...
Installing zsh completion to: /usr/share/zsh/vendor-completions/_calibre
Failed to find directory to install bash completions, using default.
Installing bash completion to: /usr/share/bash-completion/completions/

____________________ WARNING ____________________
Setting up completion failed with error:
__________________________________________________


        Traceback (most recent call last):
          File "site-packages/calibre/linux.py", line 834, in setup_completion
          File "site-packages/calibre/linux.py", line 576, in write_completion
          File "site-packages/calibre/gui2/__init__.py", line 16, in <module>
        ImportError: cannot import name QApplication

Setting up desktop integration...

____________________ WARNING ____________________
Setting up desktop integration failed with error:
__________________________________________________


        Traceback (most recent call last):
          File "site-packages/calibre/linux.py", line 902, in setup_desktop_integration
          File "site-packages/calibre/linux.py", line 887, in install_icons
          File "site-packages/calibre/linux.py", line 877, in install_single_icon
          File "site-packages/calibre/linux.py", line 1221, in render_img
        ImportError: cannot import name QImage

Creating un-installer: /usr/bin/calibre-uninstall


There were 2 warnings

* Setting up completion failed with error:

* Setting up desktop integration failed with error:


WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Get:1 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:4 http://archive.ubuntu.com/ubuntu bionic/universe Sources [11.5 MB]
Get:5 http://archive.ubuntu.com/ubuntu bionic/main Sources [1,063 kB]
Get:6 http://archive.ubuntu.com/ubuntu bionic/restricted Sources [5,823 B]
Get:7 http://archive.ubuntu.com/ubuntu bionic/multiverse Sources [216 kB]
Get:8 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
Get:9 http://archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [186 kB]
Get:10 http://archive.ubuntu.com/ubuntu bionic/restricted amd64 Packages [13.5 kB]
Get:11 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1,344 kB]
Get:12 http://archive.ubuntu.com/ubuntu bionic-updates/main Sources [407 kB]
Get:13 http://archive.ubuntu.com/ubuntu bionic-updates/universe Sources [369 kB]
Get:14 http://archive.ubuntu.com/ubuntu bionic-updates/restricted Sources [8,209 B]
Get:15 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse Sources [7,156 B]
Get:16 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [67.4 kB]
Get:17 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [19.8 kB]
Get:18 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [1,376 kB]
Get:19 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [1,210 kB]
Get:20 http://archive.ubuntu.com/ubuntu bionic-security/multiverse Sources [3,233 B]
Get:21 http://archive.ubuntu.com/ubuntu bionic-security/universe Sources [215 kB]
Get:22 http://archive.ubuntu.com/ubuntu bionic-security/main Sources [192 kB]
Get:23 http://archive.ubuntu.com/ubuntu bionic-security/restricted Sources [5,868 B]
Get:24 http://archive.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [846 kB]
Get:25 http://archive.ubuntu.com/ubuntu bionic-security/main amd64 Packages [912 kB]
Get:26 http://archive.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [8,507 B]
Get:27 http://archive.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [52.4 kB]
Fetched 31.8 MB in 5s (6,396 kB/s)
Reading package lists...
Building dependency tree...
Reading state information...
9 packages can be upgraded. Run 'apt list --upgradable' to see them.

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libdrm-amdgpu1 libdrm-common libdrm-intel1 libdrm-nouveau2 libdrm-radeon1
  libdrm2 libedit2 libelf1 libgl1 libgl1-mesa-dri libglapi-mesa libglvnd0
  libglx-mesa0 libglx0 libllvm9 libpciaccess0 libsensors4 libx11-xcb1
  libxcb-dri2-0 libxcb-dri3-0 libxcb-glx0 libxcb-present0 libxcb-sync1
  libxdamage1 libxfixes3 libxshmfence1 libxxf86vm1
Suggested packages:
  pciutils lm-sensors
The following NEW packages will be installed:
  libdrm-amdgpu1 libdrm-common libdrm-intel1 libdrm-nouveau2 libdrm-radeon1
  libdrm2 libedit2 libelf1 libgl1 libgl1-mesa-dri libgl1-mesa-glx
  libglapi-mesa libglvnd0 libglx-mesa0 libglx0 libllvm9 libpciaccess0
  libsensors4 libx11-xcb1 libxcb-dri2-0 libxcb-dri3-0 libxcb-glx0
  libxcb-present0 libxcb-sync1 libxdamage1 libxfixes3 libxshmfence1
  libxxf86vm1
0 upgraded, 28 newly installed, 0 to remove and 9 not upgraded.
Need to get 24.3 MB of archives.
After this operation, 311 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic/main amd64 libxxf86vm1 amd64 1:1.1.4-1 [10.6 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libelf1 amd64 0.170-0.4ubuntu0.1 [44.8 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libdrm-common all 2.4.99-1ubuntu1~18.04.2 [5,328 B]
Get:4 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libdrm2 amd64 2.4.99-1ubuntu1~18.04.2 [31.7 kB]
Get:5 http://archive.ubuntu.com/ubuntu bionic/main amd64 libedit2 amd64 3.1-20170329-1 [76.9 kB]
Get:6 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libdrm-amdgpu1 amd64 2.4.99-1ubuntu1~18.04.2 [18.2 kB]
Get:7 http://archive.ubuntu.com/ubuntu bionic/main amd64 libpciaccess0 amd64 0.14-1 [17.9 kB]
Get:8 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libdrm-intel1 amd64 2.4.99-1ubuntu1~18.04.2 [59.9 kB]
Get:9 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libdrm-nouveau2 amd64 2.4.99-1ubuntu1~18.04.2 [16.5 kB]
Get:10 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libdrm-radeon1 amd64 2.4.99-1ubuntu1~18.04.2 [21.7 kB]
Get:11 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libglapi-mesa amd64 19.2.8-0ubuntu0~18.04.3 [26.5 kB]
Get:12 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libllvm9 amd64 1:9-2~ubuntu18.04.2 [14.8 MB]
Get:13 http://archive.ubuntu.com/ubuntu bionic/main amd64 libsensors4 amd64 1:3.4.0-4 [28.8 kB]
Get:14 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libgl1-mesa-dri amd64 19.2.8-0ubuntu0~18.04.3 [8,811 kB]
Get:15 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libglvnd0 amd64 1.0.0-2ubuntu2.3 [47.0 kB]
Get:16 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libx11-xcb1 amd64 2:1.6.4-3ubuntu0.2 [9,376 B]
Get:17 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libxcb-dri2-0 amd64 1.13-2~ubuntu18.04 [6,920 B]
Get:18 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libxcb-dri3-0 amd64 1.13-2~ubuntu18.04 [6,568 B]
Get:19 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libxcb-glx0 amd64 1.13-2~ubuntu18.04 [22.1 kB]
Get:20 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libxcb-present0 amd64 1.13-2~ubuntu18.04 [5,552 B]
Get:21 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libxcb-sync1 amd64 1.13-2~ubuntu18.04 [8,808 B]
Get:22 http://archive.ubuntu.com/ubuntu bionic/main amd64 libxdamage1 amd64 1:1.1.4-3 [6,934 B]
Get:23 http://archive.ubuntu.com/ubuntu bionic/main amd64 libxfixes3 amd64 1:5.0.3-1 [10.8 kB]
Get:24 http://archive.ubuntu.com/ubuntu bionic/main amd64 libxshmfence1 amd64 1.3-1 [5,028 B]
Get:25 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libglx-mesa0 amd64 19.2.8-0ubuntu0~18.04.3 [139 kB]
Get:26 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libglx0 amd64 1.0.0-2ubuntu2.3 [28.1 kB]
Get:27 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libgl1 amd64 1.0.0-2ubuntu2.3 [86.2 kB]
Get:28 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libgl1-mesa-glx amd64 19.2.8-0ubuntu0~18.04.3 [5,528 B]
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76, <> line 28.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7, <> line 28.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: 
Fetched 24.3 MB in 3s (9,607 kB/s)
Selecting previously unselected package libxxf86vm1:amd64.
(Reading database ... 11435 files and directories currently installed.)
Preparing to unpack .../00-libxxf86vm1_1%3a1.1.4-1_amd64.deb ...
Unpacking libxxf86vm1:amd64 (1:1.1.4-1) ...
Selecting previously unselected package libelf1:amd64.
Preparing to unpack .../01-libelf1_0.170-0.4ubuntu0.1_amd64.deb ...
Unpacking libelf1:amd64 (0.170-0.4ubuntu0.1) ...
Selecting previously unselected package libdrm-common.
Preparing to unpack .../02-libdrm-common_2.4.99-1ubuntu1~18.04.2_all.deb ...
Unpacking libdrm-common (2.4.99-1ubuntu1~18.04.2) ...
Selecting previously unselected package libdrm2:amd64.
Preparing to unpack .../03-libdrm2_2.4.99-1ubuntu1~18.04.2_amd64.deb ...
Unpacking libdrm2:amd64 (2.4.99-1ubuntu1~18.04.2) ...
Selecting previously unselected package libedit2:amd64.
Preparing to unpack .../04-libedit2_3.1-20170329-1_amd64.deb ...
Unpacking libedit2:amd64 (3.1-20170329-1) ...
Selecting previously unselected package libdrm-amdgpu1:amd64.
Preparing to unpack .../05-libdrm-amdgpu1_2.4.99-1ubuntu1~18.04.2_amd64.deb ...
Unpacking libdrm-amdgpu1:amd64 (2.4.99-1ubuntu1~18.04.2) ...
Selecting previously unselected package libpciaccess0:amd64.
Preparing to unpack .../06-libpciaccess0_0.14-1_amd64.deb ...
Unpacking libpciaccess0:amd64 (0.14-1) ...
Selecting previously unselected package libdrm-intel1:amd64.
Preparing to unpack .../07-libdrm-intel1_2.4.99-1ubuntu1~18.04.2_amd64.deb ...
Unpacking libdrm-intel1:amd64 (2.4.99-1ubuntu1~18.04.2) ...
Selecting previously unselected package libdrm-nouveau2:amd64.
Preparing to unpack .../08-libdrm-nouveau2_2.4.99-1ubuntu1~18.04.2_amd64.deb ...
Unpacking libdrm-nouveau2:amd64 (2.4.99-1ubuntu1~18.04.2) ...
Selecting previously unselected package libdrm-radeon1:amd64.
Preparing to unpack .../09-libdrm-radeon1_2.4.99-1ubuntu1~18.04.2_amd64.deb ...
Unpacking libdrm-radeon1:amd64 (2.4.99-1ubuntu1~18.04.2) ...
Selecting previously unselected package libglapi-mesa:amd64.
Preparing to unpack .../10-libglapi-mesa_19.2.8-0ubuntu0~18.04.3_amd64.deb ...
Unpacking libglapi-mesa:amd64 (19.2.8-0ubuntu0~18.04.3) ...
Selecting previously unselected package libllvm9:amd64.
Preparing to unpack .../11-libllvm9_1%3a9-2~ubuntu18.04.2_amd64.deb ...
Unpacking libllvm9:amd64 (1:9-2~ubuntu18.04.2) ...
Selecting previously unselected package libsensors4:amd64.
Preparing to unpack .../12-libsensors4_1%3a3.4.0-4_amd64.deb ...
Unpacking libsensors4:amd64 (1:3.4.0-4) ...
Selecting previously unselected package libgl1-mesa-dri:amd64.
Preparing to unpack .../13-libgl1-mesa-dri_19.2.8-0ubuntu0~18.04.3_amd64.deb ...
Unpacking libgl1-mesa-dri:amd64 (19.2.8-0ubuntu0~18.04.3) ...
Selecting previously unselected package libglvnd0:amd64.
Preparing to unpack .../14-libglvnd0_1.0.0-2ubuntu2.3_amd64.deb ...
Unpacking libglvnd0:amd64 (1.0.0-2ubuntu2.3) ...
Selecting previously unselected package libx11-xcb1:amd64.
Preparing to unpack .../15-libx11-xcb1_2%3a1.6.4-3ubuntu0.2_amd64.deb ...
Unpacking libx11-xcb1:amd64 (2:1.6.4-3ubuntu0.2) ...
Selecting previously unselected package libxcb-dri2-0:amd64.
Preparing to unpack .../16-libxcb-dri2-0_1.13-2~ubuntu18.04_amd64.deb ...
Unpacking libxcb-dri2-0:amd64 (1.13-2~ubuntu18.04) ...
Selecting previously unselected package libxcb-dri3-0:amd64.
Preparing to unpack .../17-libxcb-dri3-0_1.13-2~ubuntu18.04_amd64.deb ...
Unpacking libxcb-dri3-0:amd64 (1.13-2~ubuntu18.04) ...
Selecting previously unselected package libxcb-glx0:amd64.
Preparing to unpack .../18-libxcb-glx0_1.13-2~ubuntu18.04_amd64.deb ...
Unpacking libxcb-glx0:amd64 (1.13-2~ubuntu18.04) ...
Selecting previously unselected package libxcb-present0:amd64.
Preparing to unpack .../19-libxcb-present0_1.13-2~ubuntu18.04_amd64.deb ...
Unpacking libxcb-present0:amd64 (1.13-2~ubuntu18.04) ...
Selecting previously unselected package libxcb-sync1:amd64.
Preparing to unpack .../20-libxcb-sync1_1.13-2~ubuntu18.04_amd64.deb ...
Unpacking libxcb-sync1:amd64 (1.13-2~ubuntu18.04) ...
Selecting previously unselected package libxdamage1:amd64.
Preparing to unpack .../21-libxdamage1_1%3a1.1.4-3_amd64.deb ...
Unpacking libxdamage1:amd64 (1:1.1.4-3) ...
Selecting previously unselected package libxfixes3:amd64.
Preparing to unpack .../22-libxfixes3_1%3a5.0.3-1_amd64.deb ...
Unpacking libxfixes3:amd64 (1:5.0.3-1) ...
Selecting previously unselected package libxshmfence1:amd64.
Preparing to unpack .../23-libxshmfence1_1.3-1_amd64.deb ...
Unpacking libxshmfence1:amd64 (1.3-1) ...
Selecting previously unselected package libglx-mesa0:amd64.
Preparing to unpack .../24-libglx-mesa0_19.2.8-0ubuntu0~18.04.3_amd64.deb ...
Unpacking libglx-mesa0:amd64 (19.2.8-0ubuntu0~18.04.3) ...
Selecting previously unselected package libglx0:amd64.
Preparing to unpack .../25-libglx0_1.0.0-2ubuntu2.3_amd64.deb ...
Unpacking libglx0:amd64 (1.0.0-2ubuntu2.3) ...
Selecting previously unselected package libgl1:amd64.
Preparing to unpack .../26-libgl1_1.0.0-2ubuntu2.3_amd64.deb ...
Unpacking libgl1:amd64 (1.0.0-2ubuntu2.3) ...
Selecting previously unselected package libgl1-mesa-glx:amd64.
Preparing to unpack .../27-libgl1-mesa-glx_19.2.8-0ubuntu0~18.04.3_amd64.deb ...
Unpacking libgl1-mesa-glx:amd64 (19.2.8-0ubuntu0~18.04.3) ...
Setting up libedit2:amd64 (3.1-20170329-1) ...
Setting up libxcb-present0:amd64 (1.13-2~ubuntu18.04) ...
Setting up libglvnd0:amd64 (1.0.0-2ubuntu2.3) ...
Setting up libxcb-dri2-0:amd64 (1.13-2~ubuntu18.04) ...
Setting up libxcb-dri3-0:amd64 (1.13-2~ubuntu18.04) ...
Setting up libxcb-glx0:amd64 (1.13-2~ubuntu18.04) ...
Setting up libxdamage1:amd64 (1:1.1.4-3) ...
Setting up libxfixes3:amd64 (1:5.0.3-1) ...
Setting up libelf1:amd64 (0.170-0.4ubuntu0.1) ...
Setting up libxshmfence1:amd64 (1.3-1) ...
Setting up libglapi-mesa:amd64 (19.2.8-0ubuntu0~18.04.3) ...
Setting up libdrm-common (2.4.99-1ubuntu1~18.04.2) ...
Setting up libxcb-sync1:amd64 (1.13-2~ubuntu18.04) ...
Setting up libx11-xcb1:amd64 (2:1.6.4-3ubuntu0.2) ...
Setting up libpciaccess0:amd64 (0.14-1) ...
Setting up libsensors4:amd64 (1:3.4.0-4) ...
Setting up libxxf86vm1:amd64 (1:1.1.4-1) ...
Setting up libllvm9:amd64 (1:9-2~ubuntu18.04.2) ...
Setting up libdrm2:amd64 (2.4.99-1ubuntu1~18.04.2) ...
Setting up libdrm-intel1:amd64 (2.4.99-1ubuntu1~18.04.2) ...
Setting up libdrm-radeon1:amd64 (2.4.99-1ubuntu1~18.04.2) ...
Setting up libdrm-nouveau2:amd64 (2.4.99-1ubuntu1~18.04.2) ...
Setting up libdrm-amdgpu1:amd64 (2.4.99-1ubuntu1~18.04.2) ...
Setting up libgl1-mesa-dri:amd64 (19.2.8-0ubuntu0~18.04.3) ...
Setting up libglx-mesa0:amd64 (19.2.8-0ubuntu0~18.04.3) ...
Setting up libglx0:amd64 (1.0.0-2ubuntu2.3) ...
Setting up libgl1:amd64 (1.0.0-2ubuntu2.3) ...
Setting up libgl1-mesa-glx:amd64 (19.2.8-0ubuntu0~18.04.3) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
[cont-init.d] 60-calibre-config: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[mod-init] Attempting to run Docker Modification Logic
[mod-init] Applying linuxserver/calibre-web:calibre files to container
[mod-init] linuxserver/calibre-web:calibre at sha256:6d06490839aa2fa973c5c888abc98b7f3d9f9191ddf3e41d2c2988399cd10e9d has been previously applied skipping
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 60-calibre-config: executing... 
[cont-init.d] 60-calibre-config: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[mod-init] Attempting to run Docker Modification Logic
[mod-init] Applying linuxserver/calibre-web:calibre files to container
[mod-init] linuxserver/calibre-web:calibre at sha256:6d06490839aa2fa973c5c888abc98b7f3d9f9191ddf3e41d2c2988399cd10e9d has been previously applied skipping
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 60-calibre-config: executing... 
[cont-init.d] 60-calibre-config: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

</details>

**Comment by yeraycito** [comment]
https://github.com/janeczku/calibre-web/issues/1370
The problem is not with the container but with the calibre-web (the program). It is already reported and fixed. The complete solution ( according to the developer ) will be given when I update the program at the end of May.

**Comment by 97carmine** [comment]
My mistake, I did not look well, thanks

Closing
