### ISSUE TITLE
Error starting server

### ISSUE THREAD

**Issue by FrouxBY** [linuxserver/docker-calibre-web#97]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior

When I use the compose file, the webserver should start without error and the web page is available
## Current Behavior

Using an existing database (that use to work)
After the initialization of the container, the container loop on a web starting error and a database warning:
File /app/calibre-web/calibre-web.log give this output every few seconds!
```
WARN {cps.config_sql:324} invalidating configuration
ERROR {cps.server:176} Error starting server: [Errno 13] Permission denied
```
## Steps to Reproduce

1. Pull new version of calibre-web image
2. docker-compose up -d
3. Try with various permission on the /books directory

## Environment
**OS:**  debian 11     
**CPU architecture:** x86_64
**How docker service was installed:**      

## Command used to create docker container (run/create/compose/screenshot)

    calibre_server:
        container_name: calibre_server
        image: linuxserver/calibre-web
        expose:
            - 8080
        environment:
            - PUID=1000
            - GUID=911
            - DOCKER_MODS=linuxserver/calibre-web:calibre
        networks:
            - proxy
        volumes:
                - calibre_books:/books
                - calibre_config:/config
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=proxy"
            - "traefik.http.routers.calibre.entrypoints=websecure"
            - "traefik.http.routers.calibre.rule=Host(`calibre-web.example.net`)"
            - "traefik.http.routers.calibre.tls=true"
            - "traefik.http.routers.calibre.tls.certresolver=myresolver"

## Docker logs

[mod-init] Attempting to run Docker Modification Logic
[mod-init] Applying linuxserver/calibre-web:calibre files to container
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    911
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 60-calibre-config: executing... 
Creating symlinks...
	Symlinking /app/calibre/ebook-convert to /usr/bin/ebook-convert
	Symlinking /app/calibre/ebook-meta to /usr/bin/ebook-meta
	Symlinking /app/calibre/calibre-debug to /usr/bin/calibre-debug
	Symlinking /app/calibre/calibredb to /usr/bin/calibredb
	Symlinking /app/calibre/calibre-server to /usr/bin/calibre-server
	Symlinking /app/calibre/calibre to /usr/bin/calibre
	Symlinking /app/calibre/markdown-calibre to /usr/bin/markdown-calibre
	Symlinking /app/calibre/web2disk to /usr/bin/web2disk
	Symlinking /app/calibre/ebook-viewer to /usr/bin/ebook-viewer
	Symlinking /app/calibre/lrf2lrs to /usr/bin/lrf2lrs
	Symlinking /app/calibre/calibre-customize to /usr/bin/calibre-customize
	Symlinking /app/calibre/ebook-edit to /usr/bin/ebook-edit
	Symlinking /app/calibre/fetch-ebook-metadata to /usr/bin/fetch-ebook-metadata
	Symlinking /app/calibre/calibre-parallel to /usr/bin/calibre-parallel
	Symlinking /app/calibre/ebook-device to /usr/bin/ebook-device
	Symlinking /app/calibre/lrs2lrf to /usr/bin/lrs2lrf
	Symlinking /app/calibre/calibre-smtp to /usr/bin/calibre-smtp
	Symlinking /app/calibre/ebook-polish to /usr/bin/ebook-polish
	Symlinking /app/calibre/lrfviewer to /usr/bin/lrfviewer
Setting up command-line completion...
Installing zsh completion to: /usr/share/zsh/vendor-completions/_calibre
Failed to find directory to install bash completions, using default.
Installing bash completion to: /usr/share/bash-completion/completions/

____________________ WARNING ____________________
Setting up completion failed with error:
__________________________________________________

	Traceback (most recent call last):
	  File "site-packages/calibre/linux.py", line 834, in setup_completion
	  File "site-packages/calibre/linux.py", line 576, in write_completion
	  File "site-packages/calibre/gui2/__init__.py", line 16, in <module>
	ImportError: cannot import name QApplication

Setting up desktop integration...

____________________ WARNING ____________________
Setting up desktop integration failed with error:.......
__________________________________________________

	Traceback (most recent call last):
	  File "site-packages/calibre/linux.py", line 902, in setup_desktop_integration
	  File "site-packages/calibre/linux.py", line 887, in install_icons
	  File "site-packages/calibre/linux.py", line 877, in install_single_icon
	  File "site-packages/calibre/linux.py", line 1221, in render_img
	ImportError: cannot import name QImage

Creating un-installer: /usr/bin/calibre-uninstall

There were 2 warnings

* Setting up completion failed with error:

* Setting up desktop integration failed with error:

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

[Skipped APT log]
Processing triggers for libc-bin (2.27-3ubuntu1.2) ...
[cont-init.d] 60-calibre-config: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Error starting server: [Errno 13] Permission denied

PS: in addition, it is impossible to choose an other GID than 911, abc group is always on 911 even id set differently on the compose

**Comment by FrouxBY** [comment]
I think I had issue with the app.db file,
I used an earlier backup and this is now working again

I have still a weird issue with the GUID number that I can't choose, but this might be an other issue
